Repository dotnet/machinelearning, pull requests merged in 2018-08, with the labels that each got.

#616 Allow use of property-based row classes in ML.NET
  Microsoft.ML.sln
  src/Microsoft.ML.Api/ApiUtils.cs
  src/Microsoft.ML.Api/DataViewConstructionUtils.cs
  src/Microsoft.ML.Api/InternalSchemaDefinition.cs
  src/Microsoft.ML.Api/SchemaDefinition.cs
  src/Microsoft.ML.Api/TypedCursor.cs
  src/Microsoft.ML/Data/TextLoader.cs
  test/Microsoft.ML.FSharp.Tests/Microsoft.ML.FSharp.Tests.fsproj
  test/Microsoft.ML.FSharp.Tests/Program.fs
  test/Microsoft.ML.FSharp.Tests/SmokeTests.fs
  test/Microsoft.ML.Tests/CollectionDataSourceTests.cs
  test/Microsoft.ML.Tests/TextLoaderTests.cs
  test/run-tests.proj
Labels: F#

#704 TensorFlowMapper transform for scoring Tensorflow models in ML.NET
  Microsoft.ML.sln
  build.proj
  build/Dependencies.props
  build/sign.proj
  pkg/Microsoft.ML.TensorFlow.Redist/Microsoft.ML.TensorFlow.Redist.nupkgproj
  pkg/Microsoft.ML.TensorFlow/Microsoft.ML.TensorFlow.nupkgproj
  pkg/Microsoft.ML.TensorFlow/Microsoft.ML.TensorFlow.symbols.nupkgproj
  src/Directory.Build.props
  src/Microsoft.ML.TensorFlow/Microsoft.ML.TensorFlow.csproj
  src/Microsoft.ML.TensorFlow/TensorFlow/Buffer.cs
  src/Microsoft.ML.TensorFlow/TensorFlow/Tensor.cs
  src/Microsoft.ML.TensorFlow/TensorFlow/TensorGeneric.cs
  src/Microsoft.ML.TensorFlow/TensorFlow/TensorGeneric.tt
  src/Microsoft.ML.TensorFlow/TensorFlow/Tensorflow.cs
  src/Microsoft.ML.TensorFlow/TensorFlow/TensorflowUtils.cs
  src/Microsoft.ML.TensorFlow/TensorflowTransform.cs
  src/Microsoft.ML.TensorFlow/doc.xml
  src/Microsoft.ML.Transforms/Microsoft.ML.Transforms.csproj
  src/Microsoft.ML/CSharpApi.cs
  src/Native/build.proj
  src/Redist/Microsoft.ML.TensorFlow.Redist/Microsoft.ML.TensorFlow.Redist.proj
  src/Redist/Microsoft.ML.TensorFlow.Redist/libtensorflow-cpu-darwin-x86_64-1.10.0.tar.gz.sha
  src/Redist/Microsoft.ML.TensorFlow.Redist/libtensorflow-cpu-linux-x86_64-1.10.0.tar.gz.sha
  src/Redist/Microsoft.ML.TensorFlow.Redist/libtensorflow-cpu-windows-x86_64-1.10.0.zip.sha
  src/Redist/build.proj
  test/BaselineOutput/Common/EntryPoints/core_ep-list.tsv
  test/BaselineOutput/Common/EntryPoints/core_manifest.json
  test/Microsoft.ML.Core.Tests/Microsoft.ML.Core.Tests.csproj
  test/Microsoft.ML.Core.Tests/UnitTests/TestCSharpApi.cs
  test/Microsoft.ML.Core.Tests/UnitTests/TestEntryPoints.cs
  test/Microsoft.ML.Tests/Microsoft.ML.Tests.csproj
  test/Microsoft.ML.Tests/Scenarios/TensorflowTests.cs
  test/Microsoft.ML.Tests/ScenariosWithDirectInstantiation/TensorflowTests.cs
Labels: enhancement

#753 Image transforms become Estimators
  src/Microsoft.ML.Console/Microsoft.ML.Console.csproj
  src/Microsoft.ML.Core/Data/IEstimator.cs
  src/Microsoft.ML.Data/DataLoadSave/TrivialEstimator.cs
  src/Microsoft.ML.Data/Transforms/CopyColumnsTransform.cs
  src/Microsoft.ML.Data/Transforms/OneToOneTransformerBase.cs
  src/Microsoft.ML.ImageAnalytics/EntryPoints/ImageAnalytics.cs
  src/Microsoft.ML.ImageAnalytics/ImageGrayscaleTransform.cs
  src/Microsoft.ML.ImageAnalytics/ImageLoaderTransform.cs
  src/Microsoft.ML.ImageAnalytics/ImagePixelExtractorTransform.cs
  src/Microsoft.ML.ImageAnalytics/ImageResizerTransform.cs
  src/Microsoft.ML.ImageAnalytics/ImageType.cs
  src/Microsoft.ML.StandardLearners/Standard/LinearClassificationTrainer.cs
  src/Microsoft.ML.StandardLearners/Standard/SdcaMultiClass.cs
  src/Microsoft.ML.StandardLearners/Standard/SdcaRegression.cs
  test/Microsoft.ML.TestFramework/DataPipe/TestDataPipeBase.cs
  test/Microsoft.ML.Tests/ImagesTests.cs
  test/Microsoft.ML.Tests/ScenariosWithDirectInstantiation/TensorflowTests.cs
Labels: api
