Repository dotnet/machinelearning, pull requests merged in 2018-10, with the labels that each got.

#965 Allow the creation of ONNX initializers
  src/Microsoft.ML.Data/Model/Onnx/OnnxContext.cs
  src/Microsoft.ML.Onnx/AssemblyInfo.cs
  src/Microsoft.ML.Onnx/OnnxContextImpl.cs
  src/Microsoft.ML.Onnx/OnnxUtils.cs
  test/Microsoft.ML.Tests/Microsoft.ML.Tests.csproj
  test/Microsoft.ML.Tests/OnnxTests.cs
Labels: enhancement

#1089 Char array for separators in word tokenizer
  src/Microsoft.ML.Legacy/CSharpApi.cs
  src/Microsoft.ML.Transforms/Text/TextStaticExtensions.cs
  src/Microsoft.ML.Transforms/Text/WordTokenizeTransform.cs
  src/Microsoft.ML.Transforms/Text/WrappedTextTransformers.cs
  test/BaselineOutput/Common/EntryPoints/core_manifest.json
  test/BaselineOutput/SingleDebug/SavePipe/TokenizeWithSeparatorCommandLine-Data.txt
  test/BaselineOutput/SingleDebug/SavePipe/TokenizeWithSeparatorCommandLine-Schema.txt
  test/BaselineOutput/SingleDebug/Text/tokenizedWithSeparators.tsv
  test/BaselineOutput/SingleRelease/SavePipe/TokenizeWithSeparatorCommandLine-Data.txt
  test/BaselineOutput/SingleRelease/SavePipe/TokenizeWithSeparatorCommandLine-Schema.txt
  test/BaselineOutput/SingleRelease/Text/tokenizedWithSeparators.tsv
  test/Microsoft.ML.Tests/Transformers/TextFeaturizerTests.cs
Labels: api

#1105 XML documentation references cs code for examples
  Microsoft.ML.sln
  docs/samples/Microsoft.ML.Samples/DatasetCreator.cs
  docs/samples/Microsoft.ML.Samples/Microsoft.ML.Samples.csproj
  docs/samples/Microsoft.ML.Samples/Program.cs
  docs/samples/Microsoft.ML.Samples/Trainers.cs
  src/Microsoft.ML.StandardLearners/Standard/SdcaStatic.cs
Labels: documentation

#1122 Convert RFF transform to estimators
  src/Microsoft.ML.Data/Transforms/KeyToVectorTransform.cs
  src/Microsoft.ML.Transforms/FourierDistributionSampler.cs
  src/Microsoft.ML.Transforms/RffTransform.cs
  test/BaselineOutput/SingleDebug/Rff/featurized.tsv
  test/BaselineOutput/SingleRelease/Rff/featurized.tsv
  test/Microsoft.ML.Core.Tests/UnitTests/TestEntryPoints.cs
  test/Microsoft.ML.Tests/Transformers/RffTests.cs
Labels: api

#1134 Conversion of Hogwild SGD to estimator
  src/Microsoft.ML.Data/Training/TrainerUtils.cs
  src/Microsoft.ML.Legacy/CSharpApi.cs
  src/Microsoft.ML.StandardLearners/Standard/LinearClassificationStatic.cs
  src/Microsoft.ML.StandardLearners/Standard/LinearClassificationTrainer.cs
  test/BaselineOutput/Common/EntryPoints/core_manifest.json
  test/Microsoft.ML.StaticPipelineTesting/Training.cs
  test/Microsoft.ML.Tests/TrainerEstimators/TrainerEstimators.cs
Labels: api

#1163 Changing the namespace where the trainers live
  docs/samples/Microsoft.ML.Samples/DatasetCreator.cs
  docs/samples/Microsoft.ML.Samples/Program.cs
  docs/samples/Microsoft.ML.Samples/Trainers.cs
  src/Microsoft.ML.FastTree/FastTreeStatic.cs
  src/Microsoft.ML.KMeansClustering/KMeansStatic.cs
  src/Microsoft.ML.LightGBM/LightGbmStatic.cs
  src/Microsoft.ML.StandardLearners/FactorizationMachine/FactorizationMachineStatic.cs
  src/Microsoft.ML.StandardLearners/Standard/LinearClassificationStatic.cs
  src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/LbfgsStatic.cs
  src/Microsoft.ML.StandardLearners/Standard/MultiClass/MultiClassNaiveBayesStatic.cs
  src/Microsoft.ML.StandardLearners/Standard/Online/OnlineLearnerStatic.cs
  src/Microsoft.ML.StandardLearners/Standard/SdcaStatic.cs
  test/Microsoft.ML.StaticPipelineTesting/Training.cs
  test/Microsoft.ML.Tests/Scenarios/Api/CookbookSamples/CookbookSamples.cs
Labels: api, documentation

#947 Save ConvertTransform as ONNX Operator and Control the Use of Experimental Features with a Flag
  src/Microsoft.ML.Data/DataView/RowToRowMapperTransform.cs
  src/Microsoft.ML.Data/Model/Onnx/ICanSaveOnnx.cs
  src/Microsoft.ML.Data/Model/Onnx/OnnxContext.cs
  src/Microsoft.ML.Data/Prediction/Calibrator.cs
  src/Microsoft.ML.Data/Scorers/GenericScorer.cs
  src/Microsoft.ML.Data/Scorers/MultiClassClassifierScorer.cs
  src/Microsoft.ML.Data/Scorers/PredictedLabelScorerBase.cs
  src/Microsoft.ML.Data/Scorers/SchemaBindablePredictorWrapper.cs
  src/Microsoft.ML.Data/Transforms/ConcatTransform.cs
  src/Microsoft.ML.Data/Transforms/ConvertTransform.cs
  src/Microsoft.ML.Data/Transforms/KeyToVectorTransform.cs
  src/Microsoft.ML.Data/Transforms/NormalizeColumn.cs
  src/Microsoft.ML.Data/Transforms/NormalizeUtils.cs
  src/Microsoft.ML.Data/Transforms/Normalizer.cs
  src/Microsoft.ML.Data/Transforms/TermTransform.cs
  src/Microsoft.ML.Data/Transforms/TransformBase.cs
  src/Microsoft.ML.FastTree/FastTree.cs
  src/Microsoft.ML.Legacy/CSharpApi.cs
  src/Microsoft.ML.Onnx/OnnxContextImpl.cs
  src/Microsoft.ML.Onnx/OnnxUtils.cs
  src/Microsoft.ML.Onnx/SaveOnnxCommand.cs
  src/Microsoft.ML.StandardLearners/Standard/LinearPredictor.cs
  src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/MulticlassLogisticRegression.cs
  src/Microsoft.ML.Transforms/NAReplaceTransform.cs
  test/BaselineOutput/Common/EntryPoints/core_manifest.json
  test/Microsoft.ML.Tests/OnnxTests.cs
Labels: enhancement

#952 Connect Inputs and Outputs Properly and Export CopyColumnTransform to (unofficial) ONNX operator
  src/Microsoft.ML.Data/Model/Onnx/OnnxContext.cs
  src/Microsoft.ML.Data/Transforms/CopyColumnsTransform.cs
  src/Microsoft.ML.Onnx/OnnxContextImpl.cs
  src/Microsoft.ML.Onnx/SaveOnnxCommand.cs
  test/BaselineOutput/Common/Onnx/BinaryClassification/BreastCancer/BinaryClassificationFastTreeSaveModelToOnnxTest.json
  test/BaselineOutput/Common/Onnx/BinaryClassification/BreastCancer/BinaryClassificationLRSaveModelToOnnxTest.json
  test/BaselineOutput/Common/Onnx/BinaryClassification/BreastCancer/BinaryClassificationLightGBMSaveModelToOnnxTest.json
  test/BaselineOutput/Common/Onnx/BinaryClassification/BreastCancer/KeyToVectorBag.json
  test/BaselineOutput/Common/Onnx/MultiClassClassification/BreastCancer/MultiClassificationLRSaveModelToOnnxTest.json
Labels: enhancement

#1212 Save Kmeans in ONNX
  src/Microsoft.ML.KMeansClustering/KMeansPredictor.cs
  test/BaselineOutput/Common/Onnx/Cluster/BreastCancer/Kmeans.json
  test/BaselineOutput/Common/Onnx/Cluster/BreastCancer/Kmeans.onnx
  test/Microsoft.ML.Tests/OnnxTests.cs
Labels: enhancement

#1252 ML Context to create them all
  docs/code/MlNetCookBook.md
  docs/samples/Microsoft.ML.Samples/Trainers.cs
  src/Microsoft.ML.Data/DataLoadSave/DataLoadSaveCatalog.cs
  src/Microsoft.ML.Data/DataLoadSave/Text/TextLoader.cs
  src/Microsoft.ML.Data/DataLoadSave/Text/TextLoaderSaverCatalog.cs
  src/Microsoft.ML.Data/Evaluators/EvaluatorStaticExtensions.cs
  src/Microsoft.ML.Data/MLContext.cs
  src/Microsoft.ML.Data/Model/ModelOperationsCatalog.cs
  src/Microsoft.ML.Data/TrainContext.cs
  src/Microsoft.ML.Data/Transforms/CatalogUtils.cs
  src/Microsoft.ML.Data/Transforms/Normalizer.cs
  src/Microsoft.ML.Data/Transforms/NormalizerCatalog.cs
  src/Microsoft.ML.Data/Transforms/TransformsCatalog.cs
  src/Microsoft.ML.FastTree/FastTreeCatalog.cs
  src/Microsoft.ML.FastTree/FastTreeStatic.cs
  src/Microsoft.ML.FastTree/Microsoft.ML.FastTree.csproj
  src/Microsoft.ML.KMeansClustering/KMeansCatalog.cs
  src/Microsoft.ML.KMeansClustering/KMeansStatic.cs
  src/Microsoft.ML.LightGBM/LightGbmCatalog.cs
  src/Microsoft.ML.LightGBM/LightGbmStatic.cs
  src/Microsoft.ML.StandardLearners/FactorizationMachine/FactorizationMachineCatalog.cs
  src/Microsoft.ML.StandardLearners/FactorizationMachine/FactorizationMachineStatic.cs
  src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/LbfgsCatalog.cs
  src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/LbfgsStatic.cs
  src/Microsoft.ML.StandardLearners/Standard/Online/OnlineLearnerCatalog.cs
  src/Microsoft.ML.StandardLearners/Standard/Online/OnlineLearnerStatic.cs
  src/Microsoft.ML.StandardLearners/Standard/SdcaCatalog.cs
  src/Microsoft.ML.StandardLearners/Standard/SdcaStatic.cs
  src/Microsoft.ML.StandardLearners/Standard/SgdCatalog.cs
  src/Microsoft.ML.StandardLearners/Standard/SgdStatic.cs
  src/Microsoft.ML.Transforms/CategoricalCatalog.cs
  src/Microsoft.ML.Transforms/CategoricalHashTransform.cs
  src/Microsoft.ML.Transforms/CategoricalTransform.cs
  src/Microsoft.ML.Transforms/TextTransformCatalog.cs
  test/Microsoft.ML.Benchmarks/KMeansAndLogisticRegressionBench.cs
  test/Microsoft.ML.Predictor.Tests/TestPredictors.cs
  test/Microsoft.ML.StaticPipelineTesting/Training.cs
  test/Microsoft.ML.TestFramework/BaseTestBaseline.cs
  test/Microsoft.ML.Tests/Scenarios/Api/CookbookSamples/CookbookSamples.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/CrossValidation.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/DecomposableTrainAndPredict.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/Evaluation.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/Extensibility.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/FileBasedSavingOfData.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/IntrospectiveTraining.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/Metacomponents.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/MultithreadedPrediction.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/ReconfigurablePrediction.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/SimpleTrainAndPredict.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/TrainSaveModelAndPredict.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/TrainWithInitialPredictor.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/TrainWithValidationSet.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/Visibility.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/Wrappers.cs
  test/Microsoft.ML.Tests/ScenariosWithDirectInstantiation/TensorflowTests.cs
  test/Microsoft.ML.Tests/Transformers/NormalizerTests.cs
Labels: api

#1276 Convert TextNormalizer to estimator
  src/Microsoft.ML.Data/Transforms/HashTransform.cs
  src/Microsoft.ML.Data/Transforms/KeyToVectorTransform.cs
  src/Microsoft.ML.Legacy/CSharpApi.cs
  src/Microsoft.ML.Transforms/RffTransform.cs
  src/Microsoft.ML.Transforms/Text/TextNormalizerTransform.cs
  src/Microsoft.ML.Transforms/Text/TextStaticExtensions.cs
  src/Microsoft.ML.Transforms/Text/TextTransform.cs
  src/Microsoft.ML.Transforms/Text/WrappedTextTransformers.cs
  test/BaselineOutput/Common/Text/Normalized.tsv
  test/Microsoft.ML.Benchmarks/StochasticDualCoordinateAscentClassifierBench.cs
  test/Microsoft.ML.FSharp.Tests/SmokeTests.fs
  test/Microsoft.ML.StaticPipelineTesting/StaticPipeTests.cs
  test/Microsoft.ML.Tests/Scenarios/Api/SimpleTrainAndPredict.cs
  test/Microsoft.ML.Tests/Scenarios/ClusteringTests.cs
  test/Microsoft.ML.Tests/Scenarios/PipelineApi/SimpleTrainAndPredict.cs
  test/Microsoft.ML.Tests/Scenarios/SentimentPredictionTests.cs
  test/Microsoft.ML.Tests/ScenariosWithDirectInstantiation/SentimentPredictionTests.cs
  test/Microsoft.ML.Tests/Transformers/TextFeaturizerTests.cs
  test/Microsoft.ML.Tests/Transformers/TextNormalizer.cs
  test/Microsoft.ML.Tests/Transformers/WordEmbeddingsTests.cs
Labels: api

#1281 Extension on IDataReader<IMultiStreamSource>, and DataReader<IMultiStreamSource, TShape> to read from one or several file paths, rather than requiring constructing an IMultiStreamSource
  docs/code/MlNetCookBook.md
  docs/samples/Microsoft.ML.Samples/Trainers.cs
  src/Microsoft.ML.Data/DataLoadSave/MultiFileSource.cs
  src/Microsoft.ML.Data/DataLoadSave/Text/TextLoaderStatic.cs
  test/Microsoft.ML.Benchmarks/PredictionEngineBench.cs
  test/Microsoft.ML.Core.Tests/UnitTests/FileSource.cs
  test/Microsoft.ML.OnnxTransformTest/OnnxTransformTests.cs
  test/Microsoft.ML.StaticPipelineTesting/StaticPipeTests.cs
  test/Microsoft.ML.Tests/Scenarios/Api/CookbookSamples/CookbookSamples.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/Evaluation.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Evaluation.cs
  test/Microsoft.ML.Tests/Scenarios/GetColumnTests.cs
  test/Microsoft.ML.Tests/TensorFlowEstimatorTests.cs
  test/Microsoft.ML.Tests/TermEstimatorTests.cs
  test/Microsoft.ML.Tests/TrainerEstimators/FAFMEstimator.cs
  test/Microsoft.ML.Tests/TrainerEstimators/OnlineLinearTests.cs
  test/Microsoft.ML.Tests/TrainerEstimators/PriorRandomTests.cs
  test/Microsoft.ML.Tests/TrainerEstimators/SdcaTests.cs
  test/Microsoft.ML.Tests/TrainerEstimators/TrainerEstimators.cs
  test/Microsoft.ML.Tests/Transformers/CategoricalHashTests.cs
  test/Microsoft.ML.Tests/Transformers/CategoricalTests.cs
  test/Microsoft.ML.Tests/Transformers/FeatureSelectionTests.cs
  test/Microsoft.ML.Tests/Transformers/KeyToBinaryVectorEstimatorTest.cs
  test/Microsoft.ML.Tests/Transformers/KeyToValueTests.cs
  test/Microsoft.ML.Tests/Transformers/KeyToVectorEstimatorTests.cs
  test/Microsoft.ML.Tests/Transformers/NAReplaceTests.cs
  test/Microsoft.ML.Tests/Transformers/NormalizerTests.cs
  test/Microsoft.ML.Tests/Transformers/PcaTests.cs
  test/Microsoft.ML.Tests/Transformers/RffTests.cs
  test/Microsoft.ML.Tests/Transformers/TextFeaturizerTests.cs
  test/Microsoft.ML.Tests/Transformers/WordEmbeddingsTests.cs
Labels: api

#1217 Conversion of NAIndicatorTransform to estimator with related pigstensions
  src/Microsoft.ML.Transforms/NAHandleTransform.cs
  src/Microsoft.ML.Transforms/NAHandling.cs
  src/Microsoft.ML.Transforms/NAIndicatorTransform.cs
  test/BaselineOutput/Common/EntryPoints/core_ep-list.tsv
  test/BaselineOutput/SingleDebug/NAIndicator/featurized.tsv
  test/BaselineOutput/SingleRelease/NAIndicator/featurized.tsv
  test/Microsoft.ML.StaticPipelineTesting/StaticPipeTests.cs
  test/Microsoft.ML.Tests/TrainerEstimators/LbfgsTests.cs
  test/Microsoft.ML.Tests/TrainerEstimators/SymSgdClassificationTests.cs
  test/Microsoft.ML.Tests/TrainerEstimators/TrainerEstimators.cs
  test/Microsoft.ML.Tests/Transformers/NAIndicatorTests.cs
Labels: api

#1285 Convert WordTokenize to estimator
  src/Microsoft.ML.Legacy/CSharpApi.cs
  src/Microsoft.ML.Transforms/EntryPoints/TextAnalytics.cs
  src/Microsoft.ML.Transforms/Text/TextStaticExtensions.cs
  src/Microsoft.ML.Transforms/Text/TextTransform.cs
  src/Microsoft.ML.Transforms/Text/WordBagTransform.cs
  src/Microsoft.ML.Transforms/Text/WordHashBagTransform.cs
  src/Microsoft.ML.Transforms/Text/WordTokenizeTransform.cs
  src/Microsoft.ML.Transforms/Text/WrappedTextTransformers.cs
  test/BaselineOutput/Common/EntryPoints/core_ep-list.tsv
  test/BaselineOutput/SingleDebug/SavePipe/TokenizeWithSeparatorCommandLine-Schema.txt
  test/BaselineOutput/SingleRelease/SavePipe/TokenizeWithSeparatorCommandLine-Schema.txt
  test/Microsoft.ML.Tests/Transformers/TextFeaturizerTests.cs
  test/Microsoft.ML.Tests/Transformers/WordTokenizeTests.cs
Labels: api

#1361 sample for dynamic SDCA binary
  docs/samples/Microsoft.ML.Samples/Dynamic/SDCA.cs
  docs/samples/Microsoft.ML.Samples/Program.cs
  docs/samples/Microsoft.ML.Samples/Static/Trainers.cs
  docs/samples/Microsoft.ML.Samples/Static/Transformers.cs
  src/Microsoft.ML.SamplesUtils/SamplesDatasetUtils.cs
  src/Microsoft.ML.StandardLearners/Standard/SdcaCatalog.cs
Labels: api, documentation

#1306 Introducing official x86 CI build
  .vsts-dotnet-ci.yml
  build/vsts-ci.yml
Labels: Build

#1390 Kill all dotnet processes after build
  run.cmd
Labels: Build

#1309 Introducing PR verification x86 CI build
  .vsts-dotnet-ci.yml
  build/ci/phase-template.yml
  init-tools.cmd
  pkg/Microsoft.ML.TensorFlow.Redist/Microsoft.ML.TensorFlow.Redist.nupkgproj
  run.cmd
  test/Microsoft.ML.Benchmarks.Tests/BenchmarksTest.cs
  test/Microsoft.ML.TestFramework/BaseTestBaseline.cs
  test/Microsoft.ML.Tests/ScenariosWithDirectInstantiation/TensorflowTests.cs
  test/Microsoft.ML.Tests/TensorFlowEstimatorTests.cs
Labels: Build

#1352 Trainer estimator cleanup for FastTrees and LightGBM
  src/Microsoft.ML.Data/Training/TrainerEstimatorBase.cs
  src/Microsoft.ML.Data/Training/TrainerUtils.cs
  src/Microsoft.ML.FastTree/BoostingFastTree.cs
  src/Microsoft.ML.FastTree/FastTree.cs
  src/Microsoft.ML.FastTree/FastTreeCatalog.cs
  src/Microsoft.ML.FastTree/FastTreeClassification.cs
  src/Microsoft.ML.FastTree/FastTreeRanking.cs
  src/Microsoft.ML.FastTree/FastTreeRegression.cs
  src/Microsoft.ML.FastTree/FastTreeTweedie.cs
  src/Microsoft.ML.FastTree/GamClassification.cs
  src/Microsoft.ML.FastTree/GamRegression.cs
  src/Microsoft.ML.FastTree/GamTrainer.cs
  src/Microsoft.ML.FastTree/RandomForest.cs
  src/Microsoft.ML.FastTree/RandomForestClassification.cs
  src/Microsoft.ML.FastTree/RandomForestRegression.cs
  src/Microsoft.ML.FastTree/TreeTrainersCatalog.cs
  src/Microsoft.ML.FastTree/TreeTrainersStatic.cs
  src/Microsoft.ML.HalLearners/OlsLinearRegression.cs
  src/Microsoft.ML.LightGBM/LightGbmBinaryTrainer.cs
  src/Microsoft.ML.LightGBM/LightGbmCatalog.cs
  src/Microsoft.ML.LightGBM/LightGbmMulticlassTrainer.cs
  src/Microsoft.ML.LightGBM/LightGbmRankingTrainer.cs
  src/Microsoft.ML.LightGBM/LightGbmRegressionTrainer.cs
  src/Microsoft.ML.LightGBM/LightGbmStatic.cs
  src/Microsoft.ML.LightGBM/LightGbmTrainerBase.cs
  src/Microsoft.ML.StandardLearners/FactorizationMachine/FactorizationMachineCatalog.cs
  src/Microsoft.ML.StandardLearners/FactorizationMachine/FactorizationMachineStatic.cs
  src/Microsoft.ML.StandardLearners/Standard/LinearClassificationTrainer.cs
  src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/LbfgsPredictorBase.cs
  src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/MulticlassLogisticRegression.cs
  src/Microsoft.ML.StandardLearners/Standard/MultiClass/MultiClassNaiveBayesTrainer.cs
  src/Microsoft.ML.StandardLearners/Standard/SdcaCatalog.cs
  src/Microsoft.ML.StandardLearners/Standard/SdcaMultiClass.cs
  src/Microsoft.ML.StandardLearners/Standard/SdcaRegression.cs
  src/Microsoft.ML.StandardLearners/Standard/SdcaStatic.cs
  test/Microsoft.ML.StaticPipelineTesting/Training.cs
Labels: api

#1407 Enable statically-typed matrix factorization
  src/Microsoft.ML.Data/DataLoadSave/Text/TextLoaderStatic.cs
  src/Microsoft.ML.Recommender/MatrixFactorizationPredictor.cs
  src/Microsoft.ML.Recommender/MatrixFactorizationStatic.cs
  src/Microsoft.ML.Recommender/MatrixFactorizationTrainer.cs
  test/Microsoft.ML.StaticPipelineTesting/Microsoft.ML.StaticPipelineTesting.csproj
  test/Microsoft.ML.StaticPipelineTesting/StaticPipeTests.cs
  test/Microsoft.ML.StaticPipelineTesting/Training.cs
  test/Microsoft.ML.Tests/TrainerEstimators/MatrixFactorizationTests.cs
Labels: enhancement

#1321 Transforms components docs
  docs/samples/Microsoft.ML.Samples/Dynamic/ConcatTransform.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/KeyToValue_Term.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/MinMaxNormalizer.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/TextTransform.cs
  docs/samples/Microsoft.ML.Samples/Microsoft.ML.Samples.csproj
  docs/samples/Microsoft.ML.Samples/Program.cs
  docs/samples/Microsoft.ML.Samples/Static/FastTree.cs
  docs/samples/Microsoft.ML.Samples/Static/LightGBM.cs
  docs/samples/Microsoft.ML.Samples/Static/SDCA.cs
  docs/samples/Microsoft.ML.Samples/Static/Trainers.cs
  docs/samples/Microsoft.ML.Samples/Static/Transformers.cs
  src/Microsoft.ML.Data/Transforms/ColumnConcatenatingEstimator.cs
  src/Microsoft.ML.Data/Transforms/NormalizerCatalog.cs
  src/Microsoft.ML.FastTree/TreeTrainersStatic.cs
  src/Microsoft.ML.LightGBM/LightGbmStatic.cs
  src/Microsoft.ML.SamplesUtils/SamplesDatasetUtils.cs
  src/Microsoft.ML.StandardLearners/Standard/SdcaCatalog.cs
  src/Microsoft.ML.StandardLearners/Standard/SdcaStatic.cs
  src/Microsoft.ML.Transforms/TextTransformCatalog.cs
  test/data/README.md
  test/data/gplv2/COPYING.txt
  test/data/gplv2/airquality.csv
  test/data/gplv2/infert.csv
  test/data/topics.csv
Labels: api, documentation

#1457 more namespace move for transforms
  src/Microsoft.ML.Ensemble/Selector/SubsetSelector/BootstrapSelector.cs
  src/Microsoft.ML.Transforms/CategoricalTransform.cs
  src/Microsoft.ML.Transforms/GroupTransform.cs
  src/Microsoft.ML.Transforms/KeyToBinaryVectorTransform.cs
  src/Microsoft.ML.Transforms/LearnerFeatureSelection.cs
  src/Microsoft.ML.Transforms/LoadTransform.cs
  src/Microsoft.ML.Transforms/MissingValueIndicatorTransform.cs
  src/Microsoft.ML.Transforms/MutualInformationFeatureSelection.cs
  src/Microsoft.ML.Transforms/OptionalColumnTransform.cs
  src/Microsoft.ML.Transforms/TermLookupTransform.cs
  src/Microsoft.ML.Transforms/UngroupTransform.cs
  src/Microsoft.ML.Transforms/WhiteningTransform.cs
  src/Microsoft.ML.Transforms/WrappedFeatureSelectionTransformers.cs
  test/BaselineOutput/Common/EntryPoints/core_ep-list.tsv
  test/Microsoft.ML.Core.Tests/UnitTests/TestEntryPoints.cs
  test/Microsoft.ML.Tests/Transformers/KeyToBinaryVectorEstimatorTest.cs
Labels: api

#1458 Last namespace re-org
  src/Microsoft.ML.Data/Commands/CrossValidationCommand.cs
  src/Microsoft.ML.Data/TrainContext.cs
  src/Microsoft.ML.Data/Transforms/ConversionsCatalog.cs
  src/Microsoft.ML.Data/Transforms/HashTransform.cs
  src/Microsoft.ML.PCA/PcaTransform.cs
  src/Microsoft.ML.Transforms/CategoricalHashTransform.cs
  src/Microsoft.ML.Transforms/Text/LdaTransform.cs
  src/Microsoft.ML.Transforms/Text/NgramHashTransform.cs
  src/Microsoft.ML.Transforms/Text/NgramTransform.cs
  src/Microsoft.ML.Transforms/Text/SentimentAnalyzerTransform.cs
  src/Microsoft.ML.Transforms/Text/StopWordsRemoverTransform.cs
  src/Microsoft.ML.Transforms/Text/TextStaticExtensions.cs
  src/Microsoft.ML.Transforms/Text/WordEmbeddingsTransform.cs
  src/Microsoft.ML.Transforms/Text/WrappedTextTransformers.cs
  test/BaselineOutput/Common/EntryPoints/core_ep-list.tsv
  test/Microsoft.ML.Benchmarks/StochasticDualCoordinateAscentClassifierBench.cs
  test/Microsoft.ML.TestFramework/DataPipe/TestDataPipe.cs
  test/Microsoft.ML.Tests/Scenarios/Api/SimpleTrainAndPredict.cs
  test/Microsoft.ML.Tests/ScenariosWithDirectInstantiation/SentimentPredictionTests.cs
  test/Microsoft.ML.Tests/Transformers/HashTests.cs
  test/Microsoft.ML.Tests/Transformers/PcaTests.cs
  test/Microsoft.ML.Tests/Transformers/WordEmbeddingsTests.cs
Labels: api

#1467 Fix unassigned public field
  src/Microsoft.ML.Recommender/MatrixFactorizationPredictor.cs
  test/Microsoft.ML.Tests/TrainerEstimators/MatrixFactorizationTests.cs
Labels: bug

#1450 Add doc for MF
  docs/samples/Microsoft.ML.Samples/Dynamic/MatrixFactorization.cs
  docs/samples/Microsoft.ML.Samples/Microsoft.ML.Samples.csproj
  src/Microsoft.ML.Recommender/MatrixFactorizationTrainer.cs
  test/Microsoft.ML.Tests/TrainerEstimators/MatrixFactorizationTests.cs
Labels: documentation
