Repository dotnet/machinelearning, pull requests merged in 2018-11, with the labels that each got.

#1453 namespace moves for more transforms
  src/Microsoft.ML.Legacy/Runtime/EntryPoints/TrainTestSplit.cs
  src/Microsoft.ML.PCA/PcaTransform.cs
  src/Microsoft.ML.Transforms/BootstrapSampleTransform.cs
  src/Microsoft.ML.Transforms/CategoricalHashTransform.cs
  src/Microsoft.ML.Transforms/CategoricalTransform.cs
  src/Microsoft.ML.Transforms/CompositeTransform.cs
  src/Microsoft.ML.Transforms/GcnTransform.cs
  src/Microsoft.ML.Transforms/GroupTransform.cs
  src/Microsoft.ML.Transforms/HashJoinTransform.cs
  src/Microsoft.ML.Transforms/RffTransform.cs
  src/Microsoft.ML.Transforms/Text/TextTransform.cs
  src/Microsoft.ML.Transforms/WhiteningTransform.cs
  src/Microsoft.ML.Transforms/WrappedGcnTransformers.cs
  src/Microsoft.ML.Transforms/WrappedWhiteningTransformer.cs
  test/BaselineOutput/Common/EntryPoints/core_ep-list.tsv
  test/Microsoft.ML.Benchmarks/PredictionEngineBench.cs
  test/Microsoft.ML.Core.Tests/UnitTests/TestEntryPoints.cs
  test/Microsoft.ML.StaticPipelineTesting/StaticPipeTests.cs
  test/Microsoft.ML.Tests/Transformers/PcaTests.cs
  test/Microsoft.ML.Tests/Transformers/RffTests.cs
Labels: api

#1494 Adding another handful transform's extensions
  src/Microsoft.ML.Data/Transforms/CategoricalCatalog.cs
  src/Microsoft.ML.Data/Transforms/ConversionsCatalog.cs
  src/Microsoft.ML.Data/Transforms/TransformsCatalog.cs
  src/Microsoft.ML.OnnxTransform/OnnxCatalog.cs
  src/Microsoft.ML.PCA/PCACatalog.cs
  src/Microsoft.ML.Transforms/ExtensionsCatalog.cs
  src/Microsoft.ML.Transforms/ProjectionCatalog.cs
Labels: api

#1513 Better explanation of Score's initial value
  docs/samples/Microsoft.ML.Samples/Dynamic/MatrixFactorization.cs
Labels: documentation

#1520 Add the `BestFriend` attribute for restricting cross-assembly internal access
  src/Microsoft.ML.Core/BestFriendAttribute.cs
  test/Microsoft.ML.CodeAnalyzer.Tests/Code/BestFriendTest.cs
  test/Microsoft.ML.CodeAnalyzer.Tests/Helpers/DiagnosticVerifier.cs
  test/Microsoft.ML.CodeAnalyzer.Tests/Helpers/TestUtils.cs
  test/Microsoft.ML.CodeAnalyzer.Tests/Microsoft.ML.CodeAnalyzer.Tests.csproj
  test/Microsoft.ML.CodeAnalyzer.Tests/Resources/BestFriendDeclaration.cs
  test/Microsoft.ML.CodeAnalyzer.Tests/Resources/BestFriendUser.cs
  tools-local/Microsoft.ML.InternalCodeAnalyzer/BestFriendAnalyzer.cs
Labels: api

#1507 Fix zero based key input from C# classes for matrix factorization
  src/Microsoft.ML.Api/DataViewConstructionUtils.cs
  src/Microsoft.ML.Recommender/MatrixFactorizationPredictor.cs
  src/Microsoft.ML.Recommender/MatrixFactorizationTrainer.cs
  test/Microsoft.ML.Tests/TrainerEstimators/MatrixFactorizationTests.cs
Labels: bug, enhancement

#1546 removing space that is causing the docs CI to fail
  src/Microsoft.ML.Data/Transforms/NormalizerCatalog.cs
Labels: documentation

#1555 adding more logging to failures.
  test/Microsoft.ML.TestFramework/BaseTestBaseline.cs
Labels: test

#1558 sample link and xml format fixes
  src/Microsoft.ML.Data/Transforms/NormalizerCatalog.cs
  src/Microsoft.ML.FastTree/TreeTrainersStatic.cs
  src/Microsoft.ML.LightGBM/LightGbmStatic.cs
  src/Microsoft.ML.Recommender/MatrixFactorizationTrainer.cs
  src/Microsoft.ML.StandardLearners/Standard/SdcaStatic.cs
  src/Microsoft.ML.TimeSeries/IidChangePointDetector.cs
  src/Microsoft.ML.TimeSeries/IidSpikeDetector.cs
  src/Microsoft.ML.TimeSeries/SsaChangePointDetector.cs
  src/Microsoft.ML.TimeSeries/SsaSpikeDetector.cs
  src/Microsoft.ML.Transforms/TextCatalog.cs
Labels: documentation

#1588 Renaming transforms to transformers Part 1
  src/Microsoft.ML.Ensemble/Selector/SubsetSelector/BootstrapSelector.cs
  src/Microsoft.ML.Legacy/AssemblyRegistration.cs
  src/Microsoft.ML.Legacy/CSharpApi.cs
  src/Microsoft.ML.PipelineInference/TransformInference.cs
  src/Microsoft.ML.Transforms/BootstrapSampleTransformer.cs
  src/Microsoft.ML.Transforms/CategoricalCatalog.cs
  src/Microsoft.ML.Transforms/CompositeTransformer.cs
  src/Microsoft.ML.Transforms/CountFeatureSelectionTransformer.cs
  src/Microsoft.ML.Transforms/EntryPoints/SelectFeatures.cs
  src/Microsoft.ML.Transforms/MissingValueIndicatorTransformer.cs
  src/Microsoft.ML.Transforms/NAHandleTransform.cs
  src/Microsoft.ML.Transforms/NAHandling.cs
  src/Microsoft.ML.Transforms/OneHotEncodingTransformer.cs
  src/Microsoft.ML.Transforms/OneHotHashEncodingTransformer.cs
  src/Microsoft.ML.Transforms/WrappedFeatureSelectionTransformers.cs
  test/BaselineOutput/Common/EntryPoints/core_ep-list.tsv
  test/Microsoft.ML.Benchmarks/Text/MultiClassClassification.cs
  test/Microsoft.ML.Core.Tests/UnitTests/TestEntryPoints.cs
  test/Microsoft.ML.TestFramework/EnvironmentExtensions.cs
  test/Microsoft.ML.Tests/LearningPipelineTests.cs
  test/Microsoft.ML.Tests/OnnxTests.cs
  test/Microsoft.ML.Tests/Scenarios/Api/CookbookSamples/CookbookSamplesDynamicApi.cs
  test/Microsoft.ML.Tests/Transformers/CategoricalHashTests.cs
  test/Microsoft.ML.Tests/Transformers/CategoricalTests.cs
  test/Microsoft.ML.Tests/Transformers/ConvertTests.cs
Labels: api

#1590 more transform => transformer renaming
  src/Microsoft.ML.Legacy/CSharpApi.cs
  src/Microsoft.ML.PipelineInference/TransformInference.cs
  src/Microsoft.ML.Transforms/ExtensionsCatalog.cs
  src/Microsoft.ML.Transforms/MissingValueDroppingTransformer.cs
  src/Microsoft.ML.Transforms/MissingValueHandlingTransformer.cs
  src/Microsoft.ML.Transforms/MissingValueReplacing.cs
  src/Microsoft.ML.Transforms/MissingValueReplacingUtils.cs
  src/Microsoft.ML.Transforms/NAHandling.cs
  src/Microsoft.ML.Transforms/ProjectionCatalog.cs
  src/Microsoft.ML.Transforms/RandomFourierFeaturizing.cs
  src/Microsoft.ML.Transforms/TermLookupTransformer.cs
  src/Microsoft.ML.Transforms/Text/WordBagTransform.cs
  src/Microsoft.ML.Transforms/Text/WordHashBagTransform.cs
  src/Microsoft.ML.Transforms/VectorWhitening.cs
  test/BaselineOutput/Common/EntryPoints/core_ep-list.tsv
  test/BaselineOutput/Common/SavePipe/SavePipeLabelParsers-Schema.txt
  test/BaselineOutput/Common/SavePipe/SavePipeLabelParsers1-Schema.txt
  test/BaselineOutput/Common/SavePipe/SavePipeLabelParsers2-Schema.txt
  test/BaselineOutput/Common/SavePipe/SavePipeLabelParsers3-Schema.txt
  test/BaselineOutput/Common/SavePipe/SavePipeLabelParsers4-Schema.txt
  test/BaselineOutput/Common/SavePipe/SavePipeLabelParsers5-Schema.txt
  test/Microsoft.ML.Benchmarks/Helpers/EnvironmentFactory.cs
  test/Microsoft.ML.Core.Tests/UnitTests/TestEntryPoints.cs
  test/Microsoft.ML.Tests/Transformers/NAReplaceTests.cs
  test/Microsoft.ML.Tests/Transformers/RffTests.cs
Labels: api

#1571 Printing out test scores in training phase for FastTree
  src/Microsoft.ML.Core/Prediction/TrainContext.cs
  src/Microsoft.ML.Core/Prediction/TrainerInfo.cs
  src/Microsoft.ML.Data/Commands/TrainCommand.cs
  src/Microsoft.ML.Data/Commands/TrainTestCommand.cs
  src/Microsoft.ML.Data/Training/TrainerEstimatorBase.cs
  src/Microsoft.ML.FastTree/Dataset/Dataset.cs
  src/Microsoft.ML.FastTree/FastTree.cs
  src/Microsoft.ML.FastTree/FastTreeClassification.cs
  src/Microsoft.ML.FastTree/FastTreeRanking.cs
  src/Microsoft.ML.FastTree/FastTreeRegression.cs
  src/Microsoft.ML.FastTree/FastTreeTweedie.cs
  src/Microsoft.ML.FastTree/RandomForestClassification.cs
  src/Microsoft.ML.FastTree/RandomForestRegression.cs
  test/BaselineOutput/Common/FastForestRegression/FastForestRegression-TrainTest-housing-out.txt
  test/BaselineOutput/Common/FastForestRegression/QuantileRegressorTester-TrainTest-housing-out.txt
  test/BaselineOutput/Common/FastRank/FastRank-TrainTest-breast-cancer-out.txt
  test/BaselineOutput/SingleDebug/FastForestClassification/FastForestClassification-TrainTest-breast-cancer-out.txt
  test/BaselineOutput/SingleDebug/FastTreeBinaryClassification/FastTree-TrainTest-Census-Cat-Only.Cat-out.txt
  test/BaselineOutput/SingleDebug/FastTreeBinaryClassification/FastTree-TrainTest-Census.Cat-out.txt
  test/BaselineOutput/SingleDebug/FastTreeBinaryClassification/FastTree-TrainTest-breast-cancer-group-out.txt
  test/BaselineOutput/SingleDebug/FastTreeBinaryClassification/FastTree-TrainTest-breast-cancer-out.txt
  test/BaselineOutput/SingleDebug/FastTreeBinaryClassification/FastTreeBsr-TrainTest-breast-cancer-out.txt
  test/BaselineOutput/SingleDebug/FastTreeBinaryClassification/FastTreeCategorical-TrainTest-Census-Cat-Only.Cat-out.txt
  test/BaselineOutput/SingleDebug/FastTreeBinaryClassification/FastTreeCategorical-TrainTest-Census.Cat-out.txt
  test/BaselineOutput/SingleDebug/FastTreeBinaryClassification/FastTreeCategoricalDisk-TrainTest-Census-Cat-Only.Cat-out.txt
  test/BaselineOutput/SingleDebug/FastTreeBinaryClassification/FastTreeCategoricalDisk-TrainTest-Census.Cat-out.txt
  test/BaselineOutput/SingleDebug/FastTreeBinaryClassification/FastTreeDisk-TrainTest-Census-Cat-Only.Cat-out.txt
  test/BaselineOutput/SingleDebug/FastTreeBinaryClassification/FastTreeDisk-TrainTest-Census.Cat-out.txt
  test/BaselineOutput/SingleDebug/FastTreeBinaryClassification/FastTreeDisk-TrainTest-breast-cancer-out.txt
  test/BaselineOutput/SingleDebug/FastTreeBinaryClassification/FastTreeDrop-TrainTest-breast-cancer-out.txt
  test/BaselineOutput/SingleDebug/FastTreeBinaryClassification/FastTreeHighMinDocs-TrainTest-breast-cancer-out.txt
  test/BaselineOutput/SingleRelease/FastForestClassification/FastForestClassification-CV-breast-cancer-out.txt
  test/BaselineOutput/SingleRelease/FastForestClassification/FastForestClassification-TrainTest-breast-cancer-out.txt
  test/BaselineOutput/SingleRelease/FastTreeBinaryClassification/FastTree-TrainTest-Census-Cat-Only.Cat-out.txt
  test/BaselineOutput/SingleRelease/FastTreeBinaryClassification/FastTree-TrainTest-Census.Cat-out.txt
  test/BaselineOutput/SingleRelease/FastTreeBinaryClassification/FastTree-TrainTest-breast-cancer-group-out.txt
  test/BaselineOutput/SingleRelease/FastTreeBinaryClassification/FastTree-TrainTest-breast-cancer-out.txt
  test/BaselineOutput/SingleRelease/FastTreeBinaryClassification/FastTreeBsr-TrainTest-breast-cancer-out.txt
  test/BaselineOutput/SingleRelease/FastTreeBinaryClassification/FastTreeCategorical-TrainTest-Census-Cat-Only.Cat-out.txt
  test/BaselineOutput/SingleRelease/FastTreeBinaryClassification/FastTreeCategorical-TrainTest-Census.Cat-out.txt
  test/BaselineOutput/SingleRelease/FastTreeBinaryClassification/FastTreeCategoricalDisk-TrainTest-Census-Cat-Only.Cat-out.txt
  test/BaselineOutput/SingleRelease/FastTreeBinaryClassification/FastTreeCategoricalDisk-TrainTest-Census.Cat-out.txt
  test/BaselineOutput/SingleRelease/FastTreeBinaryClassification/FastTreeDisk-TrainTest-Census-Cat-Only.Cat-out.txt
  test/BaselineOutput/SingleRelease/FastTreeBinaryClassification/FastTreeDisk-TrainTest-Census.Cat-out.txt
  test/BaselineOutput/SingleRelease/FastTreeBinaryClassification/FastTreeDisk-TrainTest-breast-cancer-out.txt
  test/BaselineOutput/SingleRelease/FastTreeBinaryClassification/FastTreeDrop-TrainTest-breast-cancer-out.txt
  test/BaselineOutput/SingleRelease/FastTreeBinaryClassification/FastTreeHighMinDocs-TrainTest-breast-cancer-out.txt
Labels: enhancement

#1642 Fix GAM default options and values
  src/Microsoft.ML.FastTree/GamClassification.cs
  src/Microsoft.ML.FastTree/GamRegression.cs
  src/Microsoft.ML.FastTree/GamTrainer.cs
  src/Microsoft.ML.FastTree/TreeTrainersCatalog.cs
Labels: bug

#1594 Exposing normalizer parameters
  docs/samples/Microsoft.ML.Samples/Dynamic/Normalizer.cs
  docs/samples/Microsoft.ML.Samples/Program.cs
  docs/samples/Microsoft.ML.Samples/Static/AveragedPerceptronBinaryClassification.cs
  docs/samples/Microsoft.ML.Samples/Static/FastTreeBinaryClassification.cs
  docs/samples/Microsoft.ML.Samples/Static/FastTreeRegression.cs
  docs/samples/Microsoft.ML.Samples/Static/LightGBMBinaryClassification.cs
  docs/samples/Microsoft.ML.Samples/Static/LightGBMRegression.cs
  docs/samples/Microsoft.ML.Samples/Static/SDCABinaryClassification.cs
  docs/samples/Microsoft.ML.Samples/Static/SDCARegression.cs
  src/Microsoft.ML.Data/Transforms/NormalizeColumn.cs
  src/Microsoft.ML.Data/Transforms/NormalizeColumnDbl.cs
  src/Microsoft.ML.Data/Transforms/NormalizeColumnSng.cs
  src/Microsoft.ML.Data/Transforms/NormalizeUtils.cs
  src/Microsoft.ML.Data/Transforms/Normalizer.cs
  src/Microsoft.ML.Data/Transforms/NormalizerCatalog.cs
  src/Microsoft.ML.Data/Transforms/NormalizerStaticExtensions.cs
  src/Microsoft.ML.Transforms/EntryPoints/TextAnalytics.cs
  test/Microsoft.ML.Tests/TrainerEstimators/OnlineLinearTests.cs
  test/Microsoft.ML.Tests/Transformers/NormalizerTests.cs
Labels: api

#1676 Contracts.Assert statements valid for Debug-Intrinsics
  Directory.Build.props
  src/Microsoft.ML.CpuMath/AssemblyInfo.cs
  src/Microsoft.ML.CpuMath/AvxIntrinsics.cs
  src/Microsoft.ML.CpuMath/CpuMathUtils.netcoreapp.cs
  src/Microsoft.ML.CpuMath/Microsoft.ML.CpuMath.csproj
  src/Microsoft.ML.CpuMath/SseIntrinsics.cs
Labels: Build

#1782 Add LDA example to Microsoft.ML.Samples
  docs/samples/Microsoft.ML.Samples/Dynamic/LdaTransform.cs
  docs/samples/Microsoft.ML.Samples/Microsoft.ML.Samples.csproj
  docs/samples/Microsoft.ML.Samples/Program.cs
  src/Microsoft.ML.Transforms/Text/TextCatalog.cs
Labels: documentation
