Repository dotnet/machinelearning, pull requests merged in 2018-09, with the labels that each got.

#759 Term transformer implementation
  src/Microsoft.ML.Data/DataView/RowToRowMapperTransform.cs
  src/Microsoft.ML.Data/Model/Onnx/ICanSaveOnnx.cs
  src/Microsoft.ML.Data/Model/Pfa/ICanSavePfa.cs
  src/Microsoft.ML.Data/Transforms/CopyColumnsTransform.cs
  src/Microsoft.ML.Data/Transforms/OneToOneTransformerBase.cs
  src/Microsoft.ML.Data/Transforms/TermEstimator.cs
  src/Microsoft.ML.Data/Transforms/TermTransform.cs
  src/Microsoft.ML.Data/Transforms/TermTransformImpl.cs
  src/Microsoft.ML.Transforms/CategoricalTransform.cs
  src/Microsoft.ML.Transforms/EntryPoints/TextAnalytics.cs
  src/Microsoft.ML.Transforms/Text/WordBagTransform.cs
  src/Microsoft.ML.Transforms/Text/WordHashBagTransform.cs
  src/Microsoft.ML/Runtime/EntryPoints/FeatureCombiner.cs
  test/BaselineOutput/SingleDebug/Term/Term.tsv
  test/BaselineOutput/SingleRelease/Term/Term.tsv
  test/Microsoft.ML.Core.Tests/UnitTests/TestEntryPoints.cs
  test/Microsoft.ML.TestFramework/DataPipe/TestDataPipeBase.cs
  test/Microsoft.ML.Tests/CopyColumnEstimatorTests.cs
  test/Microsoft.ML.Tests/Scenarios/Api/DecomposableTrainAndPredict.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/DecomposableTrainAndPredict.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/Extensibility.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/Metacomponents.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/Wrappers.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Extensibility.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Metacomponents.cs
  test/Microsoft.ML.Tests/TermEstimatorTests.cs
Labels: api

#811 Update README badges to point to dnceng
  README.md
Labels: Build

#813 Update badges to new definition name
  README.md
Labels: Build

#797 Converted normalizers to be estimators
  src/Microsoft.ML.Data/Transforms/NormalizeColumn.cs
  src/Microsoft.ML.Data/Transforms/NormalizeColumnDbl.cs
  src/Microsoft.ML.Data/Transforms/NormalizeColumnSng.cs
  src/Microsoft.ML.Data/Transforms/NormalizeTransform.cs
  src/Microsoft.ML.Data/Transforms/NormalizeUtils.cs
  src/Microsoft.ML.Data/Transforms/Normalizer.cs
  src/Microsoft.ML/CSharpApi.cs
  test/BaselineOutput/Common/EntryPoints/core_ep-list.tsv
  test/BaselineOutput/Common/EntryPoints/core_manifest.json
  test/BaselineOutput/SingleDebug/Normalizer/normalized.tsv
  test/BaselineOutput/SingleRelease/Normalizer/normalized.tsv
  test/Microsoft.ML.Tests/Transformers/NormalizerTests.cs
Labels: api

#812 Pigsty examples
  test/Microsoft.ML.Tests/Scenarios/Api/AspirationalExamples.cs
Labels: api, test

#809 Some pigsty examples
  test/Microsoft.ML.Tests/Scenarios/Api/AspirationalExamples.cs
Labels: api

#801 Text estimator
  src/Microsoft.ML.Transforms/Text/TextTransform.cs
  test/BaselineOutput/SingleDebug/Text/featurized.tsv
  test/BaselineOutput/SingleRelease/Text/featurized.tsv
  test/Microsoft.ML.TestFramework/DataPipe/TestDataPipeBase.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/CrossValidation.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/Evaluation.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/FileBasedSavingOfData.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/IntrospectiveTraining.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/MultithreadedPrediction.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/ReconfigurablePrediction.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/SimpleTrainAndPredict.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/TrainSaveModelAndPredict.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/TrainWithInitialPredictor.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/TrainWithValidationSet.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/Visibility.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/Wrappers.cs
  test/Microsoft.ML.Tests/Transformers/TextFeaturizerTests.cs
Labels: api

#728 Made IRowMapper take IRow for metadata
  src/Microsoft.ML.Data/Data/IColumn.cs
  src/Microsoft.ML.Data/DataView/RowToRowMapperTransform.cs
  src/Microsoft.ML.Data/DataView/SimpleRow.cs
  src/Microsoft.ML.Data/Transforms/CopyColumnsTransform.cs
  src/Microsoft.ML.Data/Transforms/OneToOneTransformerBase.cs
  src/Microsoft.ML.Data/Transforms/TermTransform.cs
Labels: api

#845 SchemaShape.Column metadata is now SchemaShape not string array
  src/Microsoft.ML.Core/Data/IEstimator.cs
  src/Microsoft.ML.Core/Data/MetadataUtils.cs
  src/Microsoft.ML.Data/StaticPipe/StaticSchemaShape.cs
  src/Microsoft.ML.Data/Training/TrainerEstimatorBase.cs
  src/Microsoft.ML.Data/Transforms/CopyColumnsTransform.cs
  src/Microsoft.ML.Data/Transforms/Normalizer.cs
  src/Microsoft.ML.Data/Transforms/TermEstimator.cs
  src/Microsoft.ML.ImageAnalytics/ImageGrayscaleTransform.cs
  src/Microsoft.ML.ImageAnalytics/ImageLoaderTransform.cs
  src/Microsoft.ML.ImageAnalytics/ImagePixelExtractorTransform.cs
  src/Microsoft.ML.ImageAnalytics/ImageResizerTransform.cs
  src/Microsoft.ML.Transforms/Text/TextTransform.cs
  test/Microsoft.ML.TestFramework/DataPipe/TestDataPipeBase.cs
Labels: api

#843 Statically Typed Normalizer Estimators
  build/Dependencies.props
  src/Microsoft.ML.Data/Microsoft.ML.Data.csproj
  src/Microsoft.ML.Data/Transforms/NormalizeColumn.cs
  src/Microsoft.ML.Data/Transforms/NormalizeColumnDbl.cs
  src/Microsoft.ML.Data/Transforms/NormalizeColumnSng.cs
  src/Microsoft.ML.Data/Transforms/NormalizeUtils.cs
  src/Microsoft.ML.Data/Transforms/Normalizer.cs
  src/Microsoft.ML.Data/Transforms/NormalizerStaticExtensions.cs
  test/Microsoft.ML.StaticPipelineTesting/StaticPipeTests.cs
Labels: api

#840 TensorFlow estimator
  src/Microsoft.ML.Data/DataLoadSave/TrivialEstimator.cs
  src/Microsoft.ML.Data/Transforms/CopyColumnsTransform.cs
  src/Microsoft.ML.TensorFlow/TensorflowTransform.cs
  src/Microsoft.ML.TensorFlow/doc.xml
  src/Microsoft.ML/CSharpApi.cs
  test/BaselineOutput/Common/EntryPoints/core_manifest.json
  test/Microsoft.ML.Tests/ScenariosWithDirectInstantiation/TensorflowTests.cs
  test/Microsoft.ML.Tests/TensorFlowEstimatorTests.cs
  test/Microsoft.ML.Tests/TermEstimatorTests.cs
Labels: api

#851 For the GitHub issues classification aspirational example, the 'Area' is not needed as input to Predict(), since it is the label.
  test/Microsoft.ML.Tests/Scenarios/Api/AspirationalExamples.cs
Labels: api, test

#849 Ap, LinearSVM, OGD as estimators
  src/Microsoft.ML.Data/Training/TrainerEstimatorBase.cs
  src/Microsoft.ML.StandardLearners/Standard/LinearClassificationTrainer.cs
  src/Microsoft.ML.StandardLearners/Standard/LinearPredictor.cs
  src/Microsoft.ML.StandardLearners/Standard/Online/AveragedLinear.cs
  src/Microsoft.ML.StandardLearners/Standard/Online/AveragedPerceptron.cs
  src/Microsoft.ML.StandardLearners/Standard/Online/LinearSvm.cs
  src/Microsoft.ML.StandardLearners/Standard/Online/OnlineGradientDescent.cs
  src/Microsoft.ML.StandardLearners/Standard/Online/OnlineLinear.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/TrainWithInitialPredictor.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/Wrappers.cs
Labels: api

#870 Term estimators in static pipeline
  src/Microsoft.ML.Data/Microsoft.ML.Data.csproj
  src/Microsoft.ML.Data/Transforms/TermEstimator.cs
  src/Microsoft.ML.Data/Transforms/TermStaticExtensions.cs
  src/Microsoft.ML.Data/Transforms/TermStaticExtensions.tt
  src/Microsoft.ML.Data/Transforms/TermTransform.cs
  src/Microsoft.ML.Data/Transforms/TermTransformImpl.cs
  test/Microsoft.ML.StaticPipelineTesting/StaticPipeTests.cs
Labels: api

#869 Static pipeline column indexers, binary/regression evaluators
  src/Microsoft.ML.Data/Evaluators/BinaryClassifierEvaluator.cs
  src/Microsoft.ML.Data/Evaluators/RegressionEvaluator.cs
  src/Microsoft.ML.Data/StaticPipe/SchemaBearing.cs
  src/Microsoft.ML.Data/StaticPipe/StaticPipeInternalUtils.cs
  src/Microsoft.ML.Data/StaticPipe/StaticPipeUtils.cs
  src/Microsoft.ML.Data/Utils/LossFunctions.cs
  test/Microsoft.ML.StaticPipelineTesting/Microsoft.ML.StaticPipelineTesting.csproj
  test/Microsoft.ML.StaticPipelineTesting/Training.cs
Labels: api

#882 TensorFlow static extensions, SDCA multiclass static extensions
  src/Microsoft.ML.Api/PredictionFunction.cs
  src/Microsoft.ML.Data/Evaluators/MulticlassClassifierEvaluator.cs
  src/Microsoft.ML.Data/Evaluators/RegressionEvaluator.cs
  src/Microsoft.ML.Data/StaticPipe/TrainerEstimatorReconciler.cs
  src/Microsoft.ML.Data/Training/TrainerEstimatorBase.cs
  src/Microsoft.ML.StandardLearners/Standard/LinearClassificationTrainer.cs
  src/Microsoft.ML.StandardLearners/Standard/Online/AveragedPerceptron.cs
  src/Microsoft.ML.StandardLearners/Standard/Online/LinearSvm.cs
  src/Microsoft.ML.StandardLearners/Standard/Online/OnlineGradientDescent.cs
  src/Microsoft.ML.StandardLearners/Standard/SdcaMultiClass.cs
  src/Microsoft.ML.StandardLearners/Standard/SdcaRegression.cs
  src/Microsoft.ML.StandardLearners/Standard/SdcaStatic.cs
  src/Microsoft.ML.TensorFlow/TensorflowTransform.cs
  test/Microsoft.ML.StaticPipelineTesting/Training.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/DecomposableTrainAndPredict.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/Extensibility.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/MultithreadedPrediction.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/SimpleTrainAndPredict.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/TrainSaveModelAndPredict.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/Wrappers.cs
  test/Microsoft.ML.Tests/TensorFlowEstimatorTests.cs
Labels: api

#856 Converted KeyToValue to estimator
  src/Microsoft.ML.Data/Data/IColumn.cs
  src/Microsoft.ML.Data/DataLoadSave/TrivialEstimator.cs
  src/Microsoft.ML.Data/DataView/RowToRowMapperTransform.cs
  src/Microsoft.ML.Data/Evaluators/EvaluatorUtils.cs
  src/Microsoft.ML.Data/Transforms/CopyColumnsTransform.cs
  src/Microsoft.ML.Data/Transforms/KeyToValueTransform.cs
  src/Microsoft.ML.Data/Transforms/TermTransformImpl.cs
  src/Microsoft.ML.Transforms/CategoricalTransform.cs
  src/Microsoft.ML/Runtime/EntryPoints/FeatureCombiner.cs
  test/BaselineOutput/SingleDebug/KeyToValue/featurized.tsv
  test/BaselineOutput/SingleRelease/KeyToValue/featurized.tsv
  test/Microsoft.ML.Tests/Scenarios/Api/DecomposableTrainAndPredict.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/DecomposableTrainAndPredict.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/Extensibility.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/Metacomponents.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/Wrappers.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Extensibility.cs
  test/Microsoft.ML.Tests/Transformers/KeyToValueTests.cs
  test/Microsoft.ML.Tests/Transformers/TextFeaturizerTests.cs
Labels: api

#858 KeyToVector estimators
  src/Microsoft.ML.Data/Transforms/KeyToVectorTransform.cs
  src/Microsoft.ML.Data/Transforms/TermTransform.cs
  src/Microsoft.ML.Transforms/CategoricalTransform.cs
  src/Microsoft.ML.Transforms/KeyToBinaryVectorTransform.cs
  src/Microsoft.ML/Runtime/EntryPoints/FeatureCombiner.cs
  test/Microsoft.ML.StaticPipelineTesting/StaticPipeFakes.cs
  test/Microsoft.ML.TestFramework/BaseTestBaseline.cs
  test/Microsoft.ML.Tests/Transformers/KeyToBinaryVectorEstimatorTest.cs
  test/Microsoft.ML.Tests/Transformers/KeyToVectorEstimatorTests.cs
Labels: api

#865 Ova and Pkpd as estimators
  src/Microsoft.ML.Data/Prediction/Calibrator.cs
  src/Microsoft.ML.Ensemble/OutputCombiners/MultiStacking.cs
  src/Microsoft.ML.StandardLearners/Standard/MultiClass/MetaMulticlassTrainer.cs
  src/Microsoft.ML.StandardLearners/Standard/MultiClass/Ova.cs
  src/Microsoft.ML.StandardLearners/Standard/MultiClass/Pkpd.cs
  test/Microsoft.ML.TestFramework/DataPipe/TestDataPipeBase.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/Metacomponents.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/Wrappers.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Metacomponents.cs
  test/Microsoft.ML.Tests/Scenarios/Api/SimpleTrainAndPredict.cs
  test/Microsoft.ML.Tests/TrainerEstimators/MetalinearEstimators.cs
Labels: api

#909 Fix for trainer estimator metadata propagation
  src/Microsoft.ML.Core/Data/MetadataUtils.cs
  src/Microsoft.ML.Data/Training/TrainerEstimatorBase.cs
  src/Microsoft.ML.StandardLearners/Standard/LinearClassificationTrainer.cs
  src/Microsoft.ML.StandardLearners/Standard/Online/AveragedPerceptron.cs
  src/Microsoft.ML.StandardLearners/Standard/Online/OnlineGradientDescent.cs
  src/Microsoft.ML.StandardLearners/Standard/SdcaMultiClass.cs
  src/Microsoft.ML.StandardLearners/Standard/SdcaRegression.cs
  test/Microsoft.ML.TestFramework/DataPipe/TestDataPipeBase.cs
  test/Microsoft.ML.Tests/TrainerEstimators/OnlineLinearTests.cs
  test/Microsoft.ML.Tests/TrainerEstimators/SdcaTests.cs
Labels: api

#896 Transformer for Concat
  src/Microsoft.ML.Data/DataView/RowToRowMapperTransform.cs
  src/Microsoft.ML.Data/EntryPoints/SchemaManipulation.cs
  src/Microsoft.ML.Data/Transforms/ConcatEstimator.cs
  src/Microsoft.ML.Data/Transforms/ConcatTransform.cs
  src/Microsoft.ML.Transforms/NAHandleTransform.cs
  src/Microsoft.ML.Transforms/Text/TextTransform.cs
  src/Microsoft.ML.Transforms/Text/WordBagTransform.cs
  src/Microsoft.ML/Runtime/EntryPoints/FeatureCombiner.cs
  test/BaselineOutput/SingleDebug/Transform/Concat/Concat2.tsv
  test/BaselineOutput/SingleRelease/Transform/Concat/Concat2.tsv
  test/Microsoft.ML.Benchmarks/KMeansAndLogisticRegressionBench.cs
  test/Microsoft.ML.Core.Tests/UnitTests/TestEntryPoints.cs
  test/Microsoft.ML.Tests/Scenarios/Api/DecomposableTrainAndPredict.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/DecomposableTrainAndPredict.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/Extensibility.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/Metacomponents.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/Wrappers.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Extensibility.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Metacomponents.cs
  test/Microsoft.ML.Tests/ScenariosWithDirectInstantiation/IrisPlantClassificationTests.cs
  test/Microsoft.ML.Tests/ScenariosWithDirectInstantiation/TensorflowTests.cs
  test/Microsoft.ML.Tests/Transformers/ConcatTests.cs
Labels: api

#899 Categorical estimator
  src/Microsoft.ML.Data/Transforms/KeyToVectorTransform.cs
  src/Microsoft.ML.Data/Transforms/TermEstimator.cs
  src/Microsoft.ML.Data/Transforms/TermTransform.cs
  src/Microsoft.ML.Data/Transforms/TermTransformImpl.cs
  src/Microsoft.ML.Transforms/CategoricalHashTransform.cs
  src/Microsoft.ML.Transforms/CategoricalTransform.cs
  src/Microsoft.ML.Transforms/KeyToBinaryVectorTransform.cs
  test/BaselineOutput/SingleDebug/Categorical/featurized.tsv
  test/BaselineOutput/SingleRelease/Categorical/featurized.tsv
  test/Microsoft.ML.Benchmarks/KMeansAndLogisticRegressionBench.cs
  test/Microsoft.ML.Predictor.Tests/TestPredictors.cs
  test/Microsoft.ML.Tests/Transformers/CategoricalTests.cs
  test/Microsoft.ML.Tests/Transformers/KeyToBinaryVectorEstimatorTest.cs
  test/Microsoft.ML.Tests/Transformers/KeyToVectorEstimatorTests.cs
Labels: api

#931 Transform wrappers and a reference implementation for tokenizers
  src/Microsoft.ML.Data/DataLoadSave/FakeSchema.cs
  src/Microsoft.ML.Data/DataLoadSave/TransformWrapper.cs
  src/Microsoft.ML.Transforms/Text/TextStaticExtensions.cs
  src/Microsoft.ML.Transforms/Text/WrappedTextTransformers.cs
  test/BaselineOutput/SingleDebug/Text/tokenized.tsv
  test/BaselineOutput/SingleRelease/Text/tokenized.tsv
  test/Microsoft.ML.StaticPipelineTesting/StaticPipeTests.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/Wrappers.cs
  test/Microsoft.ML.Tests/Transformers/TextFeaturizerTests.cs
Labels: api

#855 Tree estimators
  src/Microsoft.ML.Api/TypedCursor.cs
  src/Microsoft.ML.Data/Scorers/PredictionTransformer.cs
  src/Microsoft.ML.Ensemble/OutputCombiners/MultiStacking.cs
  src/Microsoft.ML.Ensemble/OutputCombiners/RegressionStacking.cs
  src/Microsoft.ML.Ensemble/OutputCombiners/Stacking.cs
  src/Microsoft.ML.FastTree/BoostingFastTree.cs
  src/Microsoft.ML.FastTree/FastTree.cs
  src/Microsoft.ML.FastTree/FastTreeClassification.cs
  src/Microsoft.ML.FastTree/FastTreeRanking.cs
  src/Microsoft.ML.FastTree/FastTreeRegression.cs
  src/Microsoft.ML.FastTree/FastTreeTweedie.cs
  src/Microsoft.ML.FastTree/RandomForest.cs
  src/Microsoft.ML.FastTree/RandomForestClassification.cs
  src/Microsoft.ML.FastTree/RandomForestRegression.cs
  src/Microsoft.ML.Legacy/Runtime/EntryPoints/CodeGen/TransformGenerators.cs
  src/Microsoft.ML.Sweeper/Algorithms/SmacSweeper.cs
  test/Microsoft.ML.Core.Tests/UnitTests/TestEntryPoints.cs
  test/Microsoft.ML.Predictor.Tests/Test-API.cs
  test/Microsoft.ML.Predictor.Tests/TestPredictors.cs
  test/Microsoft.ML.TestFramework/BaseTestBaseline.cs
  test/Microsoft.ML.TestFramework/DataPipe/TestDataPipeBase.cs
  test/Microsoft.ML.TestFramework/Datasets.cs
  test/Microsoft.ML.Tests/Scenarios/Api/ApiScenariosTests.cs
  test/Microsoft.ML.Tests/Scenarios/Api/AspirationalExamples.cs
  test/Microsoft.ML.Tests/Scenarios/Api/AutoNormalizationAndCaching.cs
  test/Microsoft.ML.Tests/Scenarios/Api/CrossValidation.cs
  test/Microsoft.ML.Tests/Scenarios/Api/DecomposableTrainAndPredict.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/CrossValidation.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/DecomposableTrainAndPredict.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/Evaluation.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/Extensibility.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/FileBasedSavingOfData.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/IntrospectiveTraining.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/Metacomponents.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/MultithreadedPrediction.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/ReconfigurablePrediction.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/SimpleTrainAndPredict.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/TrainSaveModelAndPredict.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/TrainWithInitialPredictor.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/TrainWithValidationSet.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/Visibility.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Evaluation.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Extensibility.cs
  test/Microsoft.ML.Tests/Scenarios/Api/FileBasedSavingOfData.cs
  test/Microsoft.ML.Tests/Scenarios/Api/IntrospectiveTraining.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Metacomponents.cs
  test/Microsoft.ML.Tests/Scenarios/Api/MultithreadedPrediction.cs
  test/Microsoft.ML.Tests/Scenarios/Api/ReconfigurablePrediction.cs
  test/Microsoft.ML.Tests/Scenarios/Api/SimpleTrainAndPredict.cs
  test/Microsoft.ML.Tests/Scenarios/Api/TrainSaveModelAndPredict.cs
  test/Microsoft.ML.Tests/Scenarios/Api/TrainWithInitialPredictor.cs
  test/Microsoft.ML.Tests/Scenarios/Api/TrainWithValidationSet.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Visibility.cs
  test/Microsoft.ML.Tests/ScenariosWithDirectInstantiation/SentimentPredictionTests.cs
  test/Microsoft.ML.Tests/TrainerEstimators/TreeEstimators.cs
Labels: api

#917 NAReplace estimator
  src/Microsoft.ML.Data/Transforms/KeyToVectorTransform.cs
  src/Microsoft.ML.Legacy/CSharpApi.cs
  src/Microsoft.ML.Transforms/KeyToBinaryVectorTransform.cs
  src/Microsoft.ML.Transforms/NAHandleTransform.cs
  src/Microsoft.ML.Transforms/NAHandling.cs
  src/Microsoft.ML.Transforms/NAReplaceTransform.cs
  src/Microsoft.ML.Transforms/NAReplaceUtils.cs
  test/BaselineOutput/SingleDebug/NAReplace/featurized.tsv
  test/BaselineOutput/SingleRelease/NAReplace/featurized.tsv
  test/Microsoft.ML.Tests/Transformers/KeyToBinaryVectorEstimatorTest.cs
  test/Microsoft.ML.Tests/Transformers/KeyToVectorEstimatorTests.cs
  test/Microsoft.ML.Tests/Transformers/NAReplaceTests.cs
Labels: api

#912 FAFM to estimator
  src/Microsoft.ML.Core/Data/IEstimator.cs
  src/Microsoft.ML.Data/Prediction/IPredictionTransformer.cs
  src/Microsoft.ML.Data/Scorers/PredictionTransformer.cs
  src/Microsoft.ML.Data/Training/ITrainerEstimator.cs
  src/Microsoft.ML.Data/Training/TrainerEstimatorBase.cs
  src/Microsoft.ML.Data/Training/TrainerEstimatorContext.cs
  src/Microsoft.ML.FastTree/BoostingFastTree.cs
  src/Microsoft.ML.FastTree/FastTree.cs
  src/Microsoft.ML.FastTree/RandomForest.cs
  src/Microsoft.ML.StandardLearners/FactorizationMachine/FactorizationMachineTrainer.cs
  src/Microsoft.ML.StandardLearners/FactorizationMachine/FieldAwareFactorizationMachinePredictor.cs
  src/Microsoft.ML.StandardLearners/FactorizationMachine/FieldAwareFactorizationMachineUtils.cs
  src/Microsoft.ML.StandardLearners/Standard/LinearClassificationTrainer.cs
  src/Microsoft.ML.StandardLearners/Standard/MultiClass/MetaMulticlassTrainer.cs
  src/Microsoft.ML.StandardLearners/Standard/MultiClass/Ova.cs
  src/Microsoft.ML.StandardLearners/Standard/MultiClass/Pkpd.cs
  src/Microsoft.ML.StandardLearners/Standard/Online/AveragedLinear.cs
  src/Microsoft.ML.StandardLearners/Standard/Online/AveragedPerceptron.cs
  src/Microsoft.ML.StandardLearners/Standard/Online/OnlineLinear.cs
  src/Microsoft.ML.StandardLearners/Standard/StochasticTrainerBase.cs
  test/Microsoft.ML.Tests/Microsoft.ML.Tests.csproj
  test/Microsoft.ML.Tests/TrainerEstimators/FAFMEstimator.cs
  test/Microsoft.ML.Tests/TrainerEstimators/MetalinearEstimators.cs
  test/Microsoft.ML.Tests/TrainerEstimators/OnlineLinearTests.cs
  test/Microsoft.ML.Tests/TrainerEstimators/SdcaTests.cs
  test/Microsoft.ML.Tests/TrainerEstimators/TrainerEstimators.cs
Labels: api

#963 enabling scanning the constructors with non-public visibility, and re…
  src/Microsoft.ML.Core/ComponentModel/ComponentCatalog.cs
  src/Microsoft.ML.FastTree/FastTreeClassification.cs
  src/Microsoft.ML.FastTree/FastTreeRanking.cs
  src/Microsoft.ML.FastTree/FastTreeRegression.cs
  src/Microsoft.ML.FastTree/FastTreeTweedie.cs
  src/Microsoft.ML.FastTree/GamClassification.cs
  src/Microsoft.ML.FastTree/GamRegression.cs
  src/Microsoft.ML.FastTree/RandomForestClassification.cs
  src/Microsoft.ML.FastTree/RandomForestRegression.cs
  src/Microsoft.ML.StandardLearners/Standard/MultiClass/Pkpd.cs
  src/Microsoft.ML.StandardLearners/Standard/SdcaMultiClass.cs
  src/Microsoft.ML.StandardLearners/Standard/SdcaRegression.cs
  test/Microsoft.ML.Benchmarks/StochasticDualCoordinateAscentClassifierBench.cs
  test/Microsoft.ML.Tests/Scenarios/Api/DecomposableTrainAndPredict.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/DecomposableTrainAndPredict.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Extensibility.cs
  test/Microsoft.ML.Tests/ScenariosWithDirectInstantiation/IrisPlantClassificationTests.cs
Labels: api

#944 Hash estimator
  src/Microsoft.ML.Data/Commands/CrossValidationCommand.cs
  src/Microsoft.ML.Data/Transforms/HashTransform.cs
  src/Microsoft.ML.Data/Transforms/TermEstimator.cs
  src/Microsoft.ML.Transforms/CategoricalHashTransform.cs
  src/Microsoft.ML.Transforms/Text/WordBagTransform.cs
  src/Microsoft.ML.Transforms/Text/WordHashBagTransform.cs
  test/Microsoft.ML.TestFramework/DataPipe/TestDataPipe.cs
  test/Microsoft.ML.Tests/Transformers/HashTests.cs
Labels: api

#967 Binary train context with evaluation and SDCA
  src/Microsoft.ML.Data/Evaluators/BinaryClassifierEvaluator.cs
  src/Microsoft.ML.Data/Evaluators/EvaluatorStaticExtensions.cs
  src/Microsoft.ML.Data/Training/TrainContext.cs
  src/Microsoft.ML.StandardLearners/Standard/SdcaStatic.cs
  test/Microsoft.ML.StaticPipelineTesting/Training.cs
Labels: api

#940 Added the GetColumn functionality to dynamic API
  src/Microsoft.ML.Data/StaticPipe/DataView.cs
  src/Microsoft.ML.Data/Utilities/ColumnCursor.cs
  test/Microsoft.ML.Tests/Scenarios/GetColumnTests.cs
Labels: api

#993 Extended contexts to regression and multiclass, added FFM pigstension
  src/Microsoft.ML.Data/Evaluators/EvaluatorStaticExtensions.cs
  src/Microsoft.ML.Data/Evaluators/MulticlassClassifierEvaluator.cs
  src/Microsoft.ML.Data/Evaluators/RegressionEvaluator.cs
  src/Microsoft.ML.Data/StaticPipe/TrainerEstimatorReconciler.cs
  src/Microsoft.ML.Data/Training/TrainContext.cs
  src/Microsoft.ML.StandardLearners/FactorizationMachine/FactorizationMachineStatic.cs
  src/Microsoft.ML.StandardLearners/Standard/SdcaStatic.cs
  test/Microsoft.ML.StaticPipelineTesting/Microsoft.ML.StaticPipelineTesting.csproj
  test/Microsoft.ML.StaticPipelineTesting/Training.cs
  test/Microsoft.ML.Tests/Microsoft.ML.Tests.csproj
Labels: api

#999 Add analayzer to nuget
  pkg/Directory.Build.props
  src/Directory.Build.targets
  src/Microsoft.ML.Analyzer/Microsoft.ML.Analyzer.csproj
Labels: api

#1002 Conversion of ordinary least square linear regression (OlsLinearRegression) to estimator
  src/Microsoft.ML.HalLearners/OlsLinearRegression.cs
  test/Microsoft.ML.Tests/TrainerEstimators/OlsLinearRegressionTests.cs
Labels: api

#957 Conversion of Logistic, Multiclass Logistic, and Poisson Regression to estimators
  src/Microsoft.ML.Ensemble/Trainer/Multiclass/MulticlassDataPartitionEnsembleTrainer.cs
  src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/LbfgsPredictorBase.cs
  src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/LogisticRegression.cs
  src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/MulticlassLogisticRegression.cs
  src/Microsoft.ML.StandardLearners/Standard/PoissonRegression/PoissonRegression.cs
  test/Microsoft.ML.Benchmarks/KMeansAndLogisticRegressionBench.cs
  test/Microsoft.ML.Core.Tests/UnitTests/TestEntryPoints.cs
  test/Microsoft.ML.Tests/TrainerEstimators/LbfgsTests.cs
  test/Microsoft.ML.Tests/TrainerEstimators/OlsLinearRegressionTests.cs
Labels: api

#996 PcaTrainer as estimator
  src/Microsoft.ML.Data/Scorers/BinaryClassifierScorer.cs
  src/Microsoft.ML.Data/Scorers/PredictionTransformer.cs
  src/Microsoft.ML.PCA/PcaTrainer.cs
  src/Microsoft.ML.StandardLearners/FactorizationMachine/FieldAwareFactorizationMachinePredictor.cs
  test/Microsoft.ML.Tests/TrainerEstimators/TrainerEstimators.cs
Labels: api

#1012 Conversion of Parallel Stochastic Gradient Descent (SymSGD) to estimator
  src/Microsoft.ML.HalLearners/SymSgdClassificationTrainer.cs
  test/Microsoft.ML.Tests/TrainerEstimators/SymSgdClassificationTests.cs
Labels: api

#1009 Adding the extension methods for FastTree classification and regression
  src/Microsoft.ML.Data/Training/TrainerUtils.cs
  src/Microsoft.ML.FastTree/FastTree.cs
  src/Microsoft.ML.FastTree/FastTreeArguments.cs
  src/Microsoft.ML.FastTree/FastTreeClassification.cs
  src/Microsoft.ML.FastTree/FastTreeRegression.cs
  src/Microsoft.ML.FastTree/FastTreeStatic.cs
  src/Microsoft.ML.FastTree/Microsoft.ML.FastTree.csproj
  src/Microsoft.ML.StandardLearners/FactorizationMachine/FactorizationMachineStatic.cs
  src/Microsoft.ML.StandardLearners/Standard/SdcaRegression.cs
  src/Microsoft.ML.StandardLearners/Standard/SdcaStatic.cs
  test/Microsoft.ML.StaticPipelineTesting/Microsoft.ML.StaticPipelineTesting.csproj
  test/Microsoft.ML.StaticPipelineTesting/Training.cs
  test/Microsoft.ML.Tests/Scenarios/Api/IntrospectiveTraining.cs
  test/Microsoft.ML.Tests/Scenarios/Api/TrainWithValidationSet.cs
  test/Microsoft.ML.Tests/ScenariosWithDirectInstantiation/SentimentPredictionTests.cs
  test/Microsoft.ML.Tests/TrainerEstimators/TreeEstimators.cs
Labels: api

#991 Converted Feature selection transforms in to transformers/estimators.
  src/Microsoft.ML.Transforms/CountFeatureSelection.cs
  src/Microsoft.ML.Transforms/MutualInformationFeatureSelection.cs
  src/Microsoft.ML.Transforms/WrappedFeatureSelectionTransformers.cs
  test/BaselineOutput/SingleDebug/FeatureSelection/featureselection.tsv
  test/BaselineOutput/SingleRelease/FeatureSelection/featureselection.tsv
  test/Microsoft.ML.StaticPipelineTesting/StaticPipeTests.cs
  test/Microsoft.ML.Tests/Transformers/FeatureSelectionTests.cs
Labels: api

#1020 LightGbm pigstensions
  src/Microsoft.ML.Data/Training/TrainerUtils.cs
  src/Microsoft.ML.LightGBM/LightGBMStatics.cs
  src/Microsoft.ML.LightGBM/LightGbmArguments.cs
  src/Microsoft.ML.LightGBM/LightGbmBinaryTrainer.cs
  src/Microsoft.ML.LightGBM/LightGbmRegressionTrainer.cs
  src/Microsoft.ML.LightGBM/LightGbmTrainerBase.cs
  test/Microsoft.ML.StaticPipelineTesting/Microsoft.ML.StaticPipelineTesting.csproj
  test/Microsoft.ML.StaticPipelineTesting/Training.cs
Labels: api

#1005 TrainTestSplit function
  src/Microsoft.ML.Data/DataLoadSave/CompositeDataReader.cs
  src/Microsoft.ML.Data/Training/TrainContext.cs
  src/Microsoft.ML.Data/Training/TrainingStaticExtensions.cs
  src/Microsoft.ML.StandardLearners/Standard/SdcaStatic.cs
  test/Microsoft.ML.StaticPipelineTesting/StaticPipeTests.cs
  test/Microsoft.ML.StaticPipelineTesting/Training.cs
Labels: api

#1014 Add Benchmark test for PredictionEngine
  test/Microsoft.ML.Benchmarks/Microsoft.ML.Benchmarks.csproj
  test/Microsoft.ML.Benchmarks/PredictionEngineBench.cs
Labels: perf

#1017 Converted PcaTransform into Transformer using TransformerWrapper.
  src/Microsoft.ML.PCA/PcaTransform.cs
  src/Microsoft.ML.PCA/WrappedPcaTransform.cs
  test/BaselineOutput/SingleDebug/PCA/pca.tsv
  test/BaselineOutput/SingleRelease/PCA/pca.tsv
  test/Microsoft.ML.StaticPipelineTesting/Microsoft.ML.StaticPipelineTesting.csproj
  test/Microsoft.ML.StaticPipelineTesting/StaticPipeTests.cs
  test/Microsoft.ML.Tests/Transformers/PcaTests.cs
Labels: api

#1074 Finish the sentence in TextLoader static pipeline extension method
  src/Microsoft.ML.Data/DataLoadSave/Text/TextLoaderStatic.cs
Labels: documentation

#979 Converting KMeans++trainer to estimator.
  src/Microsoft.ML.Core/Utilities/Contracts.cs
  src/Microsoft.ML.Data/Data/RowCursorUtils.cs
  src/Microsoft.ML.Data/Evaluators/ClusteringEvaluator.cs
  src/Microsoft.ML.Data/Evaluators/EvaluatorStaticExtensions.cs
  src/Microsoft.ML.Data/Evaluators/MulticlassClassifierEvaluator.cs
  src/Microsoft.ML.Data/Evaluators/RegressionEvaluator.cs
  src/Microsoft.ML.Data/Scorers/PredictionTransformer.cs
  src/Microsoft.ML.Data/StaticPipe/TrainerEstimatorReconciler.cs
  src/Microsoft.ML.Data/Training/TrainContext.cs
  src/Microsoft.ML.KMeansClustering/KMeansPlusPlusTrainer.cs
  src/Microsoft.ML.KMeansClustering/KMeansStatic.cs
  test/Microsoft.ML.Benchmarks/KMeansAndLogisticRegressionBench.cs
  test/Microsoft.ML.StaticPipelineTesting/Training.cs
  test/Microsoft.ML.TestFramework/Datasets.cs
  test/Microsoft.ML.Tests/TrainerEstimators/TrainerEstimators.cs
Labels: api

#1084 More pigstensions
  src/Microsoft.ML.Ensemble/Trainer/Regression/RegressionEnsembleTrainer.cs
  src/Microsoft.ML.KMeansClustering/KMeansStatic.cs
  src/Microsoft.ML.StandardLearners/Standard/LinearClassificationTrainer.cs
  src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/LbfgsPredictorBase.cs
  src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/LbfgsStatics.cs
  src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/LogisticRegression.cs
  src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/MulticlassLogisticRegression.cs
  src/Microsoft.ML.StandardLearners/Standard/Online/AveragedLinear.cs
  src/Microsoft.ML.StandardLearners/Standard/Online/AveragedPerceptron.cs
  src/Microsoft.ML.StandardLearners/Standard/Online/LinearSvm.cs
  src/Microsoft.ML.StandardLearners/Standard/Online/OnlineGradientDescent.cs
  src/Microsoft.ML.StandardLearners/Standard/Online/OnlineLearnerStatic.cs
  src/Microsoft.ML.StandardLearners/Standard/Online/OnlineLinear.cs
  src/Microsoft.ML.StandardLearners/Standard/PoissonRegression/PoissonRegression.cs
  src/Microsoft.ML.StandardLearners/Standard/SdcaStatic.cs
  test/Microsoft.ML.StaticPipelineTesting/Training.cs
  test/Microsoft.ML.Tests/TrainerEstimators/LbfgsTests.cs
  test/Microsoft.ML.Tests/TrainerEstimators/OnlineLinearTests.cs
Labels: api

#1088 Added training method that accepts initial predictor for Symboli SGD estimator
  src/Microsoft.ML.HalLearners/SymSgdClassificationTrainer.cs
  test/Microsoft.ML.Tests/TrainerEstimators/SymSgdClassificationTests.cs
Labels: api

#960 API overview and samples
  docs/code/MlNetCookBook.md
  docs/code/MlNetHighLevelConcepts.md
  src/Microsoft.ML.Transforms/Text/TextStaticExtensions.cs
  test/Microsoft.ML.Tests/Scenarios/Api/CookbookSamples/CookbookSamples.cs
Labels: api

#1068 Ranker train context and FastTree ranking xtensions
  docs/images/DCG.png
  docs/images/NDCG.png
  src/Microsoft.ML.Data/Evaluators/EvaluatorStaticExtensions.cs
  src/Microsoft.ML.Data/Evaluators/RankerEvaluator.cs
  src/Microsoft.ML.Data/StaticPipe/TrainerEstimatorReconciler.cs
  src/Microsoft.ML.Data/Training/TrainContext.cs
  src/Microsoft.ML.FastTree/FastTreeStatic.cs
  src/Microsoft.ML.LightGBM/LightGBMStatics.cs
  src/Microsoft.ML.StandardLearners/FactorizationMachine/FactorizationMachineStatic.cs
  src/Microsoft.ML.StandardLearners/Standard/SdcaStatic.cs
  test/Microsoft.ML.StaticPipelineTesting/Training.cs
  test/Microsoft.ML.Tests/Scenarios/Api/CookbookSamples/CookbookSamples.cs
Labels: api
