Repository dotnet/machinelearning, pull requests merged in 2019-05, with the labels that each got.

#3633 [AutoML] use Name instead of FullName for telemetry filename hash
  src/mlnet/Commands/New/NewCommandHandler.cs
Labels: AutoML

#3634 [AutoML] Rename classes in generated project.
  src/mlnet/CodeGenerator/CSharp/CodeGenerator.cs
  src/mlnet/Templates/Console/ModelBuilder.cs
  src/mlnet/Templates/Console/ModelBuilder.tt
  src/mlnet/Templates/Console/ModelInputClass.cs
  src/mlnet/Templates/Console/ModelInputClass.tt
  src/mlnet/Templates/Console/ModelOutputClass.cs
  src/mlnet/Templates/Console/ModelOutputClass.tt
  src/mlnet/Templates/Console/PredictProgram.cs
  src/mlnet/Templates/Console/PredictProgram.tt
  src/mlnet/mlnet.csproj
  test/mlnet.Tests/ApprovalTests/ConsoleCodeGeneratorTests.ConsoleAppModelBuilderCSFileContentBinaryTest.approved.txt
  test/mlnet.Tests/ApprovalTests/ConsoleCodeGeneratorTests.ConsoleAppModelBuilderCSFileContentOvaTest.approved.txt
  test/mlnet.Tests/ApprovalTests/ConsoleCodeGeneratorTests.ConsoleAppModelBuilderCSFileContentRegressionTest.approved.txt
  test/mlnet.Tests/ApprovalTests/ConsoleCodeGeneratorTests.ConsoleAppProgramCSFileContentTest.approved.txt
  test/mlnet.Tests/ApprovalTests/ConsoleCodeGeneratorTests.ObservationCSFileContentTest.approved.txt
  test/mlnet.Tests/ApprovalTests/ConsoleCodeGeneratorTests.PredictionCSFileContentTest.approved.txt
  test/mlnet.Tests/ApprovalTests/ConsoleCodeGeneratorTests.cs
Labels: AutoML

#3639 [AutoML] undo pinning ML.NET dependency
  src/Microsoft.ML.AutoML/Microsoft.ML.AutoML.csproj
  src/mlnet/mlnet.csproj
Labels: AutoML

#3640 [AutoML] set exploration time default in CLI to half hour
  src/mlnet/Commands/CommandDefinitions.cs
Labels: AutoML

#3642 [AutoML] step 2 of removing pinned nupkg versions
  pkg/Microsoft.ML.AutoML/Microsoft.ML.AutoML.nupkgproj
  pkg/mlnet/mlnet.nupkgproj
  src/Microsoft.ML.AutoML/Microsoft.ML.AutoML.csproj
Labels: AutoML

#3643 [AutoML] InferColumns API that consumes label column index -- only rename label column to 'Label' for headerless files
  src/Microsoft.ML.AutoML/ColumnInference/ColumnInferenceApi.cs
Labels: AutoML

#3644 [AutoML] Upgrade ml.net package in generated code
  src/mlnet/Templates/Console/ModelProject.cs
  src/mlnet/Templates/Console/ModelProject.tt
  src/mlnet/Templates/Console/PredictProject.cs
  src/mlnet/Templates/Console/PredictProject.tt
  test/mlnet.Tests/ApprovalTests/ConsoleCodeGeneratorTests.ConsoleAppProjectFileContentTest.approved.txt
  test/mlnet.Tests/ApprovalTests/ConsoleCodeGeneratorTests.ModelProjectFileContentTest.approved.txt
Labels: AutoML

#3641 [AutoML] Early stopping in CLI based on the exploration time
  src/Microsoft.ML.AutoML/Utils/BestResultUtil.cs
  src/mlnet/AutoML/AutoMLEngine.cs
  src/mlnet/AutoML/IAutoMLEngine.cs
  src/mlnet/CodeGenerator/CodeGenerationHelper.cs
  src/mlnet/Program.cs
  src/mlnet/Strings.resx
  src/mlnet/Utilities/ProgressHandlers.cs
  src/mlnet/strings.Designer.cs
Labels: AutoML

#3655 [AutoML] Change wording for CouldNotFinshOnTime message
  src/mlnet/Strings.resx
  src/mlnet/strings.Designer.cs
Labels: AutoML

#3656 [AutoML] temp change to get around vsts publish failure
  build.proj
Labels: AutoML

#3658 [AutoML] bump version to 0.4.0
  build/BranchInfo.props
Labels: AutoML

#3623 API Compat tool in ML.NET
  Microsoft.ML.sln
  build/Dependencies.props
  src/Directory.Build.props
  src/Directory.Build.targets
  tools-local/Microsoft.ML.StableApi/Microsoft.ML.StableApi.csproj
Labels: Build

#2693 Draft version of ML.NET CLI specs with AutoML capabilities
  docs/specs/mlnet-cli/Images/MLNET-AutoML-Positioning.png
  docs/specs/mlnet-cli/Images/MLNET-AutoML-Working-Diagram.png
  docs/specs/mlnet-cli/Images/Plan-Scope.png
  docs/specs/mlnet-cli/Images/results-1.png
  docs/specs/mlnet-cli/Images/results-2.png
  docs/specs/mlnet-cli/MLNET-CLI-Specs.md
Labels: command-line, documentation, enhancement

#3667 Fix to the official build (API Compat tool)
  src/Directory.Build.props
Labels: Build

#3725 [AutoML] Fix Internationalization bug in generated project.
  src/mlnet/CodeGenerator/CSharp/TrainerGeneratorBase.cs
  test/mlnet.Tests/TrainerGeneratorTests.cs
Labels: AutoML

#3730 [AutoML] Reset the culture info back to its original value in the test case.
  test/mlnet.Tests/TrainerGeneratorTests.cs
Labels: AutoML

#3263 Add DataView Type Register (supporting loading in-memory image and other in-memory custom types)
  docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/CustomMappingWithInMemoryCustomType.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/ImageAnalytics/ConvertToGrayScaleInMemory.cs
  src/Microsoft.ML.Data/Data/DataViewTypeManager.cs
  src/Microsoft.ML.Data/Data/SchemaDefinition.cs
  src/Microsoft.ML.Data/DataView/DataViewConstructionUtils.cs
  src/Microsoft.ML.Data/DataView/InternalSchemaDefinition.cs
  src/Microsoft.ML.Data/DataView/TypedCursor.cs
  src/Microsoft.ML.Data/Utils/ApiUtils.cs
  src/Microsoft.ML.DataView/DataViewType.cs
  src/Microsoft.ML.ImageAnalytics/ExtensionsCatalog.cs
  src/Microsoft.ML.ImageAnalytics/ImageType.cs
  src/Microsoft.ML.Transforms/CustomMappingCatalog.cs
  test/Microsoft.ML.Core.Tests/UnitTests/TestCustomTypeRegister.cs
  test/Microsoft.ML.Tests/ImagesTests.cs
Labels: bug

#3741 Added omp requirement to build on Linux on README
  docs/building/unix-instructions.md
Labels: Build, documentation
