Repository dotnet/machinelearning, pull requests merged in 2019-04, with the labels that each got.

#3136 Update VBuffer documentation
  docs/code/VBufferCareFeeding.md
  src/Microsoft.ML.DataView/VBuffer.cs
  src/Microsoft.ML.DataView/VBufferEditor.cs
Labels: Shiproom-approve, documentation

#3118 Move Normalizer extension method from experimental to stable nuget and remove Normalizer generic APIs
  docs/code/MlNetCookBook.md
  docs/samples/Microsoft.ML.Samples/Dynamic/Normalizer.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/PermutationFeatureImportance/PFIRegressionExample.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/PermutationFeatureImportance/PfiBinaryClassificationExample.cs
  src/Microsoft.ML.Data/Transforms/Normalizer.cs
  src/Microsoft.ML.Experimental/TransformsCatalogExtensions.cs
  src/Microsoft.ML.SamplesUtils/SamplesDatasetUtils.cs
  src/Microsoft.ML.Transforms/NormalizerCatalog.cs
  test/Microsoft.ML.Benchmarks/KMeansAndLogisticRegressionBench.cs
  test/Microsoft.ML.Benchmarks/Microsoft.ML.Benchmarks.csproj
  test/Microsoft.ML.Functional.Tests/DataTransformation.cs
  test/Microsoft.ML.Functional.Tests/IntrospectiveTraining.cs
  test/Microsoft.ML.Functional.Tests/ModelFiles.cs
  test/Microsoft.ML.Functional.Tests/ONNX.cs
  test/Microsoft.ML.Functional.Tests/Training.cs
  test/Microsoft.ML.Tests/CachingTests.cs
  test/Microsoft.ML.Tests/FeatureContributionTests.cs
  test/Microsoft.ML.Tests/OnnxConversionTest.cs
  test/Microsoft.ML.Tests/PermutationFeatureImportanceTests.cs
  test/Microsoft.ML.Tests/Scenarios/Api/CookbookSamples/CookbookSamples.cs
  test/Microsoft.ML.Tests/Scenarios/Api/CookbookSamples/CookbookSamplesDynamicApi.cs
  test/Microsoft.ML.Tests/Scenarios/IrisPlantClassificationTests.cs
  test/Microsoft.ML.Tests/Scenarios/IrisPlantClassificationWithStringLabelTests.cs
  test/Microsoft.ML.Tests/ScenariosWithDirectInstantiation/IrisPlantClassificationTests.cs
  test/Microsoft.ML.Tests/Transformers/NormalizerTests.cs
Labels: Shiproom-review

#3167 Conversion catalog samples
  docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/Conversion/ConvertType.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/Conversion/ConvertTypeMultiColumn.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/Conversion/KeyToValueToKey.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/Conversion/MapValue.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/Conversion/MapValueIdvLookup.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/Conversion/MapValueToArray.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/ValueMapping.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/ValueMappingFloatToString.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/ValueMappingStringToArray.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/ValueMappingStringToKeyType.cs
  src/Microsoft.ML.Data/Transforms/ConversionsExtensionsCatalog.cs
Labels: documentation

#3194 Key type documentation.
  docs/code/KeyValues.md
  src/Microsoft.ML.DataView/KeyDataViewType.cs
Labels: code-sanitation, documentation

#3180 Fix a value-mapping bug
  src/Microsoft.ML.Data/Transforms/ConversionsExtensionsCatalog.cs
  src/Microsoft.ML.Data/Transforms/ValueMapping.cs
  test/Microsoft.ML.Tests/Transformers/ValueMappingTests.cs
Labels: bug

#3217 Add loadable attribute for LinearMulticlassModelParameters
  src/Microsoft.ML.StandardTrainers/Standard/LogisticRegression/MulticlassLogisticRegression.cs
  test/Microsoft.ML.Tests/TrainerEstimators/SdcaTests.cs
Labels: Shiproom-review

#3187 Multi column MapKeyToValue and MapValueToKey
  docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/MulticlassClassification/StochasticDualCoordinateAscent.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/Conversion/ConvertType.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/Conversion/ConvertTypeMultiColumn.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/Conversion/Hash.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/Conversion/KeyToValueToKey.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/Conversion/MapKeyToValueMultiColumn.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/Conversion/MapValue.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/Conversion/MapValueIdvLookup.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/Conversion/MapValueToArray.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/Conversion/MapValueToKeyMultiColumn.cs
  src/Microsoft.ML.Data/Transforms/ConversionsExtensionsCatalog.cs
Labels: documentation

#3227 Polish marshalling of MF model and MF problem and enable 32-bit tests
  src/Microsoft.ML.Recommender/SafeTrainingAndModelBuffer.cs
  src/Native/MatrixFactorizationNative/UnmanagedMemory.cpp
  src/Native/MatrixFactorizationNative/UnmanagedMemory.h
  test/Microsoft.ML.TestFramework/Attributes/MatrixFactorizationFactAttribute.cs
Labels: bug

#3211 Key to binary samples for documentation
  docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/Conversion/MapKeyToBinaryVector.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/Conversion/MapKeyToVector.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/Conversion/MapKeyToVectorMultiColumn.cs
  src/Microsoft.ML.Data/Data/SchemaDefinition.cs
  src/Microsoft.ML.Data/Transforms/ConversionsExtensionsCatalog.cs
  src/Microsoft.ML.Transforms/ConversionsCatalog.cs
Labels: documentation

#3216 Samples for CustomMapping, IndicateMissingValues, ReplaceMissingValues
  docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/CustomMapping.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/CustomMappingSample.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/CustomMappingSaveAndLoad.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/IndicateMissingValues.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/IndicateMissingValuesMultiColumn.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/ReplaceMissingValues.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/ReplaceMissingValuesMultiColumn.cs
  docs/samples/Microsoft.ML.Samples/Microsoft.ML.Samples.csproj
  src/Microsoft.ML.Transforms/CustomMappingCatalog.cs
  src/Microsoft.ML.Transforms/ExtensionsCatalog.cs
Labels: documentation

#3124 Add doc string to explain matrix-vector product's SSE code and a test
  src/Microsoft.ML.CpuMath/CpuMathUtils.netstandard.cs
  src/Microsoft.ML.CpuMath/Properties/AssemblyInfo.cs
  test/Microsoft.ML.Tests/Microsoft.ML.Tests.csproj
  test/Microsoft.ML.Tests/TrainerEstimators/MatrixFactorizationTests.cs
Labels: documentation

#3302 Simple IDataView implementation sample.
  docs/samples/Microsoft.ML.Samples/Dynamic/SimpleDataViewImplementation.cs
  docs/samples/Microsoft.ML.Samples/Microsoft.ML.Samples.csproj
  src/Microsoft.ML.DataView/IDataView.cs
Labels: documentation

#3331 [AutoML] disable netfx build leg for now
  .vsts-dotnet-ci.yml
Labels: AutoML

#3252 Renamed WhatTheFeature and their abbreviations to FeatureContributionScorer.
  src/Microsoft.ML.Data/Scorers/FeatureContributionCalculation.cs
Labels: Shiproom-review

#3195 Update DataViewRow and DataViewRowCursor implementation documentation.
  src/Microsoft.ML.DataView/DataViewRowCursor.md
  src/Microsoft.ML.DataView/ICursor.md
Labels: code-sanitation, documentation

#3351 [AutoML] Add AutoML XML documentation to all public members; migrate AutoML projects & tests into ML.NET solution; AutoML test fixes
  Microsoft.ML.AutoML.sln
  Microsoft.ML.sln
  build.proj
  docs/samples/Microsoft.ML.Samples/AutoML/BinaryClassificationExperiment.cs
  docs/samples/Microsoft.ML.Samples/AutoML/BinaryClassificationExperimentWithExperimentSettings.cs
  docs/samples/Microsoft.ML.Samples/AutoML/MulticlassClassificationExperiment.cs
  docs/samples/Microsoft.ML.Samples/AutoML/MulticlassClassificationExperimentWithExperimentSettings.cs
  docs/samples/Microsoft.ML.Samples/AutoML/RegressionExperiment.cs
  docs/samples/Microsoft.ML.Samples/AutoML/RegressionExperimentWithExperimentSettings.cs
  docs/samples/Microsoft.ML.Samples/Microsoft.ML.Samples.csproj
  src/Microsoft.ML.Auto/API/AutoCatalog.cs
  src/Microsoft.ML.Auto/API/AutoInferenceCatalog.cs
  src/Microsoft.ML.Auto/API/BinaryClassificationExperiment.cs
  src/Microsoft.ML.Auto/API/ColumnInference.cs
  src/Microsoft.ML.Auto/API/ExperimentBase.cs
  src/Microsoft.ML.Auto/API/ExperimentSettings.cs
  src/Microsoft.ML.Auto/API/InferenceException.cs
  src/Microsoft.ML.Auto/API/MLContextExtension.cs
  src/Microsoft.ML.Auto/API/MulticlassClassificationExperiment.cs
  src/Microsoft.ML.Auto/API/RegressionExperiment.cs
  src/Microsoft.ML.Auto/API/RunDetails/CrossValidationRunDetail.cs
  src/Microsoft.ML.Auto/API/RunDetails/RunDetail.cs
  src/Microsoft.ML.Auto/ColumnInference/ColumnInferenceApi.cs
  src/Microsoft.ML.Auto/Microsoft.ML.Auto.csproj
  src/Microsoft.ML.Auto/Sweepers/SmacSweeper.cs
  src/Microsoft.ML.Auto/TrainerExtensions/SweepableParams.cs
  src/Microsoft.ML.Auto/TrainerExtensions/TrainerExtensionUtil.cs
  src/mlnet/CodeGenerator/CSharp/TrainerGenerators.cs
  src/mlnet/mlnet.csproj
  test/Microsoft.ML.AutoML.Tests/Microsoft.ML.AutoML.Tests.csproj
Labels: AutoML

#3364 [AutoML] Rev AutoML public API; add required native references to AutoML projects
  src/Microsoft.ML.Auto/API/BinaryClassificationExperiment.cs
  src/Microsoft.ML.Auto/API/ColumnInference.cs
  src/Microsoft.ML.Auto/API/ExperimentBase.cs
  src/Microsoft.ML.Auto/API/ExperimentResults/CrossValidationExperimentResult.cs
  src/Microsoft.ML.Auto/API/ExperimentResults/ExperimentResult.cs
  src/Microsoft.ML.Auto/API/ExperimentSettings.cs
  src/Microsoft.ML.Auto/API/MulticlassClassificationExperiment.cs
  src/Microsoft.ML.Auto/API/RegressionExperiment.cs
  src/Microsoft.ML.Auto/API/RunDetails/RunDetail.cs
  src/Microsoft.ML.Auto/DebugLogger.cs
  src/Microsoft.ML.Auto/Experiment/Experiment.cs
  src/Microsoft.ML.Auto/Experiment/Runners/CrossValRunner.cs
  src/Microsoft.ML.Auto/Experiment/Runners/CrossValSummaryRunner.cs
  src/Microsoft.ML.Auto/Experiment/Runners/RunnerUtil.cs
  src/Microsoft.ML.Auto/Experiment/Runners/TrainValidateRunner.cs
  src/Microsoft.ML.Auto/Experiment/SuggestedPipelineBuilder.cs
  src/Microsoft.ML.Auto/Microsoft.ML.Auto.csproj
  src/Microsoft.ML.Auto/PipelineSuggesters/PipelineSuggester.cs
  src/Microsoft.ML.Auto/Utils/Logger.cs
  src/mlnet/AutoML/AutoMLDebugLogger.cs
  src/mlnet/AutoML/AutoMLEngine.cs
  src/mlnet/AutoML/IAutoMLEngine.cs
  src/mlnet/CodeGenerator/CodeGenerationHelper.cs
  src/mlnet/Utilities/Utils.cs
  src/mlnet/mlnet.csproj
  test/Microsoft.ML.AutoML.Tests/AutoFitTests.cs
  test/Microsoft.ML.AutoML.Tests/Microsoft.ML.AutoML.Tests.csproj
  test/Microsoft.ML.AutoML.Tests/SuggestedPipelineBuilderTests.cs
Labels: AutoML

#3371 [AutoML] Minor changes to generated project in CLI based on feedback
  src/mlnet/CodeGenerator/CSharp/CodeGenerator.cs
  src/mlnet/Templates/Console/ModelBuilder.cs
  src/mlnet/Templates/Console/ModelBuilder.tt
  src/mlnet/Templates/Console/ModelProject.cs
  src/mlnet/Templates/Console/ModelProject.tt
  src/mlnet/Templates/Console/PredictProgram.cs
  src/mlnet/Templates/Console/PredictProgram.tt
  src/mlnet/Utilities/ProgressHandlers.cs
  test/mlnet.Tests/ApprovalTests/ConsoleCodeGeneratorTests.ConsoleAppModelBuilderCSFileContentBinaryTest.approved.txt
  test/mlnet.Tests/ApprovalTests/ConsoleCodeGeneratorTests.ConsoleAppModelBuilderCSFileContentOvaTest.approved.txt
  test/mlnet.Tests/ApprovalTests/ConsoleCodeGeneratorTests.ConsoleAppModelBuilderCSFileContentRegressionTest.approved.txt
  test/mlnet.Tests/ApprovalTests/ConsoleCodeGeneratorTests.ConsoleAppProgramCSFileContentTest.approved.txt
  test/mlnet.Tests/ApprovalTests/ConsoleCodeGeneratorTests.ModelProjectFileContentTest.approved.txt
  test/mlnet.Tests/ApprovalTests/ConsoleCodeGeneratorTests.cs
Labels: AutoML

#3373 [AutoML] Migrate AutoML back to its own solution, w/ NuGet dependencies
  Microsoft.ML.AutoML.sln
  Microsoft.ML.sln
  build.proj
  docs/samples/Microsoft.ML.Samples/AutoML/BinaryClassificationExperiment.cs
  docs/samples/Microsoft.ML.Samples/AutoML/BinaryClassificationExperimentWithExperimentSettings.cs
  docs/samples/Microsoft.ML.Samples/AutoML/MulticlassClassificationExperiment.cs
  docs/samples/Microsoft.ML.Samples/AutoML/MulticlassClassificationExperimentWithExperimentSettings.cs
  docs/samples/Microsoft.ML.Samples/AutoML/RegressionExperiment.cs
  docs/samples/Microsoft.ML.Samples/AutoML/RegressionExperimentWithExperimentSettings.cs
  docs/samples/Microsoft.ML.Samples/Microsoft.ML.Samples.csproj
  src/Microsoft.ML.Auto/API/AutoCatalog.cs
  src/Microsoft.ML.Auto/AutoMlUtils.cs
  src/Microsoft.ML.Auto/Microsoft.ML.Auto.csproj
  src/Microsoft.ML.Auto/TrainerExtensions/SweepableParams.cs
  src/mlnet/CodeGenerator/CSharp/TrainerGenerators.cs
  src/mlnet/mlnet.csproj
  test/Microsoft.ML.AutoML.Tests/Microsoft.ML.AutoML.Tests.csproj
  test/mlnet.Tests/mlnet.Tests.csproj
Labels: AutoML

#3383 [AutoML] publish AutoML package
  build.proj
  build/BranchInfo.props
  pkg/Microsoft.ML.Auto/Microsoft.ML.Auto.nupkgproj
  pkg/Microsoft.ML.Auto/Microsoft.ML.Auto.symbols.nupkgproj
  src/Microsoft.ML.Auto/Microsoft.ML.Auto.csproj
  src/mlnet/mlnet.csproj
  test/Microsoft.ML.AutoML.Tests/Microsoft.ML.AutoML.Tests.csproj
  test/run-tests.proj
Labels: AutoML

#3406 fixing the link format in ColumnCopying
  src/Microsoft.ML.Data/Transforms/ColumnCopying.cs
Labels: documentation

#3416 [AutoML] bump version to 0.3 since that's the one we're going to ship for build
  build/BranchInfo.props
Labels: AutoML

#3420 [AutoML] temporarily disable all but x64 platforms
  build/vsts-ci.yml
Labels: AutoML

#3423 [AutoML] fix vsts build
  build/vsts-ci.yml
Labels: AutoML

#3435 Normalizer multicolumn example
  docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/NormalizeBinning.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/NormalizeBinningMulticolumn.cs
  src/Microsoft.ML.Transforms/NormalizerCatalog.cs
Labels: documentation

#3370 Increase Native build warning level to W3 and fix build warnings
  src/Native/CMakeLists.txt
  src/Native/CpuMathNative/Sse.cpp
  src/Native/LdaNative/alias_multinomial_rng_int.cpp
  src/Native/LdaNative/alias_multinomial_rng_int.hpp
  src/Native/LdaNative/data_block.cpp
  src/Native/LdaNative/data_block.h
  src/Native/LdaNative/lda_engine.cpp
  src/Native/LdaNative/model_block.cpp
  src/Native/LdaNative/model_block.h
  src/Native/MatrixFactorizationNative/UnmanagedMemory.cpp
Labels: Shiproom-review

#3419 Update xml documentation for ProduceHashedNgrams
  src/Microsoft.ML.Transforms/Text/NgramHashingTransformer.cs
  src/Microsoft.ML.Transforms/Text/TextCatalog.cs
Labels: documentation

#3418 XML documentation for five text related transforms
  src/Microsoft.ML.Transforms/Text/NgramTransform.cs
  src/Microsoft.ML.Transforms/Text/NgramUtils.cs
  src/Microsoft.ML.Transforms/Text/TextCatalog.cs
  src/Microsoft.ML.Transforms/Text/TextNormalizing.cs
  src/Microsoft.ML.Transforms/Text/TokenizingByCharacters.cs
  src/Microsoft.ML.Transforms/Text/WordEmbeddingsExtractor.cs
  src/Microsoft.ML.Transforms/Text/WordTokenizing.cs
Labels: documentation

#3428 XML documentation for transforms
  src/Microsoft.ML.Data/Transforms/ColumnConcatenatingEstimator.cs
  src/Microsoft.ML.Data/Transforms/ColumnConcatenatingTransformer.cs
  src/Microsoft.ML.Data/Transforms/ColumnSelecting.cs
  src/Microsoft.ML.Data/Transforms/ExtensionsCatalog.cs
  src/Microsoft.ML.Transforms/CustomMappingCatalog.cs
  src/Microsoft.ML.Transforms/CustomMappingTransformer.cs
Labels: documentation

#3384 Towards #3204 - documentation for FeatureContributionCalculatingEstimator
  src/Microsoft.ML.Data/Transforms/ExplainabilityCatalog.cs
  src/Microsoft.ML.Data/Transforms/FeatureContributionCalculationTransformer.cs
Labels: documentation

#3401 Towards #2522 - LinearSvmTrainer documentation
  src/Microsoft.ML.StandardTrainers/Standard/Online/LinearSvm.cs
  src/Microsoft.ML.StandardTrainers/StandardTrainersCatalog.cs
Labels: documentation

#3432 XML documentation for Normalizer
  src/Microsoft.ML.Data/Transforms/Normalizer.cs
  src/Microsoft.ML.Transforms/NormalizerCatalog.cs
Labels: documentation

#3409 Matrix Factorization XML docs
  src/Microsoft.ML.Recommender/MatrixFactorizationTrainer.cs
  src/Microsoft.ML.Recommender/RecommenderCatalog.cs
Labels: documentation

#3413 Stopwords remover xml documentation
  src/Microsoft.ML.Transforms/Text/StopWordsRemovingTransformer.cs
  src/Microsoft.ML.Transforms/Text/TextCatalog.cs
Labels: documentation

#3389 Add XML to LBFGS Maximum Entropy Classifier
  docs/api-reference/io-columns-multiclass-classification.md
  src/Microsoft.ML.StandardTrainers/Standard/LogisticRegression/MulticlassLogisticRegression.cs
  src/Microsoft.ML.StandardTrainers/StandardTrainersCatalog.cs
Labels: documentation

#3374 FFM XML Doc And Add One Missing Sample File
  docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/BinaryClassification/FactorizationMachine.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/BinaryClassification/FactorizationMachine.tt
  docs/samples/Microsoft.ML.Samples/Microsoft.ML.Samples.csproj
  src/Microsoft.ML.StandardTrainers/FactorizationMachine/FactorizationMachineCatalog.cs
  src/Microsoft.ML.StandardTrainers/FactorizationMachine/FactorizationMachineTrainer.cs
Labels: documentation

#3385 Add LR XML doc
  src/Microsoft.ML.StandardTrainers/Standard/LogisticRegression/LogisticRegression.cs
  src/Microsoft.ML.StandardTrainers/StandardTrainersCatalog.cs
Labels: documentation

#3433 Documentation for Multiclass SDCA
  src/Microsoft.ML.StandardTrainers/Standard/SdcaMulticlass.cs
  src/Microsoft.ML.StandardTrainers/StandardTrainersCatalog.cs
Labels: documentation

#3440 Update documentation for WordBag
  src/Microsoft.ML.Transforms/Text/NgramHashingTransformer.cs
  src/Microsoft.ML.Transforms/Text/TextCatalog.cs
  src/Microsoft.ML.Transforms/Text/WrappedTextTransformers.cs
Labels: documentation

#3386 Update documentation for MissingValues
  src/Microsoft.ML.Transforms/ExtensionsCatalog.cs
  src/Microsoft.ML.Transforms/MissingValueIndicatorTransformer.cs
  src/Microsoft.ML.Transforms/MissingValueReplacing.cs
  src/Microsoft.ML.Transforms/doc.xml
Labels: documentation

#3417 Towards #3204 - XML Documentation for MLContext.Data transforms
  src/Microsoft.ML.Data/DataLoadSave/DataOperationsCatalog.cs
  src/Microsoft.ML.DataView/DataViewSchema.cs
Labels: documentation

#3387 Docs 2nd pass for NaiveBayes, KMeans, OVA, Pairwise and OnnxTransformer
  docs/api-reference/io-columns-clustering.md
  src/Microsoft.ML.KMeansClustering/KMeansPlusPlusTrainer.cs
  src/Microsoft.ML.KMeansClustering/doc.xml
  src/Microsoft.ML.OnnxTransformer/OnnxCatalog.cs
  src/Microsoft.ML.OnnxTransformer/OnnxTransform.cs
  src/Microsoft.ML.StandardTrainers/Standard/MulticlassClassification/MulticlassNaiveBayesTrainer.cs
  src/Microsoft.ML.StandardTrainers/Standard/MulticlassClassification/OneVersusAllTrainer.cs
  src/Microsoft.ML.StandardTrainers/Standard/MulticlassClassification/PairwiseCouplingTrainer.cs
  src/Microsoft.ML.StandardTrainers/Standard/MulticlassClassification/doc.xml
Labels: documentation

#3444 XML documentation for Time Series
  docs/api-reference/io-time-series-change-point.md
  docs/api-reference/io-time-series-spike.md
  docs/api-reference/time-series-iid.md
  docs/api-reference/time-series-props.md
  docs/api-reference/time-series-scorer.md
  docs/api-reference/time-series-ssa.md
  src/Microsoft.ML.TimeSeries/ExtensionsCatalog.cs
  src/Microsoft.ML.TimeSeries/IidAnomalyDetectionBase.cs
  src/Microsoft.ML.TimeSeries/IidChangePointDetector.cs
  src/Microsoft.ML.TimeSeries/IidSpikeDetector.cs
  src/Microsoft.ML.TimeSeries/SsaAnomalyDetectionBase.cs
  src/Microsoft.ML.TimeSeries/SsaChangePointDetector.cs
  src/Microsoft.ML.TimeSeries/SsaSpikeDetector.cs
Labels: documentation

#3448 Changing the format of the formula to LaTeX
  src/Microsoft.ML.Transforms/MutualInformationFeatureSelection.cs
Labels: documentation

#3442 Lda snapping to template
  src/Microsoft.ML.Data/Transforms/ConversionsExtensionsCatalog.cs
  src/Microsoft.ML.Data/Transforms/ValueToKeyMappingEstimator.cs
  src/Microsoft.ML.Transforms/Text/LdaTransform.cs
  src/Microsoft.ML.Transforms/Text/TextCatalog.cs
  src/Microsoft.ML.Transforms/Text/doc.xml
Labels: documentation

#3438 snapping featurizeText to the template
  src/Microsoft.ML.Transforms/Text/TextCatalog.cs
  src/Microsoft.ML.Transforms/Text/TextFeaturizingEstimator.cs
  src/Microsoft.ML.Transforms/Text/doc.xml
Labels: documentation

#3429 XML documentation for Randomized PCA trainer.
  docs/api-reference/io-columns-anomaly-detection.md
  docs/api-reference/io-columns-binary-classification.md
  src/Microsoft.ML.PCA/PCACatalog.cs
  src/Microsoft.ML.PCA/PcaTrainer.cs
Labels: documentation

#3376 Update xml documentation for Image estimators
  src/Microsoft.ML.ImageAnalytics/ExtensionsCatalog.cs
  src/Microsoft.ML.ImageAnalytics/ImageGrayscale.cs
  src/Microsoft.ML.ImageAnalytics/ImageLoader.cs
  src/Microsoft.ML.ImageAnalytics/ImagePixelExtractor.cs
  src/Microsoft.ML.ImageAnalytics/ImageResizer.cs
  src/Microsoft.ML.ImageAnalytics/VectorToImageTransform.cs
  src/Microsoft.ML.ImageAnalytics/doc.xml
Labels: documentation

#3388 Towards #3204 - Documentation for MLContext.Transforms.Categorical
  src/Microsoft.ML.Data/Transforms/ColumnCopying.cs
  src/Microsoft.ML.Data/Transforms/ConversionsExtensionsCatalog.cs
  src/Microsoft.ML.Data/Transforms/Hashing.cs
  src/Microsoft.ML.Data/Transforms/ValueToKeyMappingEstimator.cs
  src/Microsoft.ML.Transforms/CategoricalCatalog.cs
  src/Microsoft.ML.Transforms/OneHotEncoding.cs
  src/Microsoft.ML.Transforms/OneHotHashEncoding.cs
  src/Microsoft.ML.Transforms/doc.xml
Labels: documentation

#3452 Delete xml doc files.
  src/Microsoft.ML.FastTree/doc.xml
  src/Microsoft.ML.LightGbm/doc.xml
  src/Microsoft.ML.StandardTrainers/Standard/LogisticRegression/doc.xml
  src/Microsoft.ML.StandardTrainers/Standard/doc.xml
Labels: documentation

#3453 Replace documentation with link
  src/Microsoft.ML.StandardTrainers/Standard/SdcaBinary.cs
  src/Microsoft.ML.StandardTrainers/StandardTrainersCatalog.cs
Labels: documentation

#3454 XML doc for LpNormalizingEstimator and GlobalContrastNormalizingEstimator
  src/Microsoft.ML.Transforms/GcnTransform.cs
  src/Microsoft.ML.Transforms/NormalizerCatalog.cs
Labels: documentation

#3455 XML docs for Permutation feature importance for Binary, Multi-class and Ranking trainers.
  docs/api-reference/io-columns-multiclass-classification.md
  docs/api-reference/io-columns-ranking.md
  src/Microsoft.ML.FastTree/TreeTrainersCatalog.cs
  src/Microsoft.ML.LightGbm/LightGbmCatalog.cs
  src/Microsoft.ML.Transforms/PermutationFeatureImportanceExtensions.cs
Labels: documentation

#3456 XML documentation for DNN Image Featurizer Transfomer.
  src/Microsoft.ML.OnnxTransformer/DnnImageFeaturizerTransform.cs
  src/Microsoft.ML.OnnxTransformer/OnnxCatalog.cs
Labels: documentation

#3484 [AutoML] API docs for automl experiment
  src/Microsoft.ML.Auto/API/AutoCatalog.cs
Labels: AutoML

#3504 [AUTOML] fixed path bug and regression metrics correction
  src/mlnet/Templates/Console/ModelBuilder.cs
  src/mlnet/Templates/Console/ModelBuilder.tt
  src/mlnet/Templates/Console/PredictProgram.cs
  src/mlnet/Templates/Console/PredictProgram.tt
  test/mlnet.Tests/ApprovalTests/ConsoleCodeGeneratorTests.ConsoleAppModelBuilderCSFileContentRegressionTest.approved.txt
  test/mlnet.Tests/ApprovalTests/ConsoleCodeGeneratorTests.ConsoleAppProgramCSFileContentTest.approved.txt
Labels: AutoML

#3520 Kmean doc minor fixes
  docs/api-reference/io-columns-clustering.md
  src/Microsoft.ML.KMeansClustering/KMeansPlusPlusTrainer.cs
Labels: Bug Bash

#3497 [Fix Latex Code] Use textbr for vectors
  src/Microsoft.ML.StandardTrainers/FactorizationMachine/FactorizationMachineTrainer.cs
  src/Microsoft.ML.StandardTrainers/Standard/LogisticRegression/LogisticRegression.cs
  src/Microsoft.ML.StandardTrainers/Standard/LogisticRegression/MulticlassLogisticRegression.cs
  src/Microsoft.ML.StandardTrainers/Standard/SdcaMulticlass.cs
Labels: Bug Bash, bug

#3554 [AutoML] Change the conflicting alias for the command line option
  src/mlnet/Commands/CommandDefinitions.cs
Labels: AutoML

#3534 Polish some options' XML document strings
  src/Microsoft.ML.StandardTrainers/Standard/LogisticRegression/LbfgsPredictorBase.cs
  src/Microsoft.ML.StandardTrainers/Standard/SdcaBinary.cs
Labels: Bug Bash

#3558 simplifying and improving the examples
  docs/samples/Microsoft.ML.Samples/Dynamic/DataOperations/FilterRowsByKeyColumnFraction.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/DataOperations/FilterRowsByMissingValues.cs
  src/Microsoft.ML.Data/DataLoadSave/DataOperationsCatalog.cs
Labels: documentation

#3546 Fix Time Series XML Doc
  docs/api-reference/io-time-series-change-point.md
  docs/api-reference/io-time-series-spike.md
  docs/api-reference/time-series-pvalue.md
  docs/api-reference/time-series-scorer.md
  src/Microsoft.ML.TimeSeries/IidChangePointDetector.cs
  src/Microsoft.ML.TimeSeries/IidSpikeDetector.cs
  src/Microsoft.ML.TimeSeries/SsaChangePointDetector.cs
  src/Microsoft.ML.TimeSeries/SsaSpikeDetector.cs
Labels: Bug Bash

#3563 Avoid using hidden classes defined in SampleUtils
  docs/samples/Microsoft.ML.Samples/Dynamic/DataOperations/DataViewEnumerable.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/DataOperations/DataViewEnumerable.tt
  docs/samples/Microsoft.ML.Samples/Dynamic/DataOperations/FilterRowsByColumn.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/DataOperations/FilterRowsByColumn.tt
  docs/samples/Microsoft.ML.Samples/Dynamic/DataOperations/ShuffleRows.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/DataOperations/ShuffleRows.tt
  docs/samples/Microsoft.ML.Samples/Dynamic/DataOperations/SkipRows.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/DataOperations/SkipRows.tt
  docs/samples/Microsoft.ML.Samples/Dynamic/DataOperations/TakeRows.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/DataOperations/TakeRows.tt
  docs/samples/Microsoft.ML.Samples/Dynamic/DataOperations/TemperatureAndLatitude.ttinclude
  docs/samples/Microsoft.ML.Samples/Microsoft.ML.Samples.csproj
Labels: Bug Bash

#3530 Indicating in which package transforms belong.
  src/Microsoft.ML.OnnxTransformer/DnnImageFeaturizerTransform.cs
  src/Microsoft.ML.OnnxTransformer/OnnxTransform.cs
Labels: documentation

#3565 Towards #3527
  docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/Regression/OnlineGradientDescent.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/Regression/OnlineGradientDescent.tt
  src/Microsoft.ML.Mkl.Components/OlsLinearRegression.cs
  src/Microsoft.ML.Recommender/MatrixFactorizationTrainer.cs
  src/Microsoft.ML.StandardTrainers/Standard/LogisticRegression/MulticlassLogisticRegression.cs
  src/Microsoft.ML.StandardTrainers/Standard/Online/OnlineGradientDescent.cs
  src/Microsoft.ML.StandardTrainers/Standard/SdcaMulticlass.cs
Labels: documentation

#3543 Fix Dnn image featurizer and Onnx XML documentation
  src/Microsoft.ML.OnnxTransformer/DnnImageFeaturizerTransform.cs
  src/Microsoft.ML.OnnxTransformer/OnnxCatalog.cs
  src/Microsoft.ML.OnnxTransformer/OnnxTransform.cs
Labels: documentation

#3545 Fix the ApproximatedKernelMappingEstimator XML doc
  src/Microsoft.ML.Transforms/FourierDistributionSampler.cs
  src/Microsoft.ML.Transforms/KernelCatalog.cs
Labels: documentation

#3548 Fix feature selection catalog XML documentaion
  src/Microsoft.ML.Data/Transforms/ConversionsExtensionsCatalog.cs
  src/Microsoft.ML.Transforms/CountFeatureSelection.cs
  src/Microsoft.ML.Transforms/FeatureSelectionCatalog.cs
  src/Microsoft.ML.Transforms/MutualInformationFeatureSelection.cs
Labels: documentation

#3567 [AutoML] Generated project - FastTree nuget package inclusion dynamically
  src/mlnet/CodeGenerator/CSharp/CodeGenerator.cs
  src/mlnet/CodeGenerator/CSharp/TrainerGeneratorFactory.cs
  src/mlnet/CodeGenerator/CSharp/TrainerGenerators.cs
  src/mlnet/Telemetry/MlTelemetry.cs
  src/mlnet/Templates/Console/ModelProject.cs
  src/mlnet/Templates/Console/ModelProject.tt
  src/mlnet/Templates/Console/PredictProject.cs
  src/mlnet/Templates/Console/PredictProject.tt
  test/mlnet.Tests/ApprovalTests/ConsoleCodeGeneratorTests.ModelProjectFileContentTest.approved.txt
  test/mlnet.Tests/ApprovalTests/ConsoleCodeGeneratorTests.cs
Labels: AutoML

#3541 Fix GcNorm and LpNorm xml doc
  src/Microsoft.ML.Transforms/GcnTransform.cs
  src/Microsoft.ML.Transforms/NormalizerCatalog.cs
Labels: documentation

#3571 Fix time series XML again
  docs/api-reference/io-time-series-change-point.md
  docs/api-reference/io-time-series-spike.md
  docs/api-reference/time-series-pvalue.md
  docs/samples/Microsoft.ML.Samples/Program.cs
  src/Microsoft.ML.TimeSeries/IidChangePointDetector.cs
  src/Microsoft.ML.TimeSeries/IidSpikeDetector.cs
  src/Microsoft.ML.TimeSeries/SsaChangePointDetector.cs
  src/Microsoft.ML.TimeSeries/SsaSpikeDetector.cs
Labels: Bug Bash

#3458 [AutoML] Add AutoML example code
  Microsoft.ML.AutoML.sln
  docs/samples/Microsoft.ML.AutoML.Samples/BinaryClassificationExperiment.cs
  docs/samples/Microsoft.ML.AutoML.Samples/DataStructures/PixelData.cs
  docs/samples/Microsoft.ML.AutoML.Samples/DataStructures/PixelPrediction.cs
  docs/samples/Microsoft.ML.AutoML.Samples/DataStructures/SentimentIssue.cs
  docs/samples/Microsoft.ML.AutoML.Samples/DataStructures/SentimentPrediction.cs
  docs/samples/Microsoft.ML.AutoML.Samples/DataStructures/TaxiTrip.cs
  docs/samples/Microsoft.ML.AutoML.Samples/DataStructures/TaxiTripFarePrediction.cs
  docs/samples/Microsoft.ML.AutoML.Samples/Microsoft.ML.AutoML.Samples.csproj
  docs/samples/Microsoft.ML.AutoML.Samples/MulticlassClassificationExperiment.cs
  docs/samples/Microsoft.ML.AutoML.Samples/Program.cs
  docs/samples/Microsoft.ML.AutoML.Samples/RegressionExperiment.cs
  src/Microsoft.ML.Auto/API/AutoCatalog.cs
  src/Microsoft.ML.Auto/API/BinaryClassificationExperiment.cs
  src/Microsoft.ML.Auto/API/MulticlassClassificationExperiment.cs
  src/Microsoft.ML.Auto/API/RegressionExperiment.cs
Labels: AutoML

#3578 Confusion matrix for multiclass samples
  docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/MulticlassClassification/LbfgsMaximumEntropy.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/MulticlassClassification/LbfgsMaximumEntropy.tt
  docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/MulticlassClassification/LbfgsMaximumEntropyWithOptions.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/MulticlassClassification/LbfgsMaximumEntropyWithOptions.tt
  docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/MulticlassClassification/LightGbm.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/MulticlassClassification/LightGbm.tt
  docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/MulticlassClassification/LightGbmWithOptions.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/MulticlassClassification/LightGbmWithOptions.tt
  docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/MulticlassClassification/MulticlassClassification.ttinclude
  docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/MulticlassClassification/NaiveBayes.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/MulticlassClassification/NaiveBayes.tt
  docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/MulticlassClassification/OneVersusAll.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/MulticlassClassification/OneVersusAll.tt
  docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/MulticlassClassification/PairwiseCoupling.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/MulticlassClassification/PairwiseCoupling.tt
  docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/MulticlassClassification/SdcaMaximumEntropy.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/MulticlassClassification/SdcaMaximumEntropy.tt
  docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/MulticlassClassification/SdcaMaximumEntropyWithOptions.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/MulticlassClassification/SdcaMaximumEntropyWithOptions.tt
  docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/MulticlassClassification/SdcaNonCalibrated.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/MulticlassClassification/SdcaNonCalibrated.tt
  docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/MulticlassClassification/SdcaNonCalibratedWithOptions.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/MulticlassClassification/SdcaNonCalibratedWithOptions.tt
Labels: documentation

#3579 Fix runtime exceptions in samples.
  docs/samples/Microsoft.ML.Samples/Dynamic/DataOperations/BootstrapSample.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/Conversion/KeyToValueToKey.cs
Labels: bug, documentation

#3593 [AutoML] PipelineSuggester: don't recommend pipelines from first-stage trainers that failed
  src/Microsoft.ML.Auto/PipelineSuggesters/PipelineSuggester.cs
Labels: AutoML

#3599 [AutoML] InferColumns API: Validate all columns specified in column info exist in inferred data view
  src/Microsoft.ML.Auto/ColumnInference/ColumnInferenceApi.cs
  src/Microsoft.ML.Auto/ColumnInference/ColumnInferenceValidationUtil.cs
  src/Microsoft.ML.Auto/ColumnInference/ColumnInformationUtil.cs
  test/Microsoft.ML.AutoML.Tests/ColumnInferenceValidationUtilTests.cs
  test/Microsoft.ML.AutoML.Tests/ColumnInformationUtilTests.cs
Labels: AutoML

#3597 [AutoML] AutoML SDK API: validate schema types of input IDataView
  src/Microsoft.ML.Auto/API/ExperimentBase.cs
  src/Microsoft.ML.Auto/Utils/UserInputValidationUtil.cs
  test/Microsoft.ML.AutoML.Tests/UserInputValidationTests.cs
Labels: AutoML

#3591 [AutoML] If first three iterations all fail, short-circuit AutoML experiment
  src/Microsoft.ML.Auto/Experiment/Experiment.cs
  src/Microsoft.ML.Auto/Experiment/SuggestedPipelineRunDetails/SuggestedPipelineCrossValRunDetail.cs
  src/Microsoft.ML.Auto/Experiment/SuggestedPipelineRunDetails/SuggestedPipelineRunDetail.cs
Labels: AutoML

#3610 [AutoML] take dependency on a specific ml.net version
  Microsoft.ML.AutoML.sln
  nuget.config
  src/Microsoft.ML.AutoML/Microsoft.ML.AutoML.csproj
  src/Microsoft.ML.AutoML/TrainerExtensions/SweepableParams.cs
Labels: AutoML

#3616 [AutoML] force a specific ml.net nuget version, fix typo
  src/mlnet/Telemetry/MlTelemetry.cs
  src/mlnet/mlnet.csproj
Labels: AutoML

#3618 [AutoML] Fix error handling in CLI.
  src/mlnet/CodeGenerator/CodeGenerationHelper.cs
  src/mlnet/ProgressBar/ProgressBar.cs
Labels: AutoML

#3617 [AutoML] turn off line pragmas in .tt files to play nice with signing
  src/mlnet/Templates/Console/ModelProject.cs
  src/mlnet/Templates/Console/ModelProject.tt
  src/mlnet/Templates/Console/ObservationClass.cs
  src/mlnet/Templates/Console/ObservationClass.tt
  src/mlnet/Templates/Console/PredictProgram.cs
  src/mlnet/Templates/Console/PredictProgram.tt
  src/mlnet/Templates/Console/PredictionClass.cs
  src/mlnet/Templates/Console/PredictionClass.tt
Labels: AutoML

#3619 [AutoML] param name change in learners in CLI
  src/mlnet/CodeGenerator/CSharp/TrainerGenerators.cs
Labels: AutoML

#3620 [AutoML] return null instead of null ref crash on Model property accessor
  src/Microsoft.ML.AutoML/API/RunDetails/RunDetail.cs
Labels: AutoML

#3595 Refactoring clustering catalog samples line width to 85
  docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/Clustering/Clustering.ttinclude
  docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/Clustering/KMeans.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/Clustering/KMeansWithOptions.cs
  docs/samples/Microsoft.ML.Samples/Program.cs
Labels: documentation

#3624 [AutoML] Handling label column names which have space and exception logging
  src/mlnet/CodeGenerator/CSharp/CodeGenerator.cs
  src/mlnet/CodeGenerator/CodeGenerationHelper.cs
  src/mlnet/Program.cs
  src/mlnet/Strings.resx
  src/mlnet/strings.Designer.cs
Labels: AutoML
