Repository dotnet/machinelearning, pull requests merged in 2019-03, with the labels that each got.

#2807 Make accessor of linear coefficients unique to the public
  docs/samples/Microsoft.ML.Samples/Dynamic/FeatureContributionCalculationTransform.cs
  docs/samples/Microsoft.ML.Samples/Static/SDCARegression.cs
  src/Microsoft.ML.Data/Dirty/PredictorInterfaces.cs
  src/Microsoft.ML.HalLearners/SymSgdClassificationTrainer.cs
  src/Microsoft.ML.StandardLearners/Standard/LinearModelParameters.cs
  src/Microsoft.ML.StandardLearners/Standard/ModelStatistics.cs
  src/Microsoft.ML.StandardLearners/Standard/Online/OnlineLinear.cs
  src/Microsoft.ML.StandardLearners/Standard/SdcaBinary.cs
  test/Microsoft.ML.StaticPipelineTesting/Training.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/IntrospectiveTraining.cs
Labels: api

#2815 [Tiny] Use string[] instead of IEnumerable<string> in column names
  docs/samples/Microsoft.ML.Samples/Dynamic/TextTransform.cs
  src/Microsoft.ML.Transforms/Text/TextCatalog.cs
  test/Microsoft.ML.Benchmarks/StochasticDualCoordinateAscentClassifierBench.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/Visibility.cs
Labels: api

#2844 [One line Fix] Fix a use of text featurizer
  test/Microsoft.ML.Functional.Tests/DataTransformation.cs
Labels: bug

#2849 Remove random trainer and model parameters from the public surface.
  docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/BinaryClassification/RandomTrainerSample.cs
  src/Microsoft.ML.StandardLearners/Standard/Simple/SimpleTrainers.cs
  src/Microsoft.ML.StandardLearners/StandardLearnersCatalog.cs
  test/Microsoft.ML.Predictor.Tests/TestPredictors.cs
  test/Microsoft.ML.TestFramework/Learners.cs
  test/Microsoft.ML.Tests/TrainerEstimators/PriorRandomTests.cs
Labels: api

#2753 Scrub Fast Tree Family
  docs/samples/Microsoft.ML.Samples/Dynamic/FastTreeRegression.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/GeneralizedAdditiveModels.cs
  docs/samples/Microsoft.ML.Samples/Static/FastTreeBinaryClassification.cs
  docs/samples/Microsoft.ML.Samples/Static/FastTreeRegression.cs
  src/Microsoft.ML.FastTree/BoostingFastTree.cs
  src/Microsoft.ML.FastTree/FastTree.cs
  src/Microsoft.ML.FastTree/FastTreeArguments.cs
  src/Microsoft.ML.FastTree/FastTreeClassification.cs
  src/Microsoft.ML.FastTree/FastTreeRanking.cs
  src/Microsoft.ML.FastTree/FastTreeRegression.cs
  src/Microsoft.ML.FastTree/FastTreeTweedie.cs
  src/Microsoft.ML.FastTree/GamClassification.cs
  src/Microsoft.ML.FastTree/GamModelParameters.cs
  src/Microsoft.ML.FastTree/GamRegression.cs
  src/Microsoft.ML.FastTree/GamTrainer.cs
  src/Microsoft.ML.FastTree/RandomForest.cs
  src/Microsoft.ML.FastTree/RandomForestClassification.cs
  src/Microsoft.ML.FastTree/RandomForestRegression.cs
  src/Microsoft.ML.FastTree/RegressionTree.cs
  src/Microsoft.ML.FastTree/TreeTrainersCatalog.cs
  src/Microsoft.ML.StaticPipe/TreeTrainersStatic.cs
  src/Microsoft.ML.Sweeper/Algorithms/SmacSweeper.cs
  test/BaselineOutput/Common/EntryPoints/core_manifest.json
  test/Microsoft.ML.Core.Tests/UnitTests/TestEntryPoints.cs
  test/Microsoft.ML.FSharp.Tests/SmokeTests.fs
  test/Microsoft.ML.Functional.Tests/Evaluation.cs
  test/Microsoft.ML.Functional.Tests/Explainability.cs
  test/Microsoft.ML.Functional.Tests/Validation.cs
  test/Microsoft.ML.Predictor.Tests/TestGamPublicInterfaces.cs
  test/Microsoft.ML.Predictor.Tests/TestPredictors.cs
  test/Microsoft.ML.StaticPipelineTesting/Training.cs
  test/Microsoft.ML.StaticPipelineTesting/TreeRepresentation.cs
  test/Microsoft.ML.TestFramework/TestCommandBase.cs
  test/Microsoft.ML.Tests/OnnxConversionTest.cs
  test/Microsoft.ML.Tests/Scenarios/Api/CookbookSamples/CookbookSamples.cs
  test/Microsoft.ML.Tests/Scenarios/Api/CookbookSamples/CookbookSamplesDynamicApi.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/IntrospectiveTraining.cs
  test/Microsoft.ML.Tests/Scenarios/OvaTest.cs
  test/Microsoft.ML.Tests/TrainerEstimators/TreeEnsembleFeaturizerTest.cs
  test/Microsoft.ML.Tests/TrainerEstimators/TreeEstimators.cs
Labels: api

#2799 Adding a sample for the OnnxCatalog.DnnFeaturizeImage extension
  docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/ImageAnalytics/ConvertToGrayScale.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/ImageAnalytics/DnnFeaturizeImage.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/ImageAnalytics/ExtractPixels.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/ImageAnalytics/LoadImages.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/ImageAnalytics/ResizeImages.cs
  docs/samples/Microsoft.ML.Samples/Microsoft.ML.Samples.csproj
  src/Microsoft.ML.ImageAnalytics/ExtensionsCatalog.cs
  src/Microsoft.ML.OnnxTransformer/DnnImageFeaturizerTransform.cs
  src/Microsoft.ML.OnnxTransformer/OnnxCatalog.cs
Labels: documentation

#2851 Polish early stop rules in fast tree
  src/Microsoft.ML.FastTree/BoostingFastTree.cs
  src/Microsoft.ML.FastTree/FastTree.cs
  src/Microsoft.ML.FastTree/FastTreeArguments.cs
  src/Microsoft.ML.FastTree/FastTreeRanking.cs
  src/Microsoft.ML.FastTree/FastTreeRegression.cs
  src/Microsoft.ML.FastTree/FastTreeTweedie.cs
  src/Microsoft.ML.FastTree/Training/EarlyStoppingCriteria.cs
  test/Microsoft.ML.Core.Tests/UnitTests/TestEarlyStoppingCriteria.cs
  test/Microsoft.ML.Functional.Tests/Validation.cs
Labels: api

#2846 Remove ConcurrencyFactor from IHostEnvironment
  docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/Clustering/KMeans.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/Clustering/KMeansWithOptions.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/Recommendation/MatrixFactorization.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/Recommendation/MatrixFactorizationWithOptions.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/Conversion/ConvertType.cs
  src/Microsoft.ML.Core/Data/IHostEnvironment.cs
  src/Microsoft.ML.Core/Environment/ConsoleEnvironment.cs
  src/Microsoft.ML.Core/Environment/HostEnvironmentBase.cs
  src/Microsoft.ML.Data/Commands/DataCommand.cs
  src/Microsoft.ML.Data/Data/DataViewUtils.cs
  src/Microsoft.ML.Data/DataLoadSave/Text/TextLoaderCursor.cs
  src/Microsoft.ML.Data/DataView/CacheDataView.cs
  src/Microsoft.ML.Data/DebuggerExtensions.cs
  src/Microsoft.ML.Data/MLContext.cs
  src/Microsoft.ML.Data/Utilities/LocalEnvironment.cs
  src/Microsoft.ML.FastTree/FastTree.cs
  src/Microsoft.ML.FastTree/GamTrainer.cs
  src/Microsoft.ML.FastTree/SumupPerformanceCommand.cs
  src/Microsoft.ML.KMeansClustering/KMeansPlusPlusTrainer.cs
  src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/LbfgsPredictorBase.cs
  src/Microsoft.ML.StandardLearners/Standard/MultiClass/PairwiseCouplingTrainer.cs
  src/Microsoft.ML.StandardLearners/Standard/SdcaBinary.cs
  src/Microsoft.ML.StandardLearners/Standard/SdcaRegression.cs
  src/Microsoft.ML.StandardLearners/Standard/StochasticTrainerBase.cs
  src/Microsoft.ML.Transforms/Text/WordEmbeddingsExtractor.cs
  test/BaselineOutput/Common/SavePipe/SavePipeWithKey-CursLog.txt
  test/Microsoft.ML.Benchmarks/PredictionEngineBench.cs
  test/Microsoft.ML.FSharp.Tests/SmokeTests.fs
  test/Microsoft.ML.Functional.Tests/DataIO.cs
  test/Microsoft.ML.Functional.Tests/DataTransformation.cs
  test/Microsoft.ML.Functional.Tests/Evaluation.cs
  test/Microsoft.ML.Functional.Tests/Explainability.cs
  test/Microsoft.ML.Functional.Tests/Validation.cs
  test/Microsoft.ML.OnnxTransformerTest/DnnImageFeaturizerTest.cs
  test/Microsoft.ML.OnnxTransformerTest/OnnxTransformTests.cs
  test/Microsoft.ML.StaticPipelineTesting/Training.cs
  test/Microsoft.ML.TestFramework/DataPipe/TestDataPipe.cs
  test/Microsoft.ML.TestFramework/DataPipe/TestDataPipeBase.cs
  test/Microsoft.ML.Tests/OnnxConversionTest.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/IntrospectiveTraining.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/MultithreadedPrediction.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/SimpleTrainAndPredict.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/TrainSaveModelAndPredict.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/TrainWithInitialPredictor.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/Visibility.cs
  test/Microsoft.ML.Tests/Scenarios/ClusteringTests.cs
  test/Microsoft.ML.Tests/Scenarios/IrisPlantClassificationTests.cs
  test/Microsoft.ML.Tests/Scenarios/IrisPlantClassificationWithStringLabelTests.cs
  test/Microsoft.ML.Tests/Scenarios/TensorflowTests.cs
  test/Microsoft.ML.Tests/ScenariosWithDirectInstantiation/IrisPlantClassificationTests.cs
  test/Microsoft.ML.Tests/ScenariosWithDirectInstantiation/TensorflowTests.cs
  test/Microsoft.ML.Tests/TensorFlowEstimatorTests.cs
  test/Microsoft.ML.Tests/TextLoaderTests.cs
  test/Microsoft.ML.Tests/TrainerEstimators/MatrixFactorizationTests.cs
  test/Microsoft.ML.Tests/TrainerEstimators/TreeEstimators.cs
  test/Microsoft.ML.Tests/Transformers/TextFeaturizerTests.cs
  test/Microsoft.ML.TimeSeries.Tests/TimeSeriesDirectApi.cs
  test/Microsoft.ML.TimeSeries.Tests/TimeSeriesStaticTests.cs
Labels: api

#2878 Make array values intended to be immutable IReadOnlyList
  src/Microsoft.ML.Core/Data/IProgressChannel.cs
  src/Microsoft.ML.Core/Data/ProgressReporter.cs
  src/Microsoft.ML.Core/Environment/ConsoleEnvironment.cs
  src/Microsoft.ML.Data/Evaluators/Metrics/MultiClassClassifierMetrics.cs
  src/Microsoft.ML.Data/Evaluators/Metrics/RankingMetrics.cs
  src/Microsoft.ML.Data/Transforms/ValueToKeyMappingEstimator.cs
  src/Microsoft.ML.Data/Transforms/ValueToKeyMappingTransformer.cs
  src/Microsoft.ML.Transforms/MetricStatistics.cs
  src/Microsoft.ML.Transforms/PermutationFeatureImportanceExtensions.cs
  src/Microsoft.ML.Transforms/Text/NgramHashingTransformer.cs
  src/Microsoft.ML.Transforms/Text/WordTokenizing.cs
  test/Microsoft.ML.StaticPipelineTesting/Training.cs
  test/Microsoft.ML.Tests/PermutationFeatureImportanceTests.cs
  test/Microsoft.ML.Tests/Scenarios/IrisPlantClassificationTests.cs
  test/Microsoft.ML.Tests/Scenarios/IrisPlantClassificationWithStringLabelTests.cs
  test/Microsoft.ML.Tests/ScenariosWithDirectInstantiation/IrisPlantClassificationTests.cs
Labels: api

#2880 Update TreeTrainersCatalog to use standard parameter names
  docs/samples/Microsoft.ML.Samples/Dynamic/GeneralizedAdditiveModels.cs
  src/Microsoft.ML.FastTree/TreeTrainersCatalog.cs
  test/Microsoft.ML.Functional.Tests/IntrospectiveTraining.cs
Labels: api

#2876 Scrubbing task: rest of transforms
  docs/code/MlNetCookBook.md
  docs/samples/Microsoft.ML.Samples/Dynamic/PermutationFeatureImportance/PFIHelper.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/CustomMappingSample.cs
  docs/samples/Microsoft.ML.Samples/Program.cs
  src/Microsoft.ML.Transforms/CustomMappingCatalog.cs
  src/Microsoft.ML.Transforms/ExtensionsCatalog.cs
  src/Microsoft.ML.Transforms/MissingValueIndicatorTransformer.cs
  test/Microsoft.ML.Tests/Scenarios/Api/CookbookSamples/CookbookSamplesDynamicApi.cs
Labels: api

#2908 Fix links in Entrypoints.md after StandardLearners rename.
  docs/code/EntryPoints.md
Labels: api

#2862 Scrubbing of the key related transforms
  docs/code/MlNetCookBook.md
  docs/samples/Microsoft.ML.Samples/Dynamic/KeyToValueValueToKey.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/TensorFlow/TextClassification.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/ValueMapping.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/ValueMappingFloatToString.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/ValueMappingStringToArray.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/ValueMappingStringToKeyType.cs
  src/Microsoft.ML.Data/Transforms/ConversionsExtensionsCatalog.cs
  src/Microsoft.ML.Data/Transforms/ExtensionsCatalog.cs
  src/Microsoft.ML.Data/Transforms/Hashing.cs
  src/Microsoft.ML.Data/Transforms/KeyToValue.cs
  src/Microsoft.ML.Data/Transforms/KeyToVector.cs
  src/Microsoft.ML.Data/Transforms/ValueToKeyMappingEstimator.cs
  src/Microsoft.ML.Data/Transforms/ValueToKeyMappingTransformer.cs
  src/Microsoft.ML.Data/Transforms/ValueToKeyMappingTransformerImpl.cs
  src/Microsoft.ML.EntryPoints/FeatureCombiner.cs
  src/Microsoft.ML.EntryPoints/TrainTestSplit.cs
  src/Microsoft.ML.StaticPipe/CategoricalHashStaticExtensions.cs
  src/Microsoft.ML.StaticPipe/CategoricalStaticExtensions.cs
  src/Microsoft.ML.StaticPipe/TermStaticExtensions.cs
  src/Microsoft.ML.StaticPipe/TextStaticExtensions.cs
  src/Microsoft.ML.StaticPipe/TransformsStatic.cs
  src/Microsoft.ML.Transforms/CategoricalCatalog.cs
  src/Microsoft.ML.Transforms/ConversionsCatalog.cs
  src/Microsoft.ML.Transforms/HashJoiningTransform.cs
  src/Microsoft.ML.Transforms/KeyToVectorMapping.cs
  src/Microsoft.ML.Transforms/OneHotEncoding.cs
  src/Microsoft.ML.Transforms/OneHotHashEncoding.cs
  src/Microsoft.ML.Transforms/Text/NgramHashingTransformer.cs
  src/Microsoft.ML.Transforms/Text/TextCatalog.cs
  src/Microsoft.ML.Transforms/Text/WordBagTransform.cs
  src/Microsoft.ML.Transforms/Text/WordHashBagProducingTransform.cs
  src/Microsoft.ML.Transforms/Text/WrappedTextTransformers.cs
  src/Microsoft.ML.Transforms/doc.xml
  test/BaselineOutput/Common/EntryPoints/core_manifest.json
  test/Microsoft.ML.Benchmarks/HashBench.cs
  test/Microsoft.ML.Core.Tests/UnitTests/TestEntryPoints.cs
  test/Microsoft.ML.Functional.Tests/IntrospectiveTraining.cs
  test/Microsoft.ML.StaticPipelineTesting/StaticPipeFakes.cs
  test/Microsoft.ML.TestFramework/DataPipe/TestDataPipe.cs
  test/Microsoft.ML.Tests/OnnxConversionTest.cs
  test/Microsoft.ML.Tests/RangeFilterTests.cs
  test/Microsoft.ML.Tests/Scenarios/Api/CookbookSamples/CookbookSamplesDynamicApi.cs
  test/Microsoft.ML.Tests/ScenariosWithDirectInstantiation/TensorflowTests.cs
  test/Microsoft.ML.Tests/Transformers/CategoricalHashTests.cs
  test/Microsoft.ML.Tests/Transformers/CategoricalTests.cs
  test/Microsoft.ML.Tests/Transformers/ConvertTests.cs
  test/Microsoft.ML.Tests/Transformers/HashTests.cs
  test/Microsoft.ML.Tests/Transformers/KeyToBinaryVectorEstimatorTest.cs
  test/Microsoft.ML.Tests/Transformers/KeyToVectorEstimatorTests.cs
  test/Microsoft.ML.Tests/Transformers/TextFeaturizerTests.cs
  test/Microsoft.ML.Tests/Transformers/ValueMappingTests.cs
Labels: api

#2960 Checking in the samples generated during bug bash for MissingNa, Repl…
  docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/Categorical/OneHotEncoding.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/IndicateMissingValues.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/ReplaceMissingValues.cs
  docs/samples/Microsoft.ML.Samples/Program.cs
  src/Microsoft.ML.Transforms/CategoricalCatalog.cs
  src/Microsoft.ML.Transforms/ExtensionsCatalog.cs
Labels: documentation

#2973 Cleaning TrainCatalog and RecommenderCatalog
  docs/code/MlNetCookBook.md
  docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/BinaryClassification/PriorTrainerSample.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/BinaryClassification/StochasticDualCoordinateAscent.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/MulticlassClassification/LightGbm.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/MulticlassClassification/LightGbmWithOptions.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/Ranking/LightGbm.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/Ranking/LightGbmWithOptions.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/Recommendation/MatrixFactorization.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/Recommendation/MatrixFactorizationWithOptions.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/Regression/LightGbm.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/Regression/LightGbmWithOptions.cs
  src/Microsoft.ML.Data/DataLoadSave/DataOperationsCatalog.cs
  src/Microsoft.ML.Data/TrainCatalog.cs
  src/Microsoft.ML.Recommender/RecommenderCatalog.cs
  test/Microsoft.ML.Benchmarks/RffTransform.cs
  test/Microsoft.ML.Functional.Tests/Evaluation.cs
  test/Microsoft.ML.Functional.Tests/Validation.cs
  test/Microsoft.ML.Tests/Scenarios/Api/CookbookSamples/CookbookSamplesDynamicApi.cs
  test/Microsoft.ML.Tests/Scenarios/Api/TestApi.cs
  test/Microsoft.ML.Tests/ScenariosWithDirectInstantiation/TensorflowTests.cs
  test/Microsoft.ML.Tests/TrainerEstimators/MatrixFactorizationTests.cs
Labels: api

#2966 Clean FeatureContributionCalculation and PermutationFeatureImportance
  docs/samples/Microsoft.ML.Samples/Dynamic/FeatureContributionCalculationTransform.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/PermutationFeatureImportance/PFIRegressionExample.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/PermutationFeatureImportance/PfiBinaryClassificationExample.cs
  src/Microsoft.ML.Data/Model/ModelOperationsCatalog.cs
  src/Microsoft.ML.Data/Transforms/ExplainabilityCatalog.cs
  src/Microsoft.ML.Data/Transforms/FeatureContributionCalculationTransformer.cs
  src/Microsoft.ML.Transforms/PermutationFeatureImportanceExtensions.cs
  test/Microsoft.ML.Functional.Tests/Explainability.cs
  test/Microsoft.ML.Tests/FeatureContributionTests.cs
Labels: api

#2959 Hiding of ColumnOptions
  docs/samples/Microsoft.ML.Samples/Dynamic/Normalizer.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/TensorFlow/TextClassification.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/ImageAnalytics/ConvertToGrayScale.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/ImageAnalytics/DnnFeaturizeImage.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/ImageAnalytics/ExtractPixels.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/ImageAnalytics/LoadImages.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/ImageAnalytics/ResizeImages.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/Projection/VectorWhitenWithOptions.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/ReplaceMissingValues.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/ValueMapping.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/ValueMappingFloatToString.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/ValueMappingStringToArray.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/ValueMappingStringToKeyType.cs
  src/Microsoft.ML.Data/Transforms/ConversionsExtensionsCatalog.cs
  src/Microsoft.ML.Data/Transforms/ExtensionsCatalog.cs
  src/Microsoft.ML.Data/Transforms/Hashing.cs
  src/Microsoft.ML.Data/Transforms/KeyToVector.cs
  src/Microsoft.ML.Data/Transforms/Normalizer.cs
  src/Microsoft.ML.Data/Transforms/TypeConverting.cs
  src/Microsoft.ML.Data/Transforms/ValueToKeyMappingEstimator.cs
  src/Microsoft.ML.ImageAnalytics/ExtensionsCatalog.cs
  src/Microsoft.ML.ImageAnalytics/ImagePixelExtractor.cs
  src/Microsoft.ML.ImageAnalytics/ImageResizer.cs
  src/Microsoft.ML.ImageAnalytics/VectorToImageTransform.cs
  src/Microsoft.ML.Mkl.Components/MklComponentsCatalog.cs
  src/Microsoft.ML.Mkl.Components/VectorWhitening.cs
  src/Microsoft.ML.PCA/PCACatalog.cs
  src/Microsoft.ML.PCA/PcaTransformer.cs
  src/Microsoft.ML.StaticPipe/TransformsStatic.cs
  src/Microsoft.ML.Transforms/CategoricalCatalog.cs
  src/Microsoft.ML.Transforms/ConversionsCatalog.cs
  src/Microsoft.ML.Transforms/CountFeatureSelection.cs
  src/Microsoft.ML.Transforms/ExtensionsCatalog.cs
  src/Microsoft.ML.Transforms/FeatureSelectionCatalog.cs
  src/Microsoft.ML.Transforms/HashJoiningTransform.cs
  src/Microsoft.ML.Transforms/KernelCatalog.cs
  src/Microsoft.ML.Transforms/MissingValueHandlingTransformer.cs
  src/Microsoft.ML.Transforms/MissingValueReplacing.cs
  src/Microsoft.ML.Transforms/NormalizerCatalog.cs
  src/Microsoft.ML.Transforms/OneHotEncoding.cs
  src/Microsoft.ML.Transforms/OneHotHashEncoding.cs
  src/Microsoft.ML.Transforms/Properties/AssemblyInfo.cs
  src/Microsoft.ML.Transforms/RandomFourierFeaturizing.cs
  src/Microsoft.ML.Transforms/Text/LdaTransform.cs
  src/Microsoft.ML.Transforms/Text/NgramHashingTransformer.cs
  src/Microsoft.ML.Transforms/Text/NgramTransform.cs
  src/Microsoft.ML.Transforms/Text/StopWordsRemovingTransformer.cs
  src/Microsoft.ML.Transforms/Text/TextCatalog.cs
  src/Microsoft.ML.Transforms/Text/WordEmbeddingsExtractor.cs
  src/Microsoft.ML.Transforms/Text/WordTokenizing.cs
  test/Microsoft.ML.Functional.Tests/Debugging.cs
  test/Microsoft.ML.Tests/ScenariosWithDirectInstantiation/TensorflowTests.cs
  test/Microsoft.ML.Tests/Transformers/CategoricalTests.cs
  test/Microsoft.ML.Tests/Transformers/NAReplaceTests.cs
  test/Microsoft.ML.Tests/Transformers/ValueMappingTests.cs
Labels: api

#3021 Data catalog done
  docs/samples/Microsoft.ML.Samples/Dynamic/DataOperations/BootstrapSample.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/DataOperations/TrainTestSplit.cs
  src/Microsoft.ML.Data/DataLoadSave/DataOperationsCatalog.cs
  src/Microsoft.ML.ImageAnalytics/doc.xml
Labels: documentation

#3029 Polish standard trainers' catalog (Just rename some variables)
  docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/BinaryClassification/FastForest.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/BinaryClassification/StochasticDualCoordinateAscentNonCalibrated.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/BinaryClassification/StochasticGradientDescentNonCalibratedWithOptions.cs
  src/Microsoft.ML.Data/Evaluators/Metrics/AnomalyDetectionMetrics.cs
  src/Microsoft.ML.Data/TrainCatalog.cs
  src/Microsoft.ML.FastTree/TreeTrainersCatalog.cs
  src/Microsoft.ML.StandardTrainers/Standard/LogisticRegression/LbfgsPredictorBase.cs
  src/Microsoft.ML.StandardTrainers/Standard/LogisticRegression/LogisticRegression.cs
  src/Microsoft.ML.StandardTrainers/Standard/SdcaBinary.cs
  src/Microsoft.ML.StandardTrainers/Standard/SdcaMulticlass.cs
  src/Microsoft.ML.StandardTrainers/StandardTrainersCatalog.cs
  src/Microsoft.ML.StaticPipe/EvaluatorStaticExtensions.cs
  src/Microsoft.ML.StaticPipe/SdcaStaticExtensions.cs
  src/Microsoft.ML.StaticPipe/SgdStatic.cs
  test/Microsoft.ML.Functional.Tests/Common.cs
  test/Microsoft.ML.StaticPipelineTesting/Training.cs
  test/Microsoft.ML.Tests/AnomalyDetectionTests.cs
  test/Microsoft.ML.Tests/TrainerEstimators/MetalinearEstimators.cs
  test/Microsoft.ML.Tests/TrainerEstimators/SdcaTests.cs
  test/Microsoft.ML.Tests/TrainerEstimators/TrainerEstimators.cs
Labels: api

#3030 Polish train catalog (renaming only)
  src/Microsoft.ML.Data/Evaluators/Metrics/MulticlassClassificationMetrics.cs
  src/Microsoft.ML.Data/TrainCatalog.cs
  src/Microsoft.ML.StaticPipe/EvaluatorStaticExtensions.cs
  src/Microsoft.ML.Transforms/PermutationFeatureImportanceExtensions.cs
  test/Microsoft.ML.Tests/AnomalyDetectionTests.cs
  test/Microsoft.ML.Tests/Scenarios/Api/TestApi.cs
  test/Microsoft.ML.Tests/Scenarios/IrisPlantClassificationTests.cs
  test/Microsoft.ML.Tests/Scenarios/IrisPlantClassificationWithStringLabelTests.cs
  test/Microsoft.ML.Tests/TrainerEstimators/SdcaTests.cs
Labels: api

#3042 Hash sample
  docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/Conversion/Hash.cs
  docs/samples/Microsoft.ML.Samples/Microsoft.ML.Samples.csproj
  src/Microsoft.ML.Data/Transforms/ConversionsExtensionsCatalog.cs
Labels: documentation

#3034 Better names to calibreated linear classification models
  docs/samples/Microsoft.ML.Samples/Dynamic/LogisticRegression.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/PermutationFeatureImportance/PfiBinaryClassificationExample.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/BinaryClassification/StochasticDualCoordinateAscent.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/BinaryClassification/StochasticDualCoordinateAscentWithOptions.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/BinaryClassification/SymbolicStochasticGradientDescent.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/BinaryClassification/SymbolicStochasticGradientDescentWithOptions.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/MulticlassClassification/StochasticDualCoordinateAscent.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/Regression/PoissonRegression.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/Regression/PoissonRegressionWithOptions.cs
  src/Microsoft.ML.Ensemble/Trainer/Multiclass/MulticlassDataPartitionEnsembleTrainer.cs
  src/Microsoft.ML.Mkl.Components/MklComponentsCatalog.cs
  src/Microsoft.ML.Mkl.Components/SymSgdClassificationTrainer.cs
  src/Microsoft.ML.StandardTrainers/Standard/LogisticRegression/LogisticRegression.cs
  src/Microsoft.ML.StandardTrainers/Standard/LogisticRegression/MulticlassLogisticRegression.cs
  src/Microsoft.ML.StandardTrainers/Standard/MulticlassClassification/MetaMulticlassTrainer.cs
  src/Microsoft.ML.StandardTrainers/Standard/MulticlassClassification/OneVersusAllTrainer.cs
  src/Microsoft.ML.StandardTrainers/Standard/MulticlassClassification/PairwiseCouplingTrainer.cs
  src/Microsoft.ML.StandardTrainers/Standard/PoissonRegression/PoissonRegression.cs
  src/Microsoft.ML.StandardTrainers/Standard/SdcaBinary.cs
  src/Microsoft.ML.StandardTrainers/Standard/SdcaMulticlass.cs
  src/Microsoft.ML.StandardTrainers/StandardTrainersCatalog.cs
  src/Microsoft.ML.StaticPipe/LbfgsStatic.cs
  src/Microsoft.ML.StaticPipe/SdcaStaticExtensions.cs
  test/BaselineOutput/Common/Command/CommandTrainMlrWithStats-summary.txt
  test/BaselineOutput/Common/EntryPoints/core_ep-list.tsv
  test/Microsoft.ML.Benchmarks/KMeansAndLogisticRegressionBench.cs
  test/Microsoft.ML.Benchmarks/PredictionEngineBench.cs
  test/Microsoft.ML.Benchmarks/StochasticDualCoordinateAscentClassifierBench.cs
  test/Microsoft.ML.Benchmarks/Text/MultiClassClassification.cs
  test/Microsoft.ML.Core.Tests/UnitTests/TestEntryPoints.cs
  test/Microsoft.ML.Functional.Tests/DataTransformation.cs
  test/Microsoft.ML.Functional.Tests/Evaluation.cs
  test/Microsoft.ML.Functional.Tests/IntrospectiveTraining.cs
  test/Microsoft.ML.Functional.Tests/Prediction.cs
  test/Microsoft.ML.Functional.Tests/Training.cs
  test/Microsoft.ML.Predictor.Tests/TestPredictors.cs
  test/Microsoft.ML.StaticPipelineTesting/Training.cs
  test/Microsoft.ML.Tests/FeatureContributionTests.cs
  test/Microsoft.ML.Tests/OnnxConversionTest.cs
  test/Microsoft.ML.Tests/PermutationFeatureImportanceTests.cs
  test/Microsoft.ML.Tests/Scenarios/Api/CookbookSamples/CookbookSamplesDynamicApi.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/DecomposableTrainAndPredict.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/Extensibility.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/PredictAndMetadata.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/SimpleTrainAndPredict.cs
  test/Microsoft.ML.Tests/Scenarios/IrisPlantClassificationTests.cs
  test/Microsoft.ML.Tests/Scenarios/IrisPlantClassificationWithStringLabelTests.cs
  test/Microsoft.ML.Tests/Scenarios/OvaTest.cs
  test/Microsoft.ML.Tests/Scenarios/TensorflowTests.cs
  test/Microsoft.ML.Tests/ScenariosWithDirectInstantiation/IrisPlantClassificationTests.cs
  test/Microsoft.ML.Tests/TrainerEstimators/LbfgsTests.cs
  test/Microsoft.ML.Tests/TrainerEstimators/SdcaTests.cs
  test/Microsoft.ML.Tests/TrainerEstimators/SymSgdClassificationTests.cs
Labels: api
