Repository dotnet/machinelearning, pull requests merged in 2019-01, with the labels that each got.

#1979 making GetCoefficientStatistics public
  src/Microsoft.ML.StandardLearners/Standard/LinearModelParameters.cs
  src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/MulticlassLogisticRegression.cs
  src/Microsoft.ML.StandardLearners/Standard/ModelStatistics.cs
  test/Microsoft.ML.Tests/TrainerEstimators/LbfgsTests.cs
Labels: enhancement

#2021 Remove Legacy dependency in ML.FSharp.Tests
  test/Microsoft.ML.FSharp.Tests/Microsoft.ML.FSharp.Tests.fsproj
  test/Microsoft.ML.FSharp.Tests/SmokeTests.fs
Labels: api, test

#2033 Remove legacy dependency from TextLoaderTests.cs
  test/Microsoft.ML.Tests/TextLoaderTests.cs
Labels: api, test

#2007 Improve documentation for Feature Contribution Calculation
  docs/samples/Microsoft.ML.Samples/Dynamic/FeatureContributionCalculationTransform.cs
  src/Microsoft.ML.Data/Transforms/ExplainabilityCatalog.cs
  src/Microsoft.ML.Data/Transforms/FeatureContributionCalculationTransform.cs
  src/Microsoft.ML.FastTree/FastTree.cs
  src/Microsoft.ML.FastTree/GamTrainer.cs
  src/Microsoft.ML.StandardLearners/Standard/LinearModelParameters.cs
  test/Microsoft.ML.Tests/FeatureContributionTests.cs
Labels: documentation, explainability

#2076 New ML.NET statically typed pipeline Nuget.
  pkg/Microsoft.ML.StaticPipe/Microsoft.ML.StaticPipe.nupkgproj
  pkg/Microsoft.ML.StaticPipe/Microsoft.ML.StaticPipe.symbols.nupkgproj
  src/Microsoft.ML.StaticPipe/Microsoft.ML.StaticPipe.csproj
Labels: api

#2047 Modify API for advanced settings. (FastTree, RandomForest)
  src/Microsoft.ML.Data/EntryPoints/InputBase.cs
  src/Microsoft.ML.FastTree/BoostingFastTree.cs
  src/Microsoft.ML.FastTree/FastTree.cs
  src/Microsoft.ML.FastTree/FastTreeArguments.cs
  src/Microsoft.ML.FastTree/FastTreeClassification.cs
  src/Microsoft.ML.FastTree/FastTreeRanking.cs
  src/Microsoft.ML.FastTree/FastTreeRegression.cs
  src/Microsoft.ML.FastTree/FastTreeTweedie.cs
  src/Microsoft.ML.FastTree/RandomForest.cs
  src/Microsoft.ML.FastTree/RandomForestClassification.cs
  src/Microsoft.ML.FastTree/RandomForestRegression.cs
  src/Microsoft.ML.FastTree/TreeTrainersCatalog.cs
  src/Microsoft.ML.StaticPipe/TreeTrainersStatic.cs
  src/Microsoft.ML.Sweeper/Algorithms/SmacSweeper.cs
  test/BaselineOutput/Common/EntryPoints/core_ep-list.tsv
  test/BaselineOutput/Common/EntryPoints/core_manifest.json
  test/Microsoft.ML.Core.Tests/UnitTests/TestEntryPoints.cs
  test/Microsoft.ML.Predictor.Tests/TestPredictors.cs
  test/Microsoft.ML.Tests/Scenarios/OvaTest.cs
  test/Microsoft.ML.Tests/TrainerEstimators/TreeEstimators.cs
Labels: api

#2128 Publish test trx files on failure
  build/ci/phase-template.yml
Labels: Build

#2110 fixing the AdultData LoadColumn, and IrisWithAllFeatures class.
  docs/code/MlNetCookBook.md
Labels: documentation

#2163 Modify API for advanced settings (several learners)
  src/Microsoft.ML.StandardLearners/Properties/AssemblyInfo.cs
  src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/LbfgsPredictorBase.cs
  src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/LogisticRegression.cs
  src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/MulticlassLogisticRegression.cs
  src/Microsoft.ML.StandardLearners/Standard/MultiClass/MetaMulticlassTrainer.cs
  src/Microsoft.ML.StandardLearners/Standard/Online/AveragedPerceptron.cs
  src/Microsoft.ML.StandardLearners/Standard/Online/LinearSvm.cs
  src/Microsoft.ML.StandardLearners/Standard/Online/OnlineGradientDescent.cs
  src/Microsoft.ML.StandardLearners/Standard/Online/OnlineLinear.cs
  src/Microsoft.ML.StandardLearners/Standard/PoissonRegression/PoissonRegression.cs
  src/Microsoft.ML.StandardLearners/StandardLearnersCatalog.cs
  src/Microsoft.ML.StaticPipe/LbfgsStatic.cs
  src/Microsoft.ML.StaticPipe/OnlineLearnerStatic.cs
  test/BaselineOutput/Common/EntryPoints/core_ep-list.tsv
  test/Microsoft.ML.Benchmarks/KMeansAndLogisticRegressionBench.cs
  test/Microsoft.ML.Core.Tests/UnitTests/TestEntryPoints.cs
  test/Microsoft.ML.Predictor.Tests/TestPredictors.cs
  test/Microsoft.ML.StaticPipelineTesting/Training.cs
  test/Microsoft.ML.Tests/FeatureContributionTests.cs
  test/Microsoft.ML.Tests/OnnxConversionTest.cs
  test/Microsoft.ML.Tests/PermutationFeatureImportanceTests.cs
  test/Microsoft.ML.Tests/Scenarios/Api/TestApi.cs
  test/Microsoft.ML.Tests/Scenarios/OvaTest.cs
  test/Microsoft.ML.Tests/TrainerEstimators/CalibratorEstimators.cs
  test/Microsoft.ML.Tests/TrainerEstimators/LbfgsTests.cs
  test/Microsoft.ML.Tests/TrainerEstimators/MetalinearEstimators.cs
  test/Microsoft.ML.Tests/TrainerEstimators/OnlineLinearTests.cs
Labels: api

#2245 No loader on APIs for ValueToKey/OneHotEncoding
  src/Microsoft.ML.Data/Transforms/ColumnSelecting.cs
  src/Microsoft.ML.Data/Transforms/ConversionsExtensionsCatalog.cs
  src/Microsoft.ML.Data/Transforms/ValueToKeyMappingEstimator.cs
  src/Microsoft.ML.Data/Transforms/ValueToKeyMappingTransformer.cs
  src/Microsoft.ML.Transforms/OneHotEncoding.cs
  src/Microsoft.ML.Transforms/Text/StopWordsRemovingTransformer.cs
  test/Microsoft.ML.Tests/Transformers/CategoricalTests.cs
  test/Microsoft.ML.Tests/Transformers/ConvertTests.cs
Labels: api

#2217 Improve exception message and make consistent with ExceptSchemaMismatch
  src/Microsoft.ML.CpuMath/ProbabilityFunctions.cs
  src/Microsoft.ML.Data/DataLoadSave/DataOperationsCatalog.cs
  src/Microsoft.ML.Data/DataView/TypedCursor.cs
  src/Microsoft.ML.Data/Evaluators/AnomalyDetectionEvaluator.cs
  src/Microsoft.ML.Data/Evaluators/BinaryClassifierEvaluator.cs
  src/Microsoft.ML.Data/Evaluators/ClusteringEvaluator.cs
  src/Microsoft.ML.Data/Evaluators/EvaluatorBase.cs
  src/Microsoft.ML.Data/Evaluators/MultiClassClassifierEvaluator.cs
  src/Microsoft.ML.Data/Evaluators/MultiOutputRegressionEvaluator.cs
  src/Microsoft.ML.Data/Evaluators/QuantileRegressionEvaluator.cs
  src/Microsoft.ML.Data/Evaluators/RegressionEvaluator.cs
  src/Microsoft.ML.Data/Prediction/CalibratorCatalog.cs
  src/Microsoft.ML.Data/Scorers/PredictionTransformer.cs
  src/Microsoft.ML.Data/Training/TrainerEstimatorBase.cs
  src/Microsoft.ML.Data/Transforms/FeatureContributionCalculationTransform.cs
  src/Microsoft.ML.Data/Transforms/KeyToValue.cs
  src/Microsoft.ML.Data/Transforms/NAFilter.cs
  src/Microsoft.ML.Data/Transforms/Normalizer.cs
  src/Microsoft.ML.Data/Transforms/RangeFilter.cs
  src/Microsoft.ML.Data/Transforms/TransformBase.cs
  src/Microsoft.ML.EntryPoints/FeatureCombiner.cs
  src/Microsoft.ML.FastTree/FastTreeRanking.cs
  src/Microsoft.ML.FastTree/TreeEnsembleFeaturizer.cs
  src/Microsoft.ML.LightGBM/LightGbmRankingTrainer.cs
  src/Microsoft.ML.OnnxTransform/OnnxTransform.cs
  src/Microsoft.ML.PCA/PcaTransformer.cs
  src/Microsoft.ML.Recommender/MatrixFactorizationPredictor.cs
  src/Microsoft.ML.Recommender/MatrixFactorizationTrainer.cs
  src/Microsoft.ML.StandardLearners/FactorizationMachine/FactorizationMachineTrainer.cs
  src/Microsoft.ML.StandardLearners/FactorizationMachine/FieldAwareFactorizationMachineModelParameters.cs
  src/Microsoft.ML.StandardLearners/Standard/MultiClass/MetaMulticlassTrainer.cs
  src/Microsoft.ML.StandardLearners/Standard/Online/AveragedPerceptron.cs
  src/Microsoft.ML.StandardLearners/Standard/SdcaBinary.cs
  src/Microsoft.ML.StandardLearners/Standard/SdcaMultiClass.cs
  src/Microsoft.ML.TensorFlow/TensorflowTransform.cs
  src/Microsoft.ML.TimeSeries/AdaptiveSingularSpectrumSequenceModeler.cs
  src/Microsoft.ML.TimeSeries/IidAnomalyDetectionBase.cs
  src/Microsoft.ML.TimeSeries/IidChangePointDetector.cs
  src/Microsoft.ML.TimeSeries/IidSpikeDetector.cs
  src/Microsoft.ML.TimeSeries/SequentialAnomalyDetectionTransformBase.cs
  src/Microsoft.ML.TimeSeries/SequentialTransformBase.cs
  src/Microsoft.ML.TimeSeries/SsaAnomalyDetectionBase.cs
  src/Microsoft.ML.TimeSeries/SsaChangePointDetector.cs
  src/Microsoft.ML.TimeSeries/SsaSpikeDetector.cs
  src/Microsoft.ML.Transforms/MissingValueDroppingTransformer.cs
  src/Microsoft.ML.Transforms/Text/LdaTransform.cs
  src/Microsoft.ML.Transforms/Text/StopWordsRemovingTransformer.cs
Labels: usability

#2331 Fix fake schema's creation and add a test
  src/Microsoft.ML.Data/DataLoadSave/FakeSchema.cs
  test/Microsoft.ML.Tests/FakeSchemaTest.cs
  test/Microsoft.ML.Tests/TextLoaderTests.cs
Labels: bug
