Repository dotnet/machinelearning, pull requests merged in 2019-02, with the labels that each got.

#2340 Creation of components through MLContext and cleanup (KeyToValue, ValueToKey, OneHotEncoding)
  docs/samples/Microsoft.ML.Samples/Dynamic/KeyToValueValueToKey.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/ValueMappingStringToKeyType.cs
  src/Microsoft.ML.Data/Transforms/ColumnBindingsBase.cs
  src/Microsoft.ML.Data/Transforms/ConversionsExtensionsCatalog.cs
  src/Microsoft.ML.Data/Transforms/KeyToValue.cs
  src/Microsoft.ML.Data/Transforms/ValueToKeyMappingEstimator.cs
  src/Microsoft.ML.Data/Transforms/ValueToKeyMappingTransformer.cs
  src/Microsoft.ML.Data/Transforms/ValueToKeyMappingTransformerImpl.cs
  src/Microsoft.ML.EntryPoints/FeatureCombiner.cs
  src/Microsoft.ML.StaticPipe/CategoricalStaticExtensions.cs
  src/Microsoft.ML.StaticPipe/TransformsStatic.cs
  src/Microsoft.ML.Transforms/CategoricalCatalog.cs
  src/Microsoft.ML.Transforms/EntryPoints/TextAnalytics.cs
  src/Microsoft.ML.Transforms/OneHotEncoding.cs
  src/Microsoft.ML.Transforms/Text/WordBagTransform.cs
  src/Microsoft.ML.Transforms/Text/WordHashBagProducingTransform.cs
  test/BaselineOutput/Common/EntryPoints/core_ep-list.tsv
  test/Microsoft.ML.Core.Tests/UnitTests/TestEntryPoints.cs
  test/Microsoft.ML.Predictor.Tests/TestPredictors.cs
  test/Microsoft.ML.Tests/ScenariosWithDirectInstantiation/TensorflowTests.cs
  test/Microsoft.ML.Tests/TermEstimatorTests.cs
  test/Microsoft.ML.Tests/TrainerEstimators/TrainerEstimators.cs
  test/Microsoft.ML.Tests/Transformers/CategoricalTests.cs
  test/Microsoft.ML.Tests/Transformers/ConvertTests.cs
  test/Microsoft.ML.Tests/Transformers/CopyColumnEstimatorTests.cs
  test/Microsoft.ML.Tests/Transformers/KeyToBinaryVectorEstimatorTest.cs
  test/Microsoft.ML.Tests/Transformers/KeyToValueTests.cs
  test/Microsoft.ML.Tests/Transformers/KeyToVectorEstimatorTests.cs
  test/Microsoft.ML.Tests/Transformers/NAIndicatorTests.cs
Labels: api

#2372 Image analytics documentation, samples, internalization
  docs/samples/Microsoft.ML.Samples/Dynamic/ImageAnalytics/ConvertToGrayScale.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/ImageAnalytics/ExtractPixels.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/ImageAnalytics/LoadImage.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/ImageAnalytics/ResizeImage.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/Concatenate.cs
  docs/samples/Microsoft.ML.Samples/Program.cs
  src/Microsoft.ML.ImageAnalytics/EntryPoints/ImageAnalytics.cs
  src/Microsoft.ML.ImageAnalytics/ExtensionsCatalog.cs
  src/Microsoft.ML.ImageAnalytics/ImageGrayscale.cs
  src/Microsoft.ML.ImageAnalytics/ImageLoader.cs
  src/Microsoft.ML.ImageAnalytics/ImagePixelExtractor.cs
  src/Microsoft.ML.ImageAnalytics/ImageResizer.cs
  src/Microsoft.ML.ImageAnalytics/Properties/AssemblyInfo.cs
  src/Microsoft.ML.ImageAnalytics/doc.xml
  src/Microsoft.ML.SamplesUtils/SamplesDatasetUtils.cs
  src/Microsoft.ML.StaticPipe/ImageStaticPipe.cs
  src/Microsoft.ML.StaticPipe/ImageTransformsStatic.cs
  test/BaselineOutput/Common/EntryPoints/core_ep-list.tsv
  test/Microsoft.ML.Core.Tests/UnitTests/TestEntryPoints.cs
  test/Microsoft.ML.Tests/ImagesTests.cs
  test/Microsoft.ML.Tests/ScenariosWithDirectInstantiation/TensorflowTests.cs
Labels: api, documentation

#2364 Creation of components through MLContext and cleanup (OneHotHash, Hash, CopyCol, KeyToVector)
  src/Microsoft.ML.Data/EntryPoints/SchemaManipulation.cs
  src/Microsoft.ML.Data/Properties/AssemblyInfo.cs
  src/Microsoft.ML.Data/TrainCatalog.cs
  src/Microsoft.ML.Data/Transforms/ColumnCopying.cs
  src/Microsoft.ML.Data/Transforms/ConversionsExtensionsCatalog.cs
  src/Microsoft.ML.Data/Transforms/Hashing.cs
  src/Microsoft.ML.Data/Transforms/KeyToVector.cs
  src/Microsoft.ML.EntryPoints/FeatureCombiner.cs
  src/Microsoft.ML.StaticPipe/TransformsStatic.cs
  src/Microsoft.ML.Transforms/KeyToVectorMapping.cs
  src/Microsoft.ML.Transforms/OneHotEncoding.cs
  src/Microsoft.ML.Transforms/OneHotHashEncoding.cs
  src/Microsoft.ML.Transforms/Text/WordHashBagProducingTransform.cs
  test/BaselineOutput/Common/EntryPoints/core_ep-list.tsv
  test/Microsoft.ML.Benchmarks/HashBench.cs
  test/Microsoft.ML.TestFramework/DataPipe/TestDataPipe.cs
  test/Microsoft.ML.Tests/Transformers/CategoricalHashTests.cs
  test/Microsoft.ML.Tests/Transformers/HashTests.cs
  test/Microsoft.ML.Tests/Transformers/KeyToVectorEstimatorTests.cs
Labels: api

#2366 Creation of components through MLContext and cleanup (GcnNorm, LpNorm, RandomFourier, CustomStopWords, VectorWhiten, PCA)
  src/Microsoft.ML.Data/Transforms/BootstrapSamplingTransformer.cs
  src/Microsoft.ML.Data/Transforms/RowShufflingTransformer.cs
  src/Microsoft.ML.Ensemble/Selector/SubsetSelector/BootstrapSelector.cs
  src/Microsoft.ML.HalLearners.StaticPipe/VectorWhiteningStaticExtensions.cs
  src/Microsoft.ML.HalLearners/HalLearnersCatalog.cs
  src/Microsoft.ML.HalLearners/SymSgdClassificationTrainer.cs
  src/Microsoft.ML.HalLearners/VectorWhitening.cs
  src/Microsoft.ML.PCA/PCACatalog.cs
  src/Microsoft.ML.PCA/PcaTransformer.cs
  src/Microsoft.ML.StandardLearners/Standard/SdcaBinary.cs
  src/Microsoft.ML.StandardLearners/Standard/StochasticTrainerBase.cs
  src/Microsoft.ML.StaticPipe/TransformsStatic.cs
  src/Microsoft.ML.Transforms/GcnTransform.cs
  src/Microsoft.ML.Transforms/LearnerFeatureSelection.cs
  src/Microsoft.ML.Transforms/ProjectionCatalog.cs
  src/Microsoft.ML.Transforms/RandomFourierFeaturizing.cs
  src/Microsoft.ML.Transforms/Text/StopWordsRemovingTransformer.cs
  src/Microsoft.ML.Transforms/Text/TextFeaturizingEstimator.cs
  test/BaselineOutput/Common/EntryPoints/core_ep-list.tsv
  test/Microsoft.ML.Core.Tests/UnitTests/TestEntryPoints.cs
  test/Microsoft.ML.Tests/ScenariosWithDirectInstantiation/TensorflowTests.cs
  test/Microsoft.ML.Tests/Transformers/NormalizerTests.cs
  test/Microsoft.ML.Tests/Transformers/PcaTests.cs
  test/Microsoft.ML.Tests/Transformers/RffTests.cs
Labels: api

#2365 Creation of components through MLContext and cleanup (Convert, DropSlots, FeatureSelection)
  src/Microsoft.ML.Data/Transforms/ConversionsExtensionsCatalog.cs
  src/Microsoft.ML.Data/Transforms/FeatureContributionCalculationTransformer.cs
  src/Microsoft.ML.Data/Transforms/SlotsDroppingTransformer.cs
  src/Microsoft.ML.Data/Transforms/TypeConverting.cs
  src/Microsoft.ML.EntryPoints/FeatureCombiner.cs
  src/Microsoft.ML.FastTree/FastTree.cs
  src/Microsoft.ML.StaticPipe/TransformsStatic.cs
  src/Microsoft.ML.Transforms/CountFeatureSelection.cs
  src/Microsoft.ML.Transforms/EntryPoints/SelectFeatures.cs
  src/Microsoft.ML.Transforms/MissingValueDroppingTransformer.cs
  src/Microsoft.ML.Transforms/MissingValueHandlingTransformer.cs
  src/Microsoft.ML.Transforms/MutualInformationFeatureSelection.cs
  src/Microsoft.ML.Transforms/NAHandling.cs
  test/BaselineOutput/Common/EntryPoints/core_ep-list.tsv
  test/Microsoft.ML.TestFramework/DataPipe/TestDataPipe.cs
  test/Microsoft.ML.Tests/Transformers/ConvertTests.cs
  test/Microsoft.ML.Tests/Transformers/FeatureSelectionTests.cs
Labels: api

#2450 ValueMappingEstimator documentation update
  src/Microsoft.ML.Data/Transforms/doc.xml
Labels: documentation

#2526 Update calibrator estimators to be more suitable.
  docs/samples/Microsoft.ML.Samples/Dynamic/Calibrator.cs
  src/Microsoft.ML.Core/BestFriendAttribute.cs
  src/Microsoft.ML.Data/Prediction/Calibrator.cs
  src/Microsoft.ML.Data/Prediction/CalibratorCatalog.cs
  src/Microsoft.ML.Data/TrainCatalog.cs
  src/Microsoft.ML.FastTree/RandomForestClassification.cs
  src/Microsoft.ML.StandardLearners/Standard/MultiClass/MetaMulticlassTrainer.cs
  src/Microsoft.ML.StandardLearners/Standard/Online/AveragedPerceptron.cs
  src/Microsoft.ML.StandardLearners/Standard/Online/LinearSvm.cs
  src/Microsoft.ML.StandardLearners/Standard/SdcaBinary.cs
  src/Microsoft.ML.StandardLearners/StandardLearnersCatalog.cs
  test/Microsoft.ML.Tests/Scenarios/OvaTest.cs
  test/Microsoft.ML.Tests/TrainerEstimators/CalibratorEstimators.cs
  test/Microsoft.ML.Tests/TrainerEstimators/MetalinearEstimators.cs
Labels: api

#2510 Creation of components through MLContext, internalization, and renaming
  docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/PriorTrainerSample.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/RandomTrainerSample.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/CustomMappingSample.cs
  src/Microsoft.ML.Data/DataLoadSave/Text/TextLoader.cs
  src/Microsoft.ML.Data/DataLoadSave/TransformWrapper.cs
  src/Microsoft.ML.Data/Scorers/PredictionTransformer.cs
  src/Microsoft.ML.FastTree/FastTreeRegression.cs
  src/Microsoft.ML.FastTree/FastTreeTweedie.cs
  src/Microsoft.ML.LightGBM/LightGbmRankingTrainer.cs
  src/Microsoft.ML.OnnxTransform/DnnImageFeaturizerTransform.cs
  src/Microsoft.ML.OnnxTransform/OnnxCatalog.cs
  src/Microsoft.ML.StandardLearners/FactorizationMachine/FieldAwareFactorizationMachineModelParameters.cs
  src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/LogisticRegression.cs
  src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/MulticlassLogisticRegression.cs
  src/Microsoft.ML.StandardLearners/Standard/MultiClass/MultiClassNaiveBayesTrainer.cs
  src/Microsoft.ML.StandardLearners/Standard/MultiClass/Ova.cs
  src/Microsoft.ML.StandardLearners/Standard/MultiClass/Pkpd.cs
  src/Microsoft.ML.StandardLearners/Standard/Online/AveragedPerceptron.cs
  src/Microsoft.ML.StandardLearners/Standard/SdcaMultiClass.cs
  src/Microsoft.ML.StandardLearners/Standard/Simple/SimpleTrainers.cs
  src/Microsoft.ML.StandardLearners/StandardLearnersCatalog.cs
  src/Microsoft.ML.TensorFlow/TensorflowCatalog.cs
  src/Microsoft.ML.TensorFlow/TensorflowTransform.cs
  src/Microsoft.ML.Transforms/CustomMappingCatalog.cs
  src/Microsoft.ML.Transforms/CustomMappingTransformer.cs
  test/BaselineOutput/Common/EntryPoints/core_ep-list.tsv
  test/Microsoft.ML.OnnxTransformTest/DnnImageFeaturizerTest.cs
  test/Microsoft.ML.Tests/ScenariosWithDirectInstantiation/TensorflowTests.cs
  test/Microsoft.ML.Tests/TrainerEstimators/PriorRandomTests.cs
  test/Microsoft.ML.Tests/TrainerEstimators/TrainerEstimators.cs
Labels: api

#2506 Typed SDCA binary trainers
  docs/samples/Microsoft.ML.Samples/Dynamic/Calibrator.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/BinaryClassification/SDCALogisticRegression.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/BinaryClassification/SDCASupportVectorMachine.cs
  docs/samples/Microsoft.ML.Samples/Static/SDCABinaryClassification.cs
  src/Microsoft.ML.HalLearners/SymSgdClassificationTrainer.cs
  src/Microsoft.ML.SamplesUtils/SamplesDatasetUtils.cs
  src/Microsoft.ML.StandardLearners/Standard/SdcaBinary.cs
  src/Microsoft.ML.StandardLearners/StandardLearnersCatalog.cs
  src/Microsoft.ML.StaticPipe/OnlineLearnerStatic.cs
  src/Microsoft.ML.StaticPipe/SdcaStaticExtensions.cs
  src/Microsoft.ML.StaticPipe/TrainerEstimatorReconciler.cs
  test/BaselineOutput/Common/EntryPoints/core_ep-list.tsv
  test/BaselineOutput/Common/EntryPoints/core_manifest.json
  test/Microsoft.ML.Benchmarks/PredictionEngineBench.cs
  test/Microsoft.ML.Core.Tests/UnitTests/TestEntryPoints.cs
  test/Microsoft.ML.StaticPipelineTesting/Training.cs
  test/Microsoft.ML.Tests/FeatureContributionTests.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/FileBasedSavingOfData.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/IntrospectiveTraining.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/Metacomponents.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/MultithreadedPrediction.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/SimpleTrainAndPredict.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/TrainSaveModelAndPredict.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/TrainWithInitialPredictor.cs
  test/Microsoft.ML.Tests/TrainerEstimators/MetalinearEstimators.cs
  test/Microsoft.ML.Tests/TrainerEstimators/SdcaTests.cs
Labels: api

#2548 [Tiny & Simple Change] Example classes should be static
  docs/samples/Microsoft.ML.Samples/Dynamic/Calibrator.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/DataOperations/BootstrapSample.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/FastTreeRegression.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/FeatureContributionCalculationTransform.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/FeatureSelectionTransform.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/FieldAwareFactorizationMachine.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/GeneralizedAdditiveModels.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/IidChangePointDetectorTransform.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/IidSpikeDetectorTransform.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/ImageAnalytics/ConvertToGrayScale.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/ImageAnalytics/ExtractPixels.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/ImageAnalytics/LoadImage.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/ImageAnalytics/ResizeImage.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/KMeans.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/KeyToValueValueToKey.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/LdaTransform.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/LogisticRegression.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/NgramExtraction.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Normalizer.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/OnnxTransform.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/PermutationFeatureImportance/PFIHelper.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/PermutationFeatureImportance/PFIRegressionExample.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/PermutationFeatureImportance/PfiBinaryClassificationExample.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/ProjectionTransforms.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/SDCARegression.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/SsaChangePointDetectorTransform.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/SsaSpikeDetectorTransform.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/StopWordRemoverTransform.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/TensorFlow/ImageClassification.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/TensorFlow/TextClassification.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/TextTransform.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/BinaryClassification/SDCALogisticRegression.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/BinaryClassification/SDCASupportVectorMachine.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/PriorTrainerSample.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/RandomTrainerSample.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/Recommendation/MatrixFactorization.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/Recommendation/MatrixFactorizationWithOptions.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/Concatenate.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/CopyColumns.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/CustomMappingSample.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/DropColumns.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/SelectColumns.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/ValueMapping.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/ValueMappingFloatToString.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/ValueMappingStringToArray.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/ValueMappingStringToKeyType.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/WordEmbeddingTransform.cs
Labels: enhancement

#2517 Documentation for BinaryClassification.AveragedPerceptron (V2)
  docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/BinaryClassification/AveragedPerceptron.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/BinaryClassification/AveragedPerceptronWithOptions.cs
  src/Microsoft.ML.SamplesUtils/ConsoleUtils.cs
  src/Microsoft.ML.SamplesUtils/Microsoft.ML.SamplesUtils.csproj
  src/Microsoft.ML.SamplesUtils/SamplesDatasetUtils.cs
  src/Microsoft.ML.StandardLearners/Standard/Online/AveragedLinear.cs
  src/Microsoft.ML.StandardLearners/Standard/Online/AveragedPerceptron.cs
  src/Microsoft.ML.StandardLearners/Standard/Online/LinearSvm.cs
  src/Microsoft.ML.StandardLearners/Standard/Online/OnlineGradientDescent.cs
  src/Microsoft.ML.StandardLearners/Standard/Online/OnlineLinear.cs
  src/Microsoft.ML.StandardLearners/Standard/Online/doc.xml
  src/Microsoft.ML.StandardLearners/StandardLearnersCatalog.cs
  test/BaselineOutput/Common/EntryPoints/core_manifest.json
  test/Microsoft.ML.Core.Tests/UnitTests/TestEntryPoints.cs
  test/Microsoft.ML.Predictor.Tests/TestPredictors.cs
  test/Microsoft.ML.Tests/Scenarios/Api/TestApi.cs
  test/Microsoft.ML.Tests/Scenarios/OvaTest.cs
Labels: documentation

#2528 Renaming .Train to .Fit in TrainerEstimators
  src/Microsoft.ML.Data/Training/TrainerEstimatorBase.cs
  src/Microsoft.ML.FastTree/FastTreeClassification.cs
  src/Microsoft.ML.FastTree/FastTreeRanking.cs
  src/Microsoft.ML.FastTree/FastTreeRegression.cs
  src/Microsoft.ML.FastTree/FastTreeTweedie.cs
  src/Microsoft.ML.FastTree/GamClassification.cs
  src/Microsoft.ML.FastTree/GamRegression.cs
  src/Microsoft.ML.FastTree/RandomForestClassification.cs
  src/Microsoft.ML.FastTree/RandomForestRegression.cs
  src/Microsoft.ML.HalLearners/OlsLinearRegression.cs
  src/Microsoft.ML.HalLearners/SymSgdClassificationTrainer.cs
  src/Microsoft.ML.LightGBM/LightGbmBinaryTrainer.cs
  src/Microsoft.ML.LightGBM/LightGbmMulticlassTrainer.cs
  src/Microsoft.ML.LightGBM/LightGbmRankingTrainer.cs
  src/Microsoft.ML.LightGBM/LightGbmRegressionTrainer.cs
  src/Microsoft.ML.Recommender/MatrixFactorizationTrainer.cs
  src/Microsoft.ML.StandardLearners/FactorizationMachine/FactorizationMachineTrainer.cs
  src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/LogisticRegression.cs
  src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/MulticlassLogisticRegression.cs
  src/Microsoft.ML.StandardLearners/Standard/MultiClass/Ova.cs
  src/Microsoft.ML.StandardLearners/Standard/PoissonRegression/PoissonRegression.cs
  src/Microsoft.ML.StandardLearners/Standard/SdcaBinary.cs
  src/Microsoft.ML.StandardLearners/Standard/Simple/SimpleTrainers.cs
  src/Microsoft.ML.Sweeper/Algorithms/SmacSweeper.cs
  test/Microsoft.ML.Functional.Tests/Validation.cs
  test/Microsoft.ML.Tests/TrainerEstimators/FAFMEstimator.cs
  test/Microsoft.ML.Tests/TrainerEstimators/LbfgsTests.cs
  test/Microsoft.ML.Tests/TrainerEstimators/MatrixFactorizationTests.cs
  test/Microsoft.ML.Tests/TrainerEstimators/OlsLinearRegressionTests.cs
  test/Microsoft.ML.Tests/TrainerEstimators/SymSgdClassificationTests.cs
  test/Microsoft.ML.Tests/TrainerEstimators/TrainerEstimators.cs
  test/Microsoft.ML.Tests/TrainerEstimators/TreeEstimators.cs
Labels: api

#2564 Make primal stochastic trainer also typed
  docs/code/MlNetCookBook.md
  docs/samples/Microsoft.ML.Samples/Dynamic/SDCARegression.cs
  src/Microsoft.ML.LightGBM.StaticPipe/LightGbmStaticExtensions.cs
  src/Microsoft.ML.StandardLearners/Standard/SdcaBinary.cs
  src/Microsoft.ML.StandardLearners/StandardLearnersCatalog.cs
  src/Microsoft.ML.StaticPipe/SgdStatic.cs
  test/BaselineOutput/Common/EntryPoints/core_ep-list.tsv
  test/BaselineOutput/Common/EntryPoints/core_manifest.json
  test/Microsoft.ML.StaticPipelineTesting/Training.cs
  test/Microsoft.ML.Tests/FeatureContributionTests.cs
  test/Microsoft.ML.Tests/OnnxConversionTest.cs
  test/Microsoft.ML.Tests/Scenarios/Api/CookbookSamples/CookbookSamplesDynamicApi.cs
  test/Microsoft.ML.Tests/TrainerEstimators/TrainerEstimators.cs
Labels: api

#2578 [One-line change] Internalize MamlEvaluatorBase
  src/Microsoft.ML.Data/Evaluators/MamlEvaluator.cs
Labels: api

#2600 Lockdown TrainerEstimatorBase class.
  src/Microsoft.ML.Data/Training/TrainerEstimatorBase.cs
  src/Microsoft.ML.FastTree/FastTreeClassification.cs
  src/Microsoft.ML.FastTree/FastTreeRanking.cs
  src/Microsoft.ML.FastTree/FastTreeRegression.cs
  src/Microsoft.ML.FastTree/FastTreeTweedie.cs
  src/Microsoft.ML.FastTree/GamClassification.cs
  src/Microsoft.ML.FastTree/GamRegression.cs
  src/Microsoft.ML.FastTree/RandomForestClassification.cs
  src/Microsoft.ML.FastTree/RandomForestRegression.cs
  src/Microsoft.ML.HalLearners/OlsLinearRegression.cs
  src/Microsoft.ML.HalLearners/SymSgdClassificationTrainer.cs
  src/Microsoft.ML.KMeansClustering/KMeansPlusPlusTrainer.cs
  src/Microsoft.ML.LightGBM/LightGbmBinaryTrainer.cs
  src/Microsoft.ML.LightGBM/LightGbmMulticlassTrainer.cs
  src/Microsoft.ML.LightGBM/LightGbmRankingTrainer.cs
  src/Microsoft.ML.LightGBM/LightGbmRegressionTrainer.cs
  src/Microsoft.ML.PCA/PcaTrainer.cs
  src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/LogisticRegression.cs
  src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/MulticlassLogisticRegression.cs
  src/Microsoft.ML.StandardLearners/Standard/MultiClass/MultiClassNaiveBayesTrainer.cs
  src/Microsoft.ML.StandardLearners/Standard/Online/AveragedPerceptron.cs
  src/Microsoft.ML.StandardLearners/Standard/Online/LinearSvm.cs
  src/Microsoft.ML.StandardLearners/Standard/Online/OnlineGradientDescent.cs
  src/Microsoft.ML.StandardLearners/Standard/PoissonRegression/PoissonRegression.cs
  src/Microsoft.ML.StandardLearners/Standard/SdcaBinary.cs
  src/Microsoft.ML.StandardLearners/Standard/SdcaMultiClass.cs
  src/Microsoft.ML.StandardLearners/Standard/SdcaRegression.cs
  test/Microsoft.ML.Tests/TrainerEstimators/SymSgdClassificationTests.cs
Labels: api

#2607 Lockdown Microsoft.ML.Data Data folder
  src/Microsoft.ML.Data/Data/BufferBuilder.cs
  src/Microsoft.ML.Data/Data/Combiner.cs
  src/Microsoft.ML.Data/Data/DataViewUtils.cs
  src/Microsoft.ML.Data/Data/RowCursorUtils.cs
  src/Microsoft.ML.Data/Data/SchemaDefinition.cs
  src/Microsoft.ML.Data/DataView/ArrayDataViewBuilder.cs
Labels: api

#2595 Use custom BlockingQueue to significantly improve F5 perf with SDCA without caching
  src/Microsoft.ML.Data/DataLoadSave/Text/BlockingQueue.cs
  src/Microsoft.ML.Data/DataLoadSave/Text/TextLoaderCursor.cs
Labels: perf

#2608 Lockdown Microsoft.ML.Data Dataview folder.
  src/Microsoft.ML.Data/DataView/AppendRowsDataView.cs
  src/Microsoft.ML.Data/DataView/CompositeRowToRowMapper.cs
  src/Microsoft.ML.Data/DataView/EmptyDataView.cs
  src/Microsoft.ML.Data/DataView/LambdaFilter.cs
  src/Microsoft.ML.Data/DataView/OpaqueDataView.cs
  src/Microsoft.ML.Data/DataView/SimpleRow.cs
  src/Microsoft.ML.Data/DataView/TypedCursor.cs
  src/Microsoft.ML.Data/DataView/ZipDataView.cs
  src/Microsoft.ML.Data/Evaluators/BinaryClassifierEvaluator.cs
  test/Microsoft.ML.StaticPipelineTesting/StaticPipeTests.cs
Labels: api

#2511 Lockdown Microsoft.ML.FastTree public surface
  src/Microsoft.ML.Data/Dirty/PredictorInterfaces.cs
  src/Microsoft.ML.FastTree/BoostingFastTree.cs
  src/Microsoft.ML.FastTree/Dataset/Dataset.cs
  src/Microsoft.ML.FastTree/Dataset/DatasetUtils.cs
  src/Microsoft.ML.FastTree/Dataset/Feature.cs
  src/Microsoft.ML.FastTree/Dataset/FeatureFlock.cs
  src/Microsoft.ML.FastTree/Dataset/FeatureHistogram.cs
  src/Microsoft.ML.FastTree/Dataset/IntArray.cs
  src/Microsoft.ML.FastTree/FastTree.cs
  src/Microsoft.ML.FastTree/FastTreeClassification.cs
  src/Microsoft.ML.FastTree/FastTreeRanking.cs
  src/Microsoft.ML.FastTree/FastTreeRegression.cs
  src/Microsoft.ML.FastTree/FastTreeTweedie.cs
  src/Microsoft.ML.FastTree/GamClassification.cs
  src/Microsoft.ML.FastTree/GamModelParameters.cs
  src/Microsoft.ML.FastTree/GamRegression.cs
  src/Microsoft.ML.FastTree/GamTrainer.cs
  src/Microsoft.ML.FastTree/QuantileStatistics.cs
  src/Microsoft.ML.FastTree/RandomForest.cs
  src/Microsoft.ML.FastTree/RandomForestClassification.cs
  src/Microsoft.ML.FastTree/RandomForestRegression.cs
  src/Microsoft.ML.FastTree/Training/Applications/GradientWrappers.cs
  src/Microsoft.ML.FastTree/Training/Applications/ObjectiveFunction.cs
  src/Microsoft.ML.FastTree/Training/BaggingProvider.cs
  src/Microsoft.ML.FastTree/Training/DcgCalculator.cs
  src/Microsoft.ML.FastTree/Training/DcgPermutationComparer.cs
  src/Microsoft.ML.FastTree/Training/DocumentPartitioning.cs
  src/Microsoft.ML.FastTree/Training/EnsembleCompression/LassoFit.cs
  src/Microsoft.ML.FastTree/Training/OptimizationAlgorithms/GradientDescent.cs
  src/Microsoft.ML.FastTree/Training/OptimizationAlgorithms/OptimizationAlgorithm.cs
  src/Microsoft.ML.FastTree/Training/RegressionTreeNodeDocuments.cs
  src/Microsoft.ML.FastTree/Training/ScoreTracker.cs
  src/Microsoft.ML.FastTree/Training/StepSearch.cs
  src/Microsoft.ML.FastTree/Training/Test.cs
  src/Microsoft.ML.FastTree/Training/WinLossCalculator.cs
  src/Microsoft.ML.FastTree/Utils/Algorithms.cs
  src/Microsoft.ML.FastTree/Utils/BlockingThreadPool.cs
  src/Microsoft.ML.FastTree/Utils/BufferPoolManager.cs
  src/Microsoft.ML.FastTree/Utils/LinqExtensions.cs
  src/Microsoft.ML.FastTree/Utils/MD5Hasher.cs
  src/Microsoft.ML.FastTree/Utils/MappedObjectPool.cs
  src/Microsoft.ML.FastTree/Utils/PseudorandomFunction.cs
  src/Microsoft.ML.FastTree/Utils/StreamExtensions.cs
  src/Microsoft.ML.FastTree/Utils/ThreadTaskManager.cs
  src/Microsoft.ML.FastTree/Utils/Timer.cs
  src/Microsoft.ML.FastTree/Utils/ToByteArrayExtensions.cs
  src/Microsoft.ML.FastTree/Utils/VectorUtils.cs
  src/Microsoft.ML.LightGBM/LightGbmBinaryTrainer.cs
  src/Microsoft.ML.LightGBM/LightGbmRankingTrainer.cs
  src/Microsoft.ML.LightGBM/LightGbmRegressionTrainer.cs
Labels: api

#2544 Lockdown Microsoft.ML.OnnxTransform public surface, possibly rename
  Microsoft.ML.sln
  docs/samples/Microsoft.ML.Samples/Microsoft.ML.Samples.csproj
  pkg/Microsoft.ML.OnnxTransform/Microsoft.ML.OnnxTransform.symbols.nupkgproj
  pkg/Microsoft.ML.OnnxTransformer/Microsoft.ML.OnnxTransformer.nupkgproj
  pkg/Microsoft.ML.OnnxTransformer/Microsoft.ML.OnnxTransformer.symbols.nupkgproj
  src/Microsoft.ML.Console/Microsoft.ML.Console.csproj
  src/Microsoft.ML.Core/Properties/AssemblyInfo.cs
  src/Microsoft.ML.Data/Properties/AssemblyInfo.cs
  src/Microsoft.ML.DnnImageFeaturizer.AlexNet/Microsoft.ML.DnnImageFeaturizer.AlexNet.csproj
  src/Microsoft.ML.DnnImageFeaturizer.ResNet101/Microsoft.ML.DnnImageFeaturizer.ResNet101.csproj
  src/Microsoft.ML.DnnImageFeaturizer.ResNet18/Microsoft.ML.DnnImageFeaturizer.ResNet18.csproj
  src/Microsoft.ML.DnnImageFeaturizer.ResNet50/Microsoft.ML.DnnImageFeaturizer.ResNet50.csproj
  src/Microsoft.ML.OnnxTransformer.StaticPipe/DnnImageFeaturizerStaticExtensions.cs
  src/Microsoft.ML.OnnxTransformer.StaticPipe/Microsoft.ML.OnnxTransformer.StaticPipe.csproj
  src/Microsoft.ML.OnnxTransformer.StaticPipe/OnnxStaticExtensions.cs
  src/Microsoft.ML.OnnxTransformer/DnnImageFeaturizerTransform.cs
  src/Microsoft.ML.OnnxTransformer/Microsoft.ML.OnnxTransformer.csproj
  src/Microsoft.ML.OnnxTransformer/OnnxCatalog.cs
  src/Microsoft.ML.OnnxTransformer/OnnxTransform.cs
  src/Microsoft.ML.OnnxTransformer/OnnxUtils.cs
  src/Microsoft.ML.OnnxTransformer/Properties/AssemblyInfo.cs
  src/Microsoft.ML.OnnxTransformer/doc.xml
  test/Microsoft.ML.Functional.Tests/Microsoft.ML.Functional.Tests.csproj
  test/Microsoft.ML.OnnxTransformerTest/DnnImageFeaturizerTest.cs
  test/Microsoft.ML.OnnxTransformerTest/Microsoft.ML.OnnxTransformerTest.csproj
  test/Microsoft.ML.OnnxTransformerTest/OnnxTransformTests.cs
  test/Microsoft.ML.Tests/Microsoft.ML.Tests.csproj
Labels: api

#2625 Lockdown Microsoft.ML.Onnx public surface
  Microsoft.ML.sln
  pkg/Microsoft.ML.Onnx/Microsoft.ML.Onnx.symbols.nupkgproj
  pkg/Microsoft.ML.OnnxConverter/Microsoft.ML.OnnxConverter.nupkgproj
  pkg/Microsoft.ML.OnnxConverter/Microsoft.ML.OnnxConverter.symbols.nupkgproj
  src/Microsoft.ML.Console/Microsoft.ML.Console.csproj
  src/Microsoft.ML.Core/Properties/AssemblyInfo.cs
  src/Microsoft.ML.Data/DataView/RowToRowMapperTransform.cs
  src/Microsoft.ML.Data/Model/Onnx/ICanSaveOnnx.cs
  src/Microsoft.ML.Data/Model/Onnx/OnnxContext.cs
  src/Microsoft.ML.Data/Model/Onnx/OnnxNode.cs
  src/Microsoft.ML.Data/Prediction/Calibrator.cs
  src/Microsoft.ML.Data/Properties/AssemblyInfo.cs
  src/Microsoft.ML.Data/Scorers/BinaryClassifierScorer.cs
  src/Microsoft.ML.Data/Scorers/GenericScorer.cs
  src/Microsoft.ML.Data/Scorers/MultiClassClassifierScorer.cs
  src/Microsoft.ML.Data/Scorers/PredictedLabelScorerBase.cs
  src/Microsoft.ML.Data/Scorers/SchemaBindablePredictorWrapper.cs
  src/Microsoft.ML.Data/Transforms/ColumnConcatenatingTransformer.cs
  src/Microsoft.ML.Data/Transforms/ColumnCopying.cs
  src/Microsoft.ML.Data/Transforms/KeyToVector.cs
  src/Microsoft.ML.Data/Transforms/NormalizeColumn.cs
  src/Microsoft.ML.Data/Transforms/NormalizeColumnDbl.cs
  src/Microsoft.ML.Data/Transforms/NormalizeColumnSng.cs
  src/Microsoft.ML.Data/Transforms/NormalizeUtils.cs
  src/Microsoft.ML.Data/Transforms/Normalizer.cs
  src/Microsoft.ML.Data/Transforms/TransformBase.cs
  src/Microsoft.ML.Data/Transforms/TypeConverting.cs
  src/Microsoft.ML.Data/Transforms/ValueToKeyMappingTransformer.cs
  src/Microsoft.ML.DnnImageFeaturizer.AlexNet/AlexNetExtension.cs
  src/Microsoft.ML.DnnImageFeaturizer.ResNet101/ResNet101Extension.cs
  src/Microsoft.ML.DnnImageFeaturizer.ResNet18/ResNet18Extension.cs
  src/Microsoft.ML.DnnImageFeaturizer.ResNet50/ResNet50Extension.cs
  src/Microsoft.ML.FastTree/FastTree.cs
  src/Microsoft.ML.KMeansClustering/KMeansModelParameters.cs
  src/Microsoft.ML.Onnx/OnnxMl.cs
  src/Microsoft.ML.OnnxConverter/AssemblyInfo.cs
  src/Microsoft.ML.OnnxConverter/Microsoft.ML.OnnxConverter.csproj
  src/Microsoft.ML.OnnxConverter/OnnxContextImpl.cs
  src/Microsoft.ML.OnnxConverter/OnnxExportExtensions.cs
  src/Microsoft.ML.OnnxConverter/OnnxMl.cs
  src/Microsoft.ML.OnnxConverter/OnnxMl.md
  src/Microsoft.ML.OnnxConverter/OnnxNodeImpl.cs
  src/Microsoft.ML.OnnxConverter/OnnxUtils.cs
  src/Microsoft.ML.OnnxConverter/SaveOnnxCommand.cs
  src/Microsoft.ML.OnnxTransformer/DnnImageFeaturizerTransform.cs
  src/Microsoft.ML.StandardLearners/Standard/LinearModelParameters.cs
  src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/MulticlassLogisticRegression.cs
  src/Microsoft.ML.TimeSeries/SequentialTransformerBase.cs
  src/Microsoft.ML.Transforms/MissingValueReplacing.cs
  src/Microsoft.ML.Transforms/Text/WordEmbeddingsExtractor.cs
  test/BaselineOutput/Common/EntryPoints/core_ep-list.tsv
  test/Directory.Build.props
  test/Microsoft.ML.Core.Tests/Microsoft.ML.Core.Tests.csproj
  test/Microsoft.ML.Core.Tests/UnitTests/TestEntryPoints.cs
  test/Microsoft.ML.Functional.Tests/Microsoft.ML.Functional.Tests.csproj
  test/Microsoft.ML.Tests/Microsoft.ML.Tests.csproj
  test/Microsoft.ML.Tests/OnnxConversionTest.cs
Labels: api

#2417 Textloader internalizations, documentation, and Arguments refactoring
  src/Microsoft.ML.Data/DataLoadSave/DataReaderExtensions.cs
  src/Microsoft.ML.Data/DataLoadSave/Text/TextLoader.cs
  src/Microsoft.ML.Data/DataLoadSave/Text/TextLoaderSaverCatalog.cs
  src/Microsoft.ML.StaticPipe/LocalPathReader.cs
  test/BaselineOutput/Common/EntryPoints/core_manifest.json
  test/Microsoft.ML.Core.Tests/UnitTests/TestEntryPoints.cs
  test/Microsoft.ML.Predictor.Tests/TestPredictors.cs
Labels: api, documentation

#2651 Metadata utils internalization, migration of few useful methods
  docs/samples/Microsoft.ML.Samples/Dynamic/NgramExtraction.cs
  src/Microsoft.ML.Core/Data/MetadataBuilderExtensions.cs
  src/Microsoft.ML.Core/Data/MetadataUtils.cs
  src/Microsoft.ML.Data/Data/SchemaAnnotationsExtensions.cs
  src/Microsoft.ML.Data/EntryPoints/PredictorModelImpl.cs
  src/Microsoft.ML.Data/Evaluators/EvaluatorUtils.cs
  src/Microsoft.ML.Data/Evaluators/MultiClassClassifierEvaluator.cs
  src/Microsoft.ML.Data/Transforms/InvertHashUtils.cs
  src/Microsoft.ML.Data/Transforms/MetadataDispatcher.cs
  src/Microsoft.ML.Transforms/Text/NgramTransform.cs
Labels: api

#2648 Microsoft.ML.Transforms assembly lockdown
  src/Microsoft.ML.Data/Transforms/Hashing.cs
  src/Microsoft.ML.Data/Transforms/KeyToVector.cs
  src/Microsoft.ML.Data/Transforms/Normalizer.cs
  src/Microsoft.ML.Data/Transforms/OneToOneTransformerBase.cs
  src/Microsoft.ML.HalLearners/VectorWhitening.cs
  src/Microsoft.ML.ImageAnalytics/ImageGrayscale.cs
  src/Microsoft.ML.ImageAnalytics/ImageLoader.cs
  src/Microsoft.ML.ImageAnalytics/ImagePixelExtractor.cs
  src/Microsoft.ML.ImageAnalytics/ImageResizer.cs
  src/Microsoft.ML.PCA/PcaTransformer.cs
  src/Microsoft.ML.Transforms/CategoricalCatalog.cs
  src/Microsoft.ML.Transforms/CompositeTransformer.cs
  src/Microsoft.ML.Transforms/FourierDistributionSampler.cs
  src/Microsoft.ML.Transforms/GcnTransform.cs
  src/Microsoft.ML.Transforms/KeyToVectorMapping.cs
  src/Microsoft.ML.Transforms/MissingValueDroppingTransformer.cs
  src/Microsoft.ML.Transforms/MissingValueReplacing.cs
  src/Microsoft.ML.Transforms/ProjectionCatalog.cs
  src/Microsoft.ML.Transforms/RandomFourierFeaturizing.cs
  src/Microsoft.ML.Transforms/Text/NgramHashingTransformer.cs
  src/Microsoft.ML.Transforms/Text/NgramTransform.cs
  src/Microsoft.ML.Transforms/Text/StopWordsRemovingTransformer.cs
  src/Microsoft.ML.Transforms/Text/TextCatalog.cs
  src/Microsoft.ML.Transforms/Text/TextFeaturizingEstimator.cs
  src/Microsoft.ML.Transforms/Text/TextNormalizing.cs
  src/Microsoft.ML.Transforms/Text/TokenizingByCharacters.cs
  src/Microsoft.ML.Transforms/Text/WordEmbeddingsExtractor.cs
  src/Microsoft.ML.Transforms/Text/WordTokenizing.cs
  src/Microsoft.ML.Transforms/Text/WrappedTextTransformers.cs
Labels: api

#2635 Internalize Microsoft.ML.Data Evaluators folder.
  src/Microsoft.ML.Data/Evaluators/EvaluatorUtils.cs
Labels: api

#2632 Internalization of OneToOne and ManyToOne Column classes
  src/Microsoft.ML.Data/Transforms/ColumnBindingsBase.cs
  src/Microsoft.ML.Transforms/Text/WordHashBagProducingTransform.cs
Labels: api

#2649 Hide much of Microsoft.ML.Model namespace.
  src/Microsoft.ML.Core/Data/ModelHeader.cs
  src/Microsoft.ML.Core/Data/ModelLoadContext.cs
  src/Microsoft.ML.Core/Data/ModelLoading.cs
  src/Microsoft.ML.Core/Data/ModelSaveContext.cs
  src/Microsoft.ML.Core/Data/ModelSaving.cs
  src/Microsoft.ML.Core/Data/Repository.cs
  src/Microsoft.ML.Data/DataLoadSave/TransformWrapper.cs
  src/Microsoft.ML.Data/DataLoadSave/TransformerChain.cs
  src/Microsoft.ML.Data/Dirty/ModelParametersBase.cs
  src/Microsoft.ML.Data/Evaluators/MultiClassClassifierEvaluator.cs
  src/Microsoft.ML.Data/Prediction/CalibratorCatalog.cs
  src/Microsoft.ML.Data/Transforms/InvertHashUtils.cs
  src/Microsoft.ML.Data/Transforms/OneToOneTransformerBase.cs
  src/Microsoft.ML.Data/Transforms/ValueMapping.cs
  src/Microsoft.ML.StandardLearners/Standard/LinearModelParameters.cs
  test/Microsoft.ML.CodeAnalyzer.Tests/Code/ContractsCheckTest.cs
  test/Microsoft.ML.CodeAnalyzer.Tests/Resources/ContractsCheckResource.cs
Labels: api

#2667 Microsoft.ML.Internal.Internallearn namespace requires certain internalization.
  src/Microsoft.ML.Data/Dirty/PredictionUtils.cs
  src/Microsoft.ML.Data/Dirty/PredictorInterfaces.cs
  src/Microsoft.ML.Data/Training/EarlyStoppingCriteria.cs
  src/Microsoft.ML.Data/Utilities/SlotDropper.cs
  src/Microsoft.ML.Data/Utilities/TypeUtils.cs
Labels: api

#2647 Increase build timeout for code coverage CI.
  build/ci/phase-template.yml
Labels: Build

#2630 Change Default Settings in TextLoader
  docs/code/MlNetCookBook.md
  docs/samples/Microsoft.ML.Samples/Dynamic/TensorFlow/TextClassification.cs
  src/Microsoft.ML.Data/DataLoadSave/Text/TextLoader.cs
  src/Microsoft.ML.Data/DataLoadSave/Text/TextLoaderSaverCatalog.cs
  src/Microsoft.ML.Data/DataLoadSave/Text/TextSaver.cs
  src/Microsoft.ML.StaticPipe/DataLoadSaveOperationsExtensions.cs
  src/Microsoft.ML.StaticPipe/TextLoaderStatic.cs
  test/BaselineOutput/Common/EntryPoints/core_manifest.json
  test/BaselineOutput/Common/pcaAnomaly/Default-TrainTest-mnistOneClass-out.txt
  test/BaselineOutput/Common/pcaAnomaly/Default-TrainTest-mnistOneClass-rp.txt
  test/BaselineOutput/Common/pcaAnomaly/NoNorm-TrainTest-mnistOneClass-out.txt
  test/BaselineOutput/Common/pcaAnomaly/NoNorm-TrainTest-mnistOneClass-rp.txt
  test/Microsoft.ML.Benchmarks/PredictionEngineBench.cs
  test/Microsoft.ML.Benchmarks/StochasticDualCoordinateAscentClassifierBench.cs
  test/Microsoft.ML.Core.Tests/UnitTests/TestEntryPoints.cs
  test/Microsoft.ML.FSharp.Tests/SmokeTests.fs
  test/Microsoft.ML.Functional.Tests/DataIO.cs
  test/Microsoft.ML.Functional.Tests/Datasets/TypeTestData.cs
  test/Microsoft.ML.Predictor.Tests/TestPredictors.cs
  test/Microsoft.ML.TestFramework/BaseTestPredictorsMaml.cs
  test/Microsoft.ML.TestFramework/DataPipe/TestDataPipe.cs
  test/Microsoft.ML.TestFramework/DataPipe/TestDataPipeBase.cs
  test/Microsoft.ML.Tests/AnomalyDetectionTests.cs
  test/Microsoft.ML.Tests/BinaryLoaderSaverTests.cs
  test/Microsoft.ML.Tests/OnnxConversionTest.cs
  test/Microsoft.ML.Tests/Scenarios/Api/CookbookSamples/CookbookSamplesDynamicApi.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/DecomposableTrainAndPredict.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/IntrospectiveTraining.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/PredictAndMetadata.cs
  test/Microsoft.ML.Tests/ScenariosWithDirectInstantiation/TensorflowTests.cs
  test/Microsoft.ML.Tests/TextLoaderTests.cs
  test/Microsoft.ML.Tests/TrainerEstimators/TrainerEstimators.cs
  test/Microsoft.ML.Tests/Transformers/CustomMappingTests.cs
  test/Microsoft.ML.TimeSeries.Tests/TimeSeries.cs
Labels: api

#2673 Explicit implementation for IsRowToRowMapper and GetRowToRowMapper
  src/Microsoft.ML.Data/DataLoadSave/TransformWrapper.cs
  src/Microsoft.ML.Data/DataLoadSave/TransformerChain.cs
  src/Microsoft.ML.Data/Prediction/PredictionEngine.cs
  src/Microsoft.ML.Data/Scorers/PredictionTransformer.cs
  src/Microsoft.ML.Data/Transforms/ColumnSelecting.cs
  src/Microsoft.ML.Data/Transforms/RowToRowTransformerBase.cs
  src/Microsoft.ML.TimeSeries/IidAnomalyDetectionBase.cs
  src/Microsoft.ML.TimeSeries/IidChangePointDetector.cs
  src/Microsoft.ML.TimeSeries/IidSpikeDetector.cs
  src/Microsoft.ML.TimeSeries/SequentialAnomalyDetectionTransformBase.cs
  src/Microsoft.ML.TimeSeries/SequentialTransformerBase.cs
  src/Microsoft.ML.TimeSeries/SsaAnomalyDetectionBase.cs
  src/Microsoft.ML.TimeSeries/SsaChangePointDetector.cs
  src/Microsoft.ML.TimeSeries/SsaSpikeDetector.cs
  src/Microsoft.ML.Transforms/CustomMappingTransformer.cs
  src/Microsoft.ML.Transforms/OneHotEncoding.cs
  src/Microsoft.ML.Transforms/OneHotHashEncoding.cs
  src/Microsoft.ML.Transforms/Text/TextFeaturizingEstimator.cs
  test/Microsoft.ML.Benchmarks/HashBench.cs
  test/Microsoft.ML.Tests/Transformers/HashTests.cs
Labels: api

#2504 Towards 1529: replacing the predicates with an IEnumerable on IRowToRowMapper.GetDependencies
  src/Microsoft.ML.Core/Data/IRowToRowMapper.cs
  src/Microsoft.ML.Core/Data/ISchemaBindableMapper.cs
  src/Microsoft.ML.Data/DataView/CompositeRowToRowMapper.cs
  src/Microsoft.ML.Data/DataView/RowToRowMapperTransform.cs
  src/Microsoft.ML.Data/EntryPoints/TransformModelImpl.cs
  src/Microsoft.ML.Data/Prediction/Calibrator.cs
  src/Microsoft.ML.Data/Scorers/FeatureContributionCalculation.cs
  src/Microsoft.ML.Data/Scorers/MultiClassClassifierScorer.cs
  src/Microsoft.ML.Data/Scorers/RowToRowScorerBase.cs
  src/Microsoft.ML.Data/Scorers/SchemaBindablePredictorWrapper.cs
  src/Microsoft.ML.Data/Transforms/ColumnBindingsBase.cs
  src/Microsoft.ML.Data/Transforms/ColumnSelecting.cs
  src/Microsoft.ML.Data/Transforms/NopTransform.cs
  src/Microsoft.ML.Data/Transforms/TransformBase.cs
  src/Microsoft.ML.Ensemble/PipelineEnsemble.cs
  src/Microsoft.ML.FastTree/TreeEnsembleFeaturizer.cs
  src/Microsoft.ML.Recommender/MatrixFactorizationPredictor.cs
  src/Microsoft.ML.StandardLearners/FactorizationMachine/FieldAwareFactorizationMachineUtils.cs
  src/Microsoft.ML.TimeSeries/PredictionFunction.cs
  src/Microsoft.ML.TimeSeries/SequentialTransformerBase.cs
  src/Microsoft.ML.Transforms/OptionalColumnTransform.cs
  test/Microsoft.ML.Tests/Scenarios/Api/CookbookSamples/CookbookSamples.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/SimpleTrainAndPredict.cs
  test/Microsoft.ML.Tests/Scenarios/ClusteringTests.cs
Labels: api

#2710 Make text loaders consistent
  src/Microsoft.ML.Data/DataLoadSave/Text/TextLoader.cs
  src/Microsoft.ML.Data/DataLoadSave/Text/TextLoaderSaverCatalog.cs
  src/Microsoft.ML.Data/Transforms/ValueToKeyMappingTransformer.cs
  src/Microsoft.ML.Transforms/Text/StopWordsRemovingTransformer.cs
  test/Microsoft.ML.Benchmarks/PredictionEngineBench.cs
  test/Microsoft.ML.Benchmarks/StochasticDualCoordinateAscentClassifierBench.cs
  test/Microsoft.ML.Functional.Tests/Datasets/MnistOneClass.cs
  test/Microsoft.ML.Functional.Tests/Datasets/TypeTestData.cs
  test/Microsoft.ML.Functional.Tests/Evaluation.cs
  test/Microsoft.ML.Functional.Tests/Prediction.cs
  test/Microsoft.ML.Functional.Tests/Validation.cs
  test/Microsoft.ML.Tests/TextLoaderTests.cs
  test/Microsoft.ML.Tests/TrainerEstimators/MetalinearEstimators.cs
Labels: api

#2747 Expose split gains in tree models
  src/Microsoft.ML.FastTree/RegressionTree.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/IntrospectiveTraining.cs
Labels: api

#2716 Move ReadFromEnum and CreateEnumerable and add sample
  docs/samples/Microsoft.ML.Samples/Dynamic/DataOperations/BootstrapSample.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/DataOperations/Cache.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/DataOperations/DataViewEnumerable.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/DataOperations/FilterRowsByColumn.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/DataOperations/FilterRowsByKeyColumnFraction.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/DataOperations/FilterRowsByMissingValues.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/DataOperations/ShuffleRows.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/DataOperations/SkipRows.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/DataOperations/TakeRows.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/FeatureContributionCalculationTransform.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/IidChangePointDetectorTransform.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/IidSpikeDetectorTransform.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/OnnxTransform.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/SsaChangePointDetectorTransform.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/SsaSpikeDetectorTransform.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/TensorFlow/ImageClassification.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/BinaryClassification/SDCASupportVectorMachine.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/MulticlassClassification/LightGbm.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/MulticlassClassification/LightGbmWithOptions.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/Recommendation/MatrixFactorization.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/Recommendation/MatrixFactorizationWithOptions.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/Concatenate.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/CopyColumns.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/DropColumns.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/SelectColumns.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/ValueMapping.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/ValueMappingFloatToString.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/ValueMappingStringToArray.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/ValueMappingStringToKeyType.cs
  docs/samples/Microsoft.ML.Samples/Static/LightGBMMulticlassWithInMemoryData.cs
  src/Microsoft.ML.Data/DataLoadSave/DataOperationsCatalog.cs
  src/Microsoft.ML.Data/DataView/TypedCursor.cs
  src/Microsoft.ML.Data/Utilities/ComponentCreation.cs
  src/Microsoft.ML.SamplesUtils/SamplesDatasetUtils.cs
  test/Microsoft.ML.Functional.Tests/Common.cs
  test/Microsoft.ML.Functional.Tests/DataIO.cs
  test/Microsoft.ML.Functional.Tests/Explainability.cs
  test/Microsoft.ML.OnnxTransformerTest/OnnxTransformTests.cs
  test/Microsoft.ML.StaticPipelineTesting/Training.cs
  test/Microsoft.ML.TestFramework/TestSparseDataView.cs
  test/Microsoft.ML.Tests/CollectionsDataViewTest.cs
  test/Microsoft.ML.Tests/Scenarios/Api/CookbookSamples/CookbookSamples.cs
  test/Microsoft.ML.Tests/Scenarios/Api/CookbookSamples/CookbookSamplesDynamicApi.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/DecomposableTrainAndPredict.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/Extensibility.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/MultithreadedPrediction.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/PredictAndMetadata.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/SimpleTrainAndPredict.cs
  test/Microsoft.ML.Tests/Scenarios/Api/Estimators/TrainSaveModelAndPredict.cs
  test/Microsoft.ML.Tests/TrainerEstimators/MatrixFactorizationTests.cs
  test/Microsoft.ML.Tests/TrainerEstimators/SdcaTests.cs
  test/Microsoft.ML.Tests/TrainerEstimators/TreeEstimators.cs
  test/Microsoft.ML.Tests/Transformers/CustomMappingTests.cs
  test/Microsoft.ML.Tests/Transformers/GroupUngroup.cs
  test/Microsoft.ML.Tests/Transformers/WordTokenizeTests.cs
  test/Microsoft.ML.TimeSeries.Tests/TimeSeriesDirectApi.cs
  test/Microsoft.ML.TimeSeries.Tests/TimeSeriesStaticTests.cs
Labels: api

#2745 Remove IMultiStreamSource when path (type: string) exists in text loader APIs
  src/Microsoft.ML.Data/DataLoadSave/Text/TextLoaderSaverCatalog.cs
Labels: api

#2700 Clean up metrics classes.
  docs/samples/Microsoft.ML.Samples/Dynamic/LogisticRegression.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/MulticlassClassification/LightGbm.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/MulticlassClassification/LightGbmWithOptions.cs
  docs/samples/Microsoft.ML.Samples/Static/AveragedPerceptronBinaryClassification.cs
  docs/samples/Microsoft.ML.Samples/Static/FastTreeBinaryClassification.cs
  docs/samples/Microsoft.ML.Samples/Static/FastTreeRegression.cs
  docs/samples/Microsoft.ML.Samples/Static/LightGBMBinaryClassification.cs
  docs/samples/Microsoft.ML.Samples/Static/LightGBMRegression.cs
  docs/samples/Microsoft.ML.Samples/Static/SDCABinaryClassification.cs
  docs/samples/Microsoft.ML.Samples/Static/SDCARegression.cs
  src/Microsoft.ML.Data/Evaluators/Metrics/AnomalyDetectionMetrics.cs
  src/Microsoft.ML.Data/Evaluators/Metrics/BinaryClassificationMetrics.cs
  src/Microsoft.ML.Data/Evaluators/Metrics/ClusteringMetrics.cs
  src/Microsoft.ML.Data/Evaluators/Metrics/MultiClassClassifierMetrics.cs
  src/Microsoft.ML.Data/Evaluators/Metrics/RankingMetrics.cs
  src/Microsoft.ML.Data/Evaluators/Metrics/RegressionMetrics.cs
  src/Microsoft.ML.Data/TrainCatalog.cs
  src/Microsoft.ML.SamplesUtils/ConsoleUtils.cs
  src/Microsoft.ML.Transforms/PermutationFeatureImportanceExtensions.cs
  test/Microsoft.ML.Benchmarks/StochasticDualCoordinateAscentClassifierBench.cs
  test/Microsoft.ML.Functional.Tests/Common.cs
  test/Microsoft.ML.Predictor.Tests/TestIniModels.cs
  test/Microsoft.ML.StaticPipelineTesting/Training.cs
  test/Microsoft.ML.Tests/AnomalyDetectionTests.cs
  test/Microsoft.ML.Tests/Scenarios/Api/CookbookSamples/CookbookSamples.cs
  test/Microsoft.ML.Tests/Scenarios/Api/CookbookSamples/CookbookSamplesDynamicApi.cs
  test/Microsoft.ML.Tests/Scenarios/ClusteringTests.cs
  test/Microsoft.ML.Tests/Scenarios/IrisPlantClassificationTests.cs
  test/Microsoft.ML.Tests/Scenarios/IrisPlantClassificationWithStringLabelTests.cs
  test/Microsoft.ML.Tests/Scenarios/OvaTest.cs
  test/Microsoft.ML.Tests/Scenarios/TensorflowTests.cs
  test/Microsoft.ML.Tests/ScenariosWithDirectInstantiation/IrisPlantClassificationTests.cs
  test/Microsoft.ML.Tests/ScenariosWithDirectInstantiation/TensorflowTests.cs
  test/Microsoft.ML.Tests/TrainerEstimators/FAFMEstimator.cs
  test/Microsoft.ML.Tests/TrainerEstimators/MatrixFactorizationTests.cs
  test/Microsoft.ML.Tests/TrainerEstimators/SdcaTests.cs
  test/Microsoft.ML.Tests/TrainerEstimators/TrainerEstimators.cs
  test/Microsoft.ML.Tests/TrainerEstimators/TreeEstimators.cs
Labels: api

#2754 Replace Float with float
  src/Microsoft.ML.Core/Utilities/BinFinder.cs
  src/Microsoft.ML.Core/Utilities/MathUtils.cs
  src/Microsoft.ML.Core/Utilities/Stats.cs
  src/Microsoft.ML.CpuMath/AlignedMatrix.cs
  src/Microsoft.ML.CpuMath/EigenUtils.cs
  src/Microsoft.ML.CpuMath/ICpuBuffer.cs
  src/Microsoft.ML.Data/Data/Combiner.cs
  src/Microsoft.ML.Data/Depricated/Vector/VBufferMathUtils.cs
  src/Microsoft.ML.Data/Depricated/Vector/VectorUtils.cs
  src/Microsoft.ML.Data/Dirty/PredictionUtils.cs
  src/Microsoft.ML.Data/Evaluators/MultiOutputRegressionEvaluator.cs
  src/Microsoft.ML.Data/Evaluators/QuantileRegressionEvaluator.cs
  src/Microsoft.ML.Data/Evaluators/RegressionEvaluator.cs
  src/Microsoft.ML.Data/Scorers/BinaryClassifierScorer.cs
  src/Microsoft.ML.Data/Scorers/ClusteringScorer.cs
  src/Microsoft.ML.Data/Scorers/MultiClassClassifierScorer.cs
  src/Microsoft.ML.Data/Scorers/PredictedLabelScorerBase.cs
  src/Microsoft.ML.Data/Scorers/SchemaBindablePredictorWrapper.cs
  src/Microsoft.ML.Data/Transforms/GenerateNumberTransform.cs
  src/Microsoft.ML.Data/Transforms/LabelConvertTransform.cs
  src/Microsoft.ML.Data/Transforms/NAFilter.cs
  src/Microsoft.ML.Data/Transforms/RangeFilter.cs
  src/Microsoft.ML.Data/Utils/LossFunctions.cs
  src/Microsoft.ML.FastTree/BoostingFastTree.cs
  src/Microsoft.ML.FastTree/FastTree.cs
  src/Microsoft.ML.FastTree/Training/EarlyStoppingCriteria.cs
  src/Microsoft.ML.FastTree/TreeEnsemble/InternalQuantileRegressionTree.cs
  src/Microsoft.ML.KMeansClustering/KMeansModelParameters.cs
  src/Microsoft.ML.ResultProcessor/ResultProcessor.cs
  src/Microsoft.ML.StandardLearners/Optimizer/DifferentiableFunction.cs
  src/Microsoft.ML.StandardLearners/Optimizer/L1Optimizer.cs
  src/Microsoft.ML.StandardLearners/Optimizer/LineSearch.cs
  src/Microsoft.ML.StandardLearners/Optimizer/OptimizationMonitor.cs
  src/Microsoft.ML.StandardLearners/Optimizer/Optimizer.cs
  src/Microsoft.ML.StandardLearners/Optimizer/SgdOptimizer.cs
  src/Microsoft.ML.StandardLearners/Standard/LinearPredictorUtils.cs
  src/Microsoft.ML.StandardLearners/Standard/SdcaMultiClass.cs
  src/Microsoft.ML.Sweeper/Algorithms/KdoSweeper.cs
  src/Microsoft.ML.Sweeper/Algorithms/NelderMead.cs
  src/Microsoft.ML.Sweeper/Algorithms/SmacSweeper.cs
  src/Microsoft.ML.Sweeper/ISweeper.cs
  src/Microsoft.ML.Sweeper/Parameters.cs
  src/Microsoft.ML.TimeSeries/EigenUtils.cs
  src/Microsoft.ML.Transforms/MissingValueIndicatorTransform.cs
  src/Microsoft.ML.Transforms/Text/NgramUtils.cs
  test/Microsoft.ML.Core.Tests/UnitTests/TestLoss.cs
  test/Microsoft.ML.Predictor.Tests/TestPredictors.cs
  test/Microsoft.ML.TestFramework/DataPipe/TestDataPipe.cs
Labels: code-sanitation

#2780 Add an example of random PCA using in-memory data structure
  docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/AnomalyDetection/RandomizedPcaSample.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/AnomalyDetection/RandomizedPcaSampleWithOptions.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/Recommendation/MatrixFactorization.cs
  docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/Recommendation/MatrixFactorizationWithOptions.cs
  src/Microsoft.ML.PCA/PCACatalog.cs
  test/Microsoft.ML.Tests/AnomalyDetectionTests.cs
Labels: documentation
